export const UPLOAD_MIME_MAP: Record<string, string> = {
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.webp': 'image/webp',
    '.heic': 'image/heic',
    '.heif': 'image/heif',
    '.pdf': 'application/pdf',
    '.txt': 'text/plain',
    '.md': 'text/markdown',
    '.csv': 'text/csv',
    '.json': 'application/json',
    '.xml': 'application/xml',
    '.log': 'text/plain',
    '.rtf': 'application/rtf',
    '.doc': 'application/msword',
    '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    '.xls': 'application/vnd.ms-excel',
    '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    '.ppt': 'application/vnd.ms-powerpoint',
    '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    '.mp3': 'audio/mpeg',
    '.wav': 'audio/wav',
    '.m4a': 'audio/m4a',
    '.aac': 'audio/aac',
    '.aiff': 'audio/aiff',
    '.flac': 'audio/flac',
    '.ogg': 'audio/ogg',
    '.mp4': 'video/mp4',
    '.webm': 'video/webm',
    '.mov': 'video/quicktime',
    '.mpeg': 'video/mpeg',
    '.mpg': 'video/mpeg',
    '.avi': 'video/x-msvideo',
    '.wmv': 'video/x-ms-wmv',
    '.3gp': 'video/3gpp',

    // 3D models / CAD outputs. glb/stl/3mf render in the in-app viewer;
    // STEP is the primary CAD interchange format (download-only). G-code is
    // plain text so the code viewer can open it.
    '.glb': 'model/gltf-binary',
    '.stl': 'model/stl',
    '.3mf': 'model/3mf',
    '.step': 'application/step',
    '.stp': 'application/step',
    '.gcode': 'text/plain',

    // Source code, config, and markup. All served as text/plain so they are
    // safe to serve inline (browsers display them as text, never execute them —
    // this is why .html/.svg map to text/plain rather than their renderable
    // type) and so model APIs that accept text/plain (e.g. Gemini) can ingest
    // them. Agents on local-upload providers read them straight off disk.
    '.py': 'text/plain',
    '.pyw': 'text/plain',
    '.pyi': 'text/plain',
    '.js': 'text/plain',
    '.mjs': 'text/plain',
    '.cjs': 'text/plain',
    '.jsx': 'text/plain',
    '.ts': 'text/plain',
    '.tsx': 'text/plain',
    '.mts': 'text/plain',
    '.cts': 'text/plain',
    '.html': 'text/plain',
    '.htm': 'text/plain',
    '.xhtml': 'text/plain',
    '.svg': 'text/plain',
    '.css': 'text/plain',
    '.scss': 'text/plain',
    '.sass': 'text/plain',
    '.less': 'text/plain',
    '.vue': 'text/plain',
    '.svelte': 'text/plain',
    '.astro': 'text/plain',
    '.yaml': 'text/plain',
    '.yml': 'text/plain',
    '.toml': 'text/plain',
    '.ini': 'text/plain',
    '.cfg': 'text/plain',
    '.conf': 'text/plain',
    '.env': 'text/plain',
    '.properties': 'text/plain',
    '.sh': 'text/plain',
    '.bash': 'text/plain',
    '.zsh': 'text/plain',
    '.fish': 'text/plain',
    '.ps1': 'text/plain',
    '.bat': 'text/plain',
    '.cmd': 'text/plain',
    '.sql': 'text/plain',
    '.go': 'text/plain',
    '.rs': 'text/plain',
    '.rb': 'text/plain',
    '.php': 'text/plain',
    '.java': 'text/plain',
    '.kt': 'text/plain',
    '.kts': 'text/plain',
    '.gradle': 'text/plain',
    '.groovy': 'text/plain',
    '.swift': 'text/plain',
    '.c': 'text/plain',
    '.h': 'text/plain',
    '.cc': 'text/plain',
    '.cpp': 'text/plain',
    '.cxx': 'text/plain',
    '.hpp': 'text/plain',
    '.hh': 'text/plain',
    '.hxx': 'text/plain',
    '.cs': 'text/plain',
    '.m': 'text/plain',
    '.mm': 'text/plain',
    '.scala': 'text/plain',
    '.clj': 'text/plain',
    '.cljs': 'text/plain',
    '.ex': 'text/plain',
    '.exs': 'text/plain',
    '.erl': 'text/plain',
    '.hs': 'text/plain',
    '.lua': 'text/plain',
    '.pl': 'text/plain',
    '.pm': 'text/plain',
    '.r': 'text/plain',
    '.dart': 'text/plain',
    '.tsv': 'text/plain',
    '.markdown': 'text/plain',
    '.rst': 'text/plain',
    '.org': 'text/plain',
    '.tex': 'text/plain',
    '.adoc': 'text/plain',
    '.asciidoc': 'text/plain',
    '.diff': 'text/plain',
    '.patch': 'text/plain',

    // Structured data (kept as their real type → classified as documents).
    '.json5': 'application/json',
    '.jsonc': 'application/json',
    '.ndjson': 'application/x-ndjson',
    '.geojson': 'application/json',
    '.webmanifest': 'application/json',
    '.ipynb': 'application/json',
    '.xsl': 'application/xml',
    '.xslt': 'application/xml',
    '.rss': 'application/xml',
    '.atom': 'application/xml',

    // Archives. Not accepted by any model API (filtered out before sending);
    // here only so /api/uploads serves them with a sensible download type.
    '.zip': 'application/zip',
    '.gz': 'application/gzip',
    '.tgz': 'application/gzip',
    '.tar': 'application/x-tar',
    '.7z': 'application/x-7z-compressed',
    '.rar': 'application/vnd.rar',
    '.bz2': 'application/x-bzip2',
    '.xz': 'application/x-xz',
    '.zst': 'application/zstd',

    // Additional media/document types recovered by content sniffing
    // (lib/file-sniff.ts) when an ingested file has no usable MIME or filename.
    // Listed here so /api/uploads serves them with a real Content-Type and they
    // classify into the right viewer bucket (image/audio/video/document).
    '.opus': 'audio/ogg',
    '.oga': 'audio/ogg',
    '.amr': 'audio/amr',
    '.bmp': 'image/bmp',
    '.tif': 'image/tiff',
    '.tiff': 'image/tiff',
    '.ico': 'image/x-icon',
    '.avif': 'image/avif',
    '.mkv': 'video/x-matroska',
    '.ogv': 'video/ogg',
    '.m4v': 'video/mp4',
    '.ps': 'application/postscript',
    '.epub': 'application/epub+zip',
    '.odt': 'application/vnd.oasis.opendocument.text',
    '.ods': 'application/vnd.oasis.opendocument.spreadsheet',
    '.odp': 'application/vnd.oasis.opendocument.presentation',
}
