import {
  executeCancelTask,
  executeListTasks,
  executeRescheduleTask,
  executeScheduleTask,
} from "../schedule"
import {
  executeGetAgentLog,
  executeGetPastRun,
  executeReadRuntimeIndex,
  executeSearchAgentLogs,
  executeSearchPastRuns,
} from "../observability"
import { executeNotifyInbox } from "../notify"
import { executeInboxActionHistory } from "../inbox-history"
import { executeSetTaskState } from "../task-state"
import { executeApplyUpdate } from "../update-app"
import {
  executeMemoryRecentActivity,
  executeMemorySearch,
} from "../memory-search"
import { executeLibrarySearch } from "../library-search"
import {
  executeMapsCurrentLocation,
  executeMapsDirections,
  executeMapsListLocationSources,
  executeMapRender,
  executeMapsGeocode,
  executeMapsOptimizeStops,
  executeMapsPlaces,
  executeMapsReverseGeocode,
  executeMapsSetLocationSource,
  executeMapsStatus,
  MAPS_CURRENT_LOCATION_TOOL_ID,
  MAPS_DIRECTIONS_TOOL_ID,
  MAPS_LIST_LOCATION_SOURCES_TOOL_ID,
  MAP_RENDER_TOOL_ID,
  MAPS_GEOCODE_TOOL_ID,
  MAPS_OPTIMIZE_STOPS_TOOL_ID,
  MAPS_PLACES_TOOL_ID,
  MAPS_REVERSE_GEOCODE_TOOL_ID,
  MAPS_SET_LOCATION_SOURCE_TOOL_ID,
  MAPS_STATUS_TOOL_ID,
} from "../maps"
import {
  executeWeatherSetCalendarContext,
  executeWeatherSetOutfit,
  executeWeatherSetWhy,
  executeWeatherShow,
  executeWeatherStatus,
  WEATHER_SET_CALENDAR_CONTEXT_TOOL_ID,
  WEATHER_SET_OUTFIT_TOOL_ID,
  WEATHER_SET_WHY_TOOL_ID,
  WEATHER_SHOW_TOOL_ID,
  WEATHER_STATUS_TOOL_ID,
} from "../weather"
import {
  executeGetBodyMetrics,
  executeGetExerciseHistory,
  executeGetRecentWorkouts,
  executeListExerciseHistory,
  executeSaveBodyMetrics,
  GET_BODY_METRICS_TOOL_ID,
  GET_EXERCISE_HISTORY_TOOL_ID,
  GET_RECENT_WORKOUTS_TOOL_ID,
  LIST_EXERCISE_HISTORY_TOOL_ID,
  SAVE_BODY_METRICS_TOOL_ID,
} from "../workout-history"
import { executePatchWorkout, PATCH_WORKOUT_TOOL_ID } from "../workout-patch"
import {
  executeAppDataGet,
  executeAppDataSet,
  executeAppDelete,
  executeAppGet,
  executeAppSave,
  executeAppShow,
  executeAppsList,
  APP_DATA_GET_TOOL_ID,
  APP_DATA_SET_TOOL_ID,
  APP_DELETE_TOOL_ID,
  APP_GET_TOOL_ID,
  APP_SAVE_TOOL_ID,
  APP_SHOW_TOOL_ID,
  APPS_LIST_TOOL_ID,
} from "../apps"
import { executeMonitorWakeFeedback } from "../smart-monitor-feedback"
import {
  executeMonitorDescribeSources,
  executeMonitorWatchAdd,
  executeMonitorWatchGet,
  executeMonitorWatchList,
  executeMonitorWatchRemove,
  executeMonitorWatchUpdate,
} from "../smart-monitor-manage"
import {
  executeWatchlistAddFinancialInstrument,
  executeWatchlistAddProduct,
  executeWatchlistListItems,
  executeWatchlistRecordProductPrice,
  executeWatchlistRemoveItem,
} from "../watchlist"
import {
  executeMicroscriptCreate,
  executeMicroscriptDelete,
  executeMicroscriptDescribeCapabilities,
  executeMicroscriptGet,
  executeMicroscriptGetRun,
  executeMicroscriptList,
  executeMicroscriptPause,
  executeMicroscriptResume,
  executeMicroscriptRunNow,
  executeMicroscriptUpdate,
} from "../microscripts"
import {
  executeWebhookCreate,
  executeWebhookDelete,
  executeWebhookDescribeCapabilities,
  executeWebhookList,
  executeWebhookSubscriptionCreate,
  executeWebhookUpdate,
} from "../webhooks"
import {
  executeRemoteAccessStatus,
  executeRemoteAccessEnableWebhookFunnel,
  executeRemoteAccessDisableWebhookFunnel,
  executeRemoteAccessInstallTailscale,
  executeRemoteAccessSetupHttps,
} from "../remote-access"
import type { ToolExecutor } from "./types"

export const automationToolExecutors: Record<string, ToolExecutor> = {
  schedule_task: executeScheduleTask,
  list_tasks: executeListTasks,
  cancel_task: executeCancelTask,
  reschedule_task: executeRescheduleTask,
  search_past_runs: executeSearchPastRuns,
  get_past_run: executeGetPastRun,
  search_agent_logs: executeSearchAgentLogs,
  get_agent_log: executeGetAgentLog,
  read_runtime_index: executeReadRuntimeIndex,
  notify_inbox: executeNotifyInbox,
  inbox_action_history: executeInboxActionHistory,
  set_task_state: executeSetTaskState,
  [MAP_RENDER_TOOL_ID]: executeMapRender,
  [MAPS_STATUS_TOOL_ID]: executeMapsStatus,
  [MAPS_CURRENT_LOCATION_TOOL_ID]: executeMapsCurrentLocation,
  [MAPS_LIST_LOCATION_SOURCES_TOOL_ID]: executeMapsListLocationSources,
  [MAPS_SET_LOCATION_SOURCE_TOOL_ID]: executeMapsSetLocationSource,
  [MAPS_GEOCODE_TOOL_ID]: executeMapsGeocode,
  [MAPS_REVERSE_GEOCODE_TOOL_ID]: executeMapsReverseGeocode,
  [MAPS_PLACES_TOOL_ID]: executeMapsPlaces,
  [MAPS_OPTIMIZE_STOPS_TOOL_ID]: executeMapsOptimizeStops,
  [MAPS_DIRECTIONS_TOOL_ID]: executeMapsDirections,
  [WEATHER_SHOW_TOOL_ID]: executeWeatherShow,
  [WEATHER_SET_OUTFIT_TOOL_ID]: executeWeatherSetOutfit,
  [WEATHER_SET_WHY_TOOL_ID]: executeWeatherSetWhy,
  [WEATHER_SET_CALENDAR_CONTEXT_TOOL_ID]: executeWeatherSetCalendarContext,
  [WEATHER_STATUS_TOOL_ID]: executeWeatherStatus,
  [GET_EXERCISE_HISTORY_TOOL_ID]: executeGetExerciseHistory,
  [LIST_EXERCISE_HISTORY_TOOL_ID]: executeListExerciseHistory,
  [GET_RECENT_WORKOUTS_TOOL_ID]: executeGetRecentWorkouts,
  [GET_BODY_METRICS_TOOL_ID]: executeGetBodyMetrics,
  [SAVE_BODY_METRICS_TOOL_ID]: executeSaveBodyMetrics,
  [PATCH_WORKOUT_TOOL_ID]: executePatchWorkout,
  [APPS_LIST_TOOL_ID]: executeAppsList,
  [APP_GET_TOOL_ID]: executeAppGet,
  [APP_SAVE_TOOL_ID]: executeAppSave,
  [APP_DELETE_TOOL_ID]: executeAppDelete,
  [APP_DATA_GET_TOOL_ID]: executeAppDataGet,
  [APP_DATA_SET_TOOL_ID]: executeAppDataSet,
  [APP_SHOW_TOOL_ID]: executeAppShow,
  apply_update: executeApplyUpdate,
  memory_search: executeMemorySearch,
  memory_recent_activity: executeMemoryRecentActivity,
  library_search: executeLibrarySearch,
  WatchlistAddFinancialInstrument: executeWatchlistAddFinancialInstrument,
  WatchlistAddProduct: executeWatchlistAddProduct,
  WatchlistRemoveItem: executeWatchlistRemoveItem,
  WatchlistListItems: executeWatchlistListItems,
  WatchlistRecordProductPrice: executeWatchlistRecordProductPrice,
  monitor_wake_feedback: executeMonitorWakeFeedback,
  monitor_describe_sources: executeMonitorDescribeSources,
  monitor_watch_list: executeMonitorWatchList,
  monitor_watch_get: executeMonitorWatchGet,
  monitor_watch_add: executeMonitorWatchAdd,
  monitor_watch_update: executeMonitorWatchUpdate,
  monitor_watch_remove: executeMonitorWatchRemove,
  microscript_describe_capabilities: executeMicroscriptDescribeCapabilities,
  microscript_create: executeMicroscriptCreate,
  microscript_list: executeMicroscriptList,
  microscript_get: executeMicroscriptGet,
  microscript_update: executeMicroscriptUpdate,
  microscript_pause: executeMicroscriptPause,
  microscript_resume: executeMicroscriptResume,
  microscript_delete: executeMicroscriptDelete,
  microscript_run_now: executeMicroscriptRunNow,
  microscript_get_run: executeMicroscriptGetRun,
  webhook_describe_capabilities: executeWebhookDescribeCapabilities,
  webhook_list: executeWebhookList,
  webhook_create: executeWebhookCreate,
  webhook_update: executeWebhookUpdate,
  webhook_delete: executeWebhookDelete,
  webhook_subscription_create: executeWebhookSubscriptionCreate,
  remote_access_status: executeRemoteAccessStatus,
  remote_access_enable_webhook_funnel: executeRemoteAccessEnableWebhookFunnel,
  remote_access_disable_webhook_funnel: executeRemoteAccessDisableWebhookFunnel,
  remote_access_install_tailscale: executeRemoteAccessInstallTailscale,
  remote_access_setup_https: executeRemoteAccessSetupHttps,
}
