import {
  executeGmailArchive,
  executeGmailCreateDraft,
  executeGmailCreateLabel,
  executeGmailDeletePermanently,
  executeGmailDownloadAttachment,
  executeGmailListLabels,
  executeGmailMarkRead,
  executeGmailMarkUnread,
  executeGmailModifyLabels,
  executeGmailReadThread,
  executeGmailSearch,
  executeGmailSendDraft,
  executeGmailSendEmail,
  executeGmailTrash,
  executeGmailUntrash,
  executeGmailUnsubscribe,
  executeGmailUnsubscribeInfo,
} from "../gmail"
import {
  executeWhatsAppConnect,
  executeWhatsAppDeleteMessageForEveryone,
  executeWhatsAppDownloadMedia,
  executeWhatsAppListChats,
  executeWhatsAppMarkChatRead,
  executeWhatsAppMarkChatUnread,
  executeWhatsAppReadChat,
  executeWhatsAppSearchMessages,
  executeWhatsAppSendMedia,
  executeWhatsAppSendMessage,
  executeWhatsAppStatus,
  executeWhatsAppUnreadSummary,
} from "../whatsapp"
import type { ToolExecutor } from "./types"

export const communicationToolExecutors: Record<string, ToolExecutor> = {
  GmailSearch: executeGmailSearch,
  GmailReadThread: executeGmailReadThread,
  GmailCreateDraft: executeGmailCreateDraft,
  GmailSendDraft: executeGmailSendDraft,
  GmailSendEmail: executeGmailSendEmail,
  GmailModifyLabels: executeGmailModifyLabels,
  GmailArchive: executeGmailArchive,
  GmailMarkRead: executeGmailMarkRead,
  GmailMarkUnread: executeGmailMarkUnread,
  GmailTrash: executeGmailTrash,
  GmailUntrash: executeGmailUntrash,
  GmailDeletePermanently: executeGmailDeletePermanently,
  GmailUnsubscribeInfo: executeGmailUnsubscribeInfo,
  GmailUnsubscribe: executeGmailUnsubscribe,
  GmailListLabels: executeGmailListLabels,
  GmailCreateLabel: executeGmailCreateLabel,
  GmailDownloadAttachment: executeGmailDownloadAttachment,
  WhatsAppStatus: executeWhatsAppStatus,
  WhatsAppConnect: executeWhatsAppConnect,
  WhatsAppListChats: executeWhatsAppListChats,
  WhatsAppUnreadSummary: executeWhatsAppUnreadSummary,
  WhatsAppReadChat: executeWhatsAppReadChat,
  WhatsAppSearchMessages: executeWhatsAppSearchMessages,
  WhatsAppDownloadMedia: executeWhatsAppDownloadMedia,
  WhatsAppSendMessage: executeWhatsAppSendMessage,
  WhatsAppSendMedia: executeWhatsAppSendMedia,
  WhatsAppDeleteMessageForEveryone: executeWhatsAppDeleteMessageForEveryone,
  WhatsAppMarkChatRead: executeWhatsAppMarkChatRead,
  WhatsAppMarkChatUnread: executeWhatsAppMarkChatUnread,
}
