import {
  executeGoogleCalendarConfigure,
  executeGoogleCalendarCreateEvent,
  executeGoogleCalendarDeleteEvent,
  executeGoogleCalendarFindAvailability,
  executeGoogleCalendarFreeBusy,
  executeGoogleCalendarGetEvent,
  executeGoogleCalendarListCalendars,
  executeGoogleCalendarListEvents,
  executeGoogleCalendarMoveEvent,
  executeGoogleCalendarRespondToEvent,
  executeGoogleCalendarSearchEvents,
  executeGoogleCalendarStartOAuth,
  executeGoogleCalendarStatus,
  executeGoogleCalendarUpdateEvent,
} from "../google-calendar"
import {
  executeGoogleContactsBatchCreateContacts,
  executeGoogleContactsBatchDeleteContacts,
  executeGoogleContactsBatchGetPeople,
  executeGoogleContactsBatchUpdateContacts,
  executeGoogleContactsCopyOtherContactToMyContacts,
  executeGoogleContactsCreateContact,
  executeGoogleContactsCreateContactGroup,
  executeGoogleContactsDeleteContact,
  executeGoogleContactsDeleteContactGroup,
  executeGoogleContactsGetContactGroup,
  executeGoogleContactsGetPerson,
  executeGoogleContactsListConnections,
  executeGoogleContactsListContactGroups,
  executeGoogleContactsListOtherContacts,
  executeGoogleContactsModifyContactGroupMembers,
  executeGoogleContactsSearchContacts,
  executeGoogleContactsSearchOtherContacts,
  executeGoogleContactsUpdateContact,
  executeGoogleContactsUpdateContactGroup,
} from "../google-contacts"
import {
  executeGoogleDocsApplyParagraphStyle,
  executeGoogleDocsApplyTextStyle,
  executeGoogleDocsBatchUpdate,
  executeGoogleDocsCreateDocument,
  executeGoogleDocsGetDocument,
  executeGoogleDocsInsertTable,
  executeGoogleDocsInsertText,
  executeGoogleDocsReplaceAllText,
} from "../google-docs"
import {
  executeGoogleDriveAbout,
  executeGoogleDriveConfigure,
  executeGoogleDriveCopyFile,
  executeGoogleDriveCreateFolder,
  executeGoogleDriveCreateGoogleFile,
  executeGoogleDriveDeleteFile,
  executeGoogleDriveDeletePermission,
  executeGoogleDriveDownloadFile,
  executeGoogleDriveExportFile,
  executeGoogleDriveGetFile,
  executeGoogleDriveListFiles,
  executeGoogleDriveListPermissions,
  executeGoogleDriveListSharedDrives,
  executeGoogleDriveMoveFile,
  executeGoogleDriveReadFile,
  executeGoogleDriveShareFile,
  executeGoogleDriveStartOAuth,
  executeGoogleDriveStatus,
  executeGoogleDriveTrashFile,
  executeGoogleDriveUntrashFile,
  executeGoogleDriveUpdateFileContent,
  executeGoogleDriveUpdateMetadata,
  executeGoogleDriveUpdatePermission,
  executeGoogleDriveUploadFile,
} from "../google-drive"
import {
  executeGoogleSheetsAppendValues,
  executeGoogleSheetsBatchGetValues,
  executeGoogleSheetsBatchUpdate,
  executeGoogleSheetsClearValues,
  executeGoogleSheetsCreateSpreadsheet,
  executeGoogleSheetsGetSpreadsheet,
  executeGoogleSheetsGetValues,
  executeGoogleSheetsUpdateValues,
} from "../google-sheets"
import {
  executeGoogleSlidesBatchUpdate,
  executeGoogleSlidesCreatePresentation,
  executeGoogleSlidesCreateSlide,
  executeGoogleSlidesGetPage,
  executeGoogleSlidesGetPresentation,
  executeGoogleSlidesGetThumbnail,
  executeGoogleSlidesInsertTextBox,
  executeGoogleSlidesReplaceAllText,
} from "../google-slides"
import type { ToolExecutor } from "./types"

export const googleWorkspaceToolExecutors: Record<string, ToolExecutor> = {
  GoogleCalendarStatus: executeGoogleCalendarStatus,
  GoogleCalendarConfigure: executeGoogleCalendarConfigure,
  GoogleCalendarStartOAuth: executeGoogleCalendarStartOAuth,
  GoogleCalendarListCalendars: executeGoogleCalendarListCalendars,
  GoogleCalendarListEvents: executeGoogleCalendarListEvents,
  GoogleCalendarGetEvent: executeGoogleCalendarGetEvent,
  GoogleCalendarSearchEvents: executeGoogleCalendarSearchEvents,
  GoogleCalendarFreeBusy: executeGoogleCalendarFreeBusy,
  GoogleCalendarFindAvailability: executeGoogleCalendarFindAvailability,
  GoogleCalendarCreateEvent: executeGoogleCalendarCreateEvent,
  GoogleCalendarUpdateEvent: executeGoogleCalendarUpdateEvent,
  GoogleCalendarDeleteEvent: executeGoogleCalendarDeleteEvent,
  GoogleCalendarRespondToEvent: executeGoogleCalendarRespondToEvent,
  GoogleCalendarMoveEvent: executeGoogleCalendarMoveEvent,
  GoogleContactsListConnections: executeGoogleContactsListConnections,
  GoogleContactsSearchContacts: executeGoogleContactsSearchContacts,
  GoogleContactsGetPerson: executeGoogleContactsGetPerson,
  GoogleContactsBatchGetPeople: executeGoogleContactsBatchGetPeople,
  GoogleContactsCreateContact: executeGoogleContactsCreateContact,
  GoogleContactsBatchCreateContacts: executeGoogleContactsBatchCreateContacts,
  GoogleContactsUpdateContact: executeGoogleContactsUpdateContact,
  GoogleContactsBatchUpdateContacts: executeGoogleContactsBatchUpdateContacts,
  GoogleContactsDeleteContact: executeGoogleContactsDeleteContact,
  GoogleContactsBatchDeleteContacts: executeGoogleContactsBatchDeleteContacts,
  GoogleContactsListContactGroups: executeGoogleContactsListContactGroups,
  GoogleContactsGetContactGroup: executeGoogleContactsGetContactGroup,
  GoogleContactsCreateContactGroup: executeGoogleContactsCreateContactGroup,
  GoogleContactsUpdateContactGroup: executeGoogleContactsUpdateContactGroup,
  GoogleContactsDeleteContactGroup: executeGoogleContactsDeleteContactGroup,
  GoogleContactsModifyContactGroupMembers:
    executeGoogleContactsModifyContactGroupMembers,
  GoogleContactsListOtherContacts: executeGoogleContactsListOtherContacts,
  GoogleContactsSearchOtherContacts: executeGoogleContactsSearchOtherContacts,
  GoogleContactsCopyOtherContactToMyContacts:
    executeGoogleContactsCopyOtherContactToMyContacts,
  GoogleDriveStatus: executeGoogleDriveStatus,
  GoogleDriveConfigure: executeGoogleDriveConfigure,
  GoogleDriveStartOAuth: executeGoogleDriveStartOAuth,
  GoogleDriveAbout: executeGoogleDriveAbout,
  GoogleDriveListSharedDrives: executeGoogleDriveListSharedDrives,
  GoogleDriveListFiles: executeGoogleDriveListFiles,
  GoogleDriveGetFile: executeGoogleDriveGetFile,
  GoogleDriveReadFile: executeGoogleDriveReadFile,
  GoogleDriveDownloadFile: executeGoogleDriveDownloadFile,
  GoogleDriveExportFile: executeGoogleDriveExportFile,
  GoogleDriveUploadFile: executeGoogleDriveUploadFile,
  GoogleDriveUpdateFileContent: executeGoogleDriveUpdateFileContent,
  GoogleDriveCreateFolder: executeGoogleDriveCreateFolder,
  GoogleDriveCreateGoogleFile: executeGoogleDriveCreateGoogleFile,
  GoogleDriveUpdateMetadata: executeGoogleDriveUpdateMetadata,
  GoogleDriveMoveFile: executeGoogleDriveMoveFile,
  GoogleDriveCopyFile: executeGoogleDriveCopyFile,
  GoogleDriveTrashFile: executeGoogleDriveTrashFile,
  GoogleDriveUntrashFile: executeGoogleDriveUntrashFile,
  GoogleDriveDeleteFile: executeGoogleDriveDeleteFile,
  GoogleDriveListPermissions: executeGoogleDriveListPermissions,
  GoogleDriveShareFile: executeGoogleDriveShareFile,
  GoogleDriveUpdatePermission: executeGoogleDriveUpdatePermission,
  GoogleDriveDeletePermission: executeGoogleDriveDeletePermission,
  GoogleDocsCreateDocument: executeGoogleDocsCreateDocument,
  GoogleDocsGetDocument: executeGoogleDocsGetDocument,
  GoogleDocsInsertText: executeGoogleDocsInsertText,
  GoogleDocsReplaceAllText: executeGoogleDocsReplaceAllText,
  GoogleDocsApplyTextStyle: executeGoogleDocsApplyTextStyle,
  GoogleDocsApplyParagraphStyle: executeGoogleDocsApplyParagraphStyle,
  GoogleDocsInsertTable: executeGoogleDocsInsertTable,
  GoogleDocsBatchUpdate: executeGoogleDocsBatchUpdate,
  GoogleSheetsCreateSpreadsheet: executeGoogleSheetsCreateSpreadsheet,
  GoogleSheetsGetSpreadsheet: executeGoogleSheetsGetSpreadsheet,
  GoogleSheetsGetValues: executeGoogleSheetsGetValues,
  GoogleSheetsBatchGetValues: executeGoogleSheetsBatchGetValues,
  GoogleSheetsUpdateValues: executeGoogleSheetsUpdateValues,
  GoogleSheetsAppendValues: executeGoogleSheetsAppendValues,
  GoogleSheetsClearValues: executeGoogleSheetsClearValues,
  GoogleSheetsBatchUpdate: executeGoogleSheetsBatchUpdate,
  GoogleSlidesCreatePresentation: executeGoogleSlidesCreatePresentation,
  GoogleSlidesGetPresentation: executeGoogleSlidesGetPresentation,
  GoogleSlidesGetPage: executeGoogleSlidesGetPage,
  GoogleSlidesGetThumbnail: executeGoogleSlidesGetThumbnail,
  GoogleSlidesCreateSlide: executeGoogleSlidesCreateSlide,
  GoogleSlidesInsertTextBox: executeGoogleSlidesInsertTextBox,
  GoogleSlidesReplaceAllText: executeGoogleSlidesReplaceAllText,
  GoogleSlidesBatchUpdate: executeGoogleSlidesBatchUpdate,
}
