import {
  executeHomeAssistantApiInfo,
  executeHomeAssistantAutomationActivity,
  executeHomeAssistantCallService,
  executeHomeAssistantCameraSnapshot,
  executeHomeAssistantCheckConfig,
  executeHomeAssistantConfigure,
  executeHomeAssistantErrorLog,
  executeHomeAssistantGetConfig,
  executeHomeAssistantGetState,
  executeHomeAssistantHistory,
  executeHomeAssistantListAutomations,
  executeHomeAssistantListAutomationConfigs,
  executeHomeAssistantListCalendars,
  executeHomeAssistantListEvents,
  executeHomeAssistantListRegistries,
  executeHomeAssistantListScenes,
  executeHomeAssistantListScripts,
  executeHomeAssistantListServices,
  executeHomeAssistantListStates,
  executeHomeAssistantLogbook,
  executeHomeAssistantNotify,
  executeHomeAssistantPreviewAction,
  executeHomeAssistantReadActionAudit,
  executeHomeAssistantReadAutomationConfig,
  executeHomeAssistantReadCalendar,
  executeHomeAssistantRenderTemplate,
  executeHomeAssistantSearchEntities,
  executeHomeAssistantSetClimate,
  executeHomeAssistantSetCover,
  executeHomeAssistantSetLight,
  executeHomeAssistantStatus,
  executeHomeAssistantWebSocketRead,
} from "../home-assistant"
import type { ToolExecutor } from "./types"

export const homeAssistantToolExecutors: Record<string, ToolExecutor> = {
  HomeAssistantStatus: executeHomeAssistantStatus,
  HomeAssistantConfigure: executeHomeAssistantConfigure,
  HomeAssistantApiInfo: executeHomeAssistantApiInfo,
  HomeAssistantGetConfig: executeHomeAssistantGetConfig,
  HomeAssistantListStates: executeHomeAssistantListStates,
  HomeAssistantGetState: executeHomeAssistantGetState,
  HomeAssistantSearchEntities: executeHomeAssistantSearchEntities,
  HomeAssistantListServices: executeHomeAssistantListServices,
  HomeAssistantListEvents: executeHomeAssistantListEvents,
  HomeAssistantHistory: executeHomeAssistantHistory,
  HomeAssistantLogbook: executeHomeAssistantLogbook,
  HomeAssistantErrorLog: executeHomeAssistantErrorLog,
  HomeAssistantListCalendars: executeHomeAssistantListCalendars,
  HomeAssistantReadCalendar: executeHomeAssistantReadCalendar,
  HomeAssistantCameraSnapshot: executeHomeAssistantCameraSnapshot,
  HomeAssistantRenderTemplate: executeHomeAssistantRenderTemplate,
  HomeAssistantCheckConfig: executeHomeAssistantCheckConfig,
  HomeAssistantWebSocketRead: executeHomeAssistantWebSocketRead,
  HomeAssistantListRegistries: executeHomeAssistantListRegistries,
  HomeAssistantListAutomations: executeHomeAssistantListAutomations,
  HomeAssistantListScripts: executeHomeAssistantListScripts,
  HomeAssistantListScenes: executeHomeAssistantListScenes,
  HomeAssistantAutomationActivity: executeHomeAssistantAutomationActivity,
  HomeAssistantReadAutomationConfig: executeHomeAssistantReadAutomationConfig,
  HomeAssistantListAutomationConfigs: executeHomeAssistantListAutomationConfigs,
  HomeAssistantPreviewAction: executeHomeAssistantPreviewAction,
  HomeAssistantCallService: executeHomeAssistantCallService,
  HomeAssistantSetLight: executeHomeAssistantSetLight,
  HomeAssistantSetCover: executeHomeAssistantSetCover,
  HomeAssistantSetClimate: executeHomeAssistantSetClimate,
  HomeAssistantNotify: executeHomeAssistantNotify,
  HomeAssistantReadActionAudit: executeHomeAssistantReadActionAudit,
}
