// App & host guide doctrine — the orchestrator's self-knowledge about the
// Orchestrator product: every page and Settings tab, where each capability
// lives, how data management (backup / restore / factory reset) works, the
// feature mechanics a user actually asks about, and how to read the live host
// snapshot. Loaded lazily into the prompt only after
// ActivateIntegrationTools('app_guide') (see lib/integrations/subsystem-manifest.ts).
//
// MAINTENANCE: this is hand-written documentation of the UI/product AND of the
// background machinery (<under_the_hood>). Keeping it current is a dev RULE, not a
// nicety — see "Keep The App Guide In Sync" in AGENTS.md: any change that adds or
// alters a user-facing surface, capability, data-management behavior, or the
// background machinery below must update this file in the same change and run
// `npm run smoke:app-guide`. Keep it user-facing and accurate; it answers "what can
// this app do / where do I do X / how does Y work / what's running", not internal
// code architecture. Grounded in the codebase as of this writing — verify a
// specific path/flag with the live UI or code if a user disputes it rather than
// insisting from here.
export const APP_GUIDE_DOCTRINE = `
<app_guide>
Authoritative reference for answering the user's questions ABOUT Orchestrator itself — what it can do, where a feature lives, how a surface behaves, and how its data-management controls work. The user owns and administers this instance; you are their operating layer inside it. Be concrete: name the page or the exact Settings tab → section. Don't invent UI that isn't described here. Many things in here you can also DO for the user (edit memory/behavior files, set up integrations, create a backup, manage watches/tasks); a few are deliberately user-only (restore, factory reset) — say so plainly. If a user disputes a detail, trust the live app over this text and check rather than insisting.

<product_model>
- Orchestrator is a personal, local-first AI operating layer: one chat-driven agent (you) that does work directly and delegates the rest to specialist sub-agents, with persistent memory, integrations, schedules, and monitors.
- Local-first and profile-scoped: OAuth tokens, WhatsApp/browser sessions, .env secrets, SQLite data, uploads, artifacts, browser-agent state, CLI runtime homes, and memory live on disk on the machine the app runs on. Each profile has its own isolated workspace/private state; the built-in admin profile is Horia. Disconnect / factory-reset language is always "removed locally", not "revoked at the provider".
- Surfacing is silent by default across schedules and monitors: routine runs are logged but only reach the current profile's Inbox (and that profile's active push subscriptions) when the agent decides something is worth the user's attention, or on error.
- The agent that powers chat is the "orchestrator"; some surfaces run alias agents on the same brain so the user can route them to a different/cheaper model in Settings → Models (e.g. the Inbox agent, the Smart Monitor wake agent, the Conversation Namer).
</product_model>

<profiles>
- Profile picker: a device with no selected profile opens "/profiles" before the app. It shows Netflix-style profile tiles plus an Add profile tile. Profiles have no password by default; locked profiles ask for the profile password.
- Sidebar profile menu: the sidebar footer shows the active profile. Clicking it opens Switch profile and Sign out. Switching returns to the profile picker; signing out clears only that device's profile session.
- Admin vs member: Horia/admin sees Settings, Logs, Usage, Updates, model/config controls, profile management, and app-wide data management. Member profiles do not see Settings and direct Settings/admin API calls return 403.
- Isolation: each profile gets its own conversations, inbox, schedules, monitors, watchlist, maps/places, uploads, artifacts, memory files, .env.local, integration tokens, WhatsApp session, browser-agent Patchright profile, Codex runtime home, and browser downloads. The profile permission matrix can allow a member to use an integration/tool, but it does not merge their workspace with Horia's.
</profiles>

<navigation>
Left sidebar (collapsible to an icon rail). Pages, top to bottom:
- Chat ("/") — the main conversation surface. New chat button; Search (also Cmd/Ctrl-K) is accent-insensitive (matches Romanian text without diacritics) and searches titles + message contents both client-side and server-side. Conversation list shows "Recents" (non-archived); a hover/again-tap Archive toggle flips to the "Archive" view.
- Inbox ("/inbox") — results/notifications from scheduled tasks and monitors. The sidebar item carries a dark-red unread badge (count, or "99+").
- Library ("/library") — everything generated or attached, in tabs.
- Watchlist ("/watchlist") — track financial instruments and products.
- Scheduling ("/scheduling") — create and manage scheduled tasks.
- Smart Monitor ("/monitor") — ongoing, model-owned monitoring.
- Smart Maps ("/maps") — full-screen interactive map.
- Settings ("/settings") — all configuration (footer, admin profiles only).

Conversation management (sidebar):
- Auto-naming: a new chat gets a placeholder, then after the first exchange the Conversation Namer agent names it in the user's language (≤~30 chars). It never overwrites a title the user changed manually.
- Archive / Restore / Delete: normal rows can be Archived (hover button on desktop; long-press ~0.5s or right-click on mobile). The Archive view exposes Restore and Delete per row. There is no delete in Recents — archive first, then delete from the Archive view.
- Unread: a conversation is marked unread when an assistant reply finishes while the user isn't looking at it (different page, hidden tab, or a different active conversation). Opening it clears the unread state.
- Drafts and per-conversation artifact-panel widths persist locally.
</navigation>

<chat_surface>
Input (the composer):
- Text: Enter sends, Shift+Enter is a newline (on a mobile keyboard Enter inserts a newline — use the send button). Markdown list markers ("1.", "-", "A.") get a tab-style gap before the item text; Shift+Enter inside a markdown list auto-continues the next bullet/number/letter, and on an empty list item it ends the list (Word-style).
- Attachments: the "+" button, drag-and-drop, or paste. Multiple files. They upload immediately; sending is blocked until every attachment finishes uploading. Click an attachment chip to preview it in-app: a full PDF viewer, image/video lightbox, Excel/CSV as a scrollable multi-sheet grid (cell formatting, column widths, merged cells), PowerPoint as rendered slides, Word (.docx), source/text files syntax-highlighted with line numbers, and SVG rendered as a sanitized image (with a source toggle). Audio plays inline. Anything not previewable keeps a Download fallback.
- Voice: the Mic button records a voice note. It is uploaded and sent as an AUDIO ATTACHMENT (not transcribed in the browser). A pure voice-note message (no typed text) may get the server audio pre-pass before the main model when needed; if the user also typed text, the whole text+audio message goes straight to the orchestrator to decide what to do. Voice notes land in Library → Audio.
- Drafts persist per conversation.

Messages and what the user sees:
- Assistant replies interleave "Thinking" reasoning blocks and prose. The Thinking block is collapsible (expand/collapse persists per message), shows a live "Thinking (Ns)" timer while streaming, and contains the agent's reasoning and tool calls (web searches are grouped). It auto-expands when there are notable tool calls and stays open while a live browser-agent run is in progress.
- Sub-agent calls render as agent cards rather than raw delegate tool output. Each card shows status, tool count, output size, and whether the full transcript is saved in the persistent agent thread; opening the card shows the full prompt/output/reasoning pane with a Copy-full-output control. When that agent has several sub-agents, their chips switch the nested preview in place instead of replacing the main agent pane. If a live/tool preview looks clipped, the persisted agent thread remains the source of truth.
- Files the agent produces show up in the message itself, not only as text. A generated image referenced inline (Markdown \`![](…)\`, including by its workspace path) renders as an actual image, click-to-zoom. A link to a workspace file (PDF, Office, code/text, 3D model, image) renders as a compact file card that opens the SAME in-app viewer used for attachment chips — PowerPoint decks convert to slides server-side on open. Workspace HTML links under \`files/\` open in the chat side panel as a mini-browser preview; if a response links several HTML files, they appear as closeable browser-style tabs and auto-open for newly generated assistant responses. Files with no in-app viewer (archives, etc.) stay a one-click download link.
- Hover a message for the timestamp and a Copy button.

Artifacts (rich, self-contained outputs the agent emits). Each renders inline, in a resizable side panel ("Open artifact"), or full-screen ("/artifact/[id]") depending on the agent's display choice. The panel offers a Preview⇄Code toggle, a version dropdown (history of that artifact), Copy, Download, Open-in-new-tab, and Fullscreen. Types:
- text/markdown, application/vnd.ant.code (highlighted source), text/html (sandboxed live page), application/vnd.ant.react (live React component), application/vnd.ant.mermaid (diagram), image/svg+xml, text/csv (table), application/json, application/x-latex.
- application/vnd.ant.map — interactive Google map (pins/routes/areas, multi-day trip tabs); "Open in Smart Maps".
- application/vnd.ant.weather — iOS-style weather card (current, 24h scroll, 10-day, UV/wind/sunrise tiles).
- application/vnd.ant.recipe — recipe card with an interactive servings stepper that live-scales ingredient quantities; lands in Library → Recipes.
- application/vnd.ant.workout — interactive workout session. Start appears near the top of the workout; once active, Finish/Discard appear at the bottom of the workout content instead of as a sticky session band. After Start, the user can tap any pending set in any order; the highlighted row is just the next unfinished suggestion. The working-set timer appears in the bottom bar; Finish stops it and opens a compact editor for actual weight/reps/duration/RPE/notes; Save logs the set, starts the rest timer with chimes, and autosaves progress. During rest, the bottom rest bar can start the next set for that same exercise when one remains, otherwise the next unfinished set in workout order, closing the rest event cleanly. Individual sets can be skipped from the row menu; if the user taps Finish workout before completing everything, the remaining sets are confirmed and marked skipped with an optional reason. During an active workout the user can add extra sets or add a new weighted/bodyweight exercise from a dialog with full muscle-group coverage including back/pull groups; added exercises scroll into view, join progress, next-set order, summary, and saved history. Set notes open in a custom workout dialog rather than a browser prompt. Completed/failed/skipped sets remain editable after Finish workout, and changed actuals/RPE/notes re-save the finished session. The renderer records set timer duration and rest timer events so later workout-history tools can coach from real timing, not only reps/weight/RPE. The exercise info button expands an inline panel with longer description, alternatives, video, relevant term explanations, and an ExerciseDB OSS demo GIF resolved automatically from the exercise id/name; when no confident GIF match exists it falls back to the built-in exercise-photo library, then a keyless web image lookup. In-progress sessions autosave to the server keyed by the current artifact and are copied forward when the same sessionId workout is re-emitted, so a started session resumes after a reload, an inbox re-open, or on another device — not just in the same browser. The full-screen workout surface also has an in-surface AI coach — a docked lateral chat on desktop and a full-screen coach on mobile opened from the floating Coach button. When the workout/map was generated in main chat, the side chat loads that source conversation; inbox, system, handoff, or manually opened surfaces start with a blank new side chat instead. The user can ask it to adjust the session live (swap an exercise, make it harder, add a finisher) or attach a photo (a machine, a form check); when it edits, it updates the workout in place (a targeted patch, or a full re-emit for big changes) so the plan updates live while logged progress is preserved. Finished sessions save a summary and land in Library → Workouts.
- application/vnd.ant.app-link — compact launch card for a registered internal app; always opens the app's current code version.
- application/vnd.ant.cad — interactive 3D CAD model viewer (orbit/zoom/pan, grid, wireframe, auto-rotate, size chip) backed by a GLB file the agent generated in the workspace, with download chips for STEP/STL/3MF/source. Produced by the bundled \`cad\` skill (build123d parametric modeling; the \`step-parts\` skill fetches real STEP models of named purchasable parts like servos and screws). The user can print the downloaded STL/3MF/STEP with their own slicer. Standalone .glb/.stl/.3mf files in chat or Library also open in the same 3D viewer.
- application/vnd.ant.dev-preview — a live "mini-browser" of a website the agent is building. When the agent builds a web app (a new Next.js/Vite site, or a self-development change) it runs the dev server on the host and reverse-proxies it through the app at \`/dev-preview/<run-id>/\`; this artifact embeds that live preview in an iframe (URL bar, reload, open-in-new-tab) and AUTO-OPENS the side panel so the user sees the site as it is built — no link to chase and no access to the host's localhost needed. Edits are picked up with the reload control (the proxy doesn't carry Next's HMR socket). The user can still open the same preview in a real browser tab.
Recipe/map/workout artifacts also appear automatically in the matching Library tab; everything else (markdown, code, HTML/React pages, SVG, CSV, JSON, diagrams) lands in Library → Artifacts.
Internal apps: the agent can build reusable mini-apps — any self-contained interactive tool (calculators, planners, trackers, generators, dashboards, configurators, games, …) — as html/react artifacts registered under a stable slug, with a persistent per-app JSON data store shared by the running app (window.AppHost bridge) and the agent's AppData tools — so the user can add data or request changes from any later conversation. Saved apps sit pinned at the top of Library → Artifacts.
The strict-schema types (map, weather, recipe, workout, cad) are validated before any surface stores them — live chat, scheduled runs, microscript notifications, and inline Inbox replies alike; if a body fails validation, the same generating/owning agent runtime gets the exact error and repairs the JSON in-place before the message is delivered, so the corrected card appears without the user having to ask for a redo (only a repair that still fails after retries surfaces an error notice). If a card briefly shows "could not be displayed" after reopening the app, the client refetches it automatically — that notice only sticks for content that genuinely failed validation.
</chat_surface>

<inbox_surface>
A mail-style client for scheduled-run results, monitor alerts, replies, and handoffs.
- What creates an item: the agent (a scheduled task or a monitor wake) calls the notify_inbox tool with a title, a user-facing markdown body, and optional quick-reply actions. Ordinary chat does NOT create Inbox items. Items are system-owned conversations kept separate from user chats.
- List: search; folder chips Inbox / Unread / Read / Scheduled (items tied to a scheduled task); grouped Today / Yesterday / Earlier. An item re-marks unread when a new reply arrives.
- Opening an item marks it read. Header actions: "Open in chat" forks the thread into a normal chat; Delete.
- Quick-reply action buttons under an assistant message: reply-type actions continue the thread inline (handled by the Inbox agent); "direct" actions run a whitelisted housekeeping tool server-side WITHOUT invoking a model (e.g. Gmail mark-read/archive, WhatsApp mark-read). A free-text composer (with attachments) replies inline too.
- Push notifications: an in-Inbox bell enables web push for the active profile. A browser/device endpoint belongs to one profile at a time; enabling it under a new profile removes that endpoint from other profiles so pushes do not cross profiles.
</inbox_surface>

<library_surface>
One hub for "everything you've generated or attached." Tabs and what fills each:
- Workouts / Recipes / Maps — populated automatically from the matching chat artifacts. The Workouts tab is a history dashboard built from saved sessions: a training calendar (a GitHub-style heatmap of training days over the last ~16 weeks plus a week-streak, this-week, and last-30-day count), progress cards (recent sessions, volume trend, PRs), a weekly muscle-balance breakdown (completed sets per muscle group over a 7- or 30-day window, counting each muscle a compound lift targets), a recent-session list where each row also surfaces average rest time and skipped-rest count, per-exercise PR/history trends, and a Body metrics card where the user can log height, weight, body fat %, and muscle % (percentages of bodyweight) and see a body-weight trend sparkline; IMC/BMI is calculated from the latest height+weight. Clicking an artifact opens the full interactive renderer ("/artifact/[id]" or "/maps/[id]").
- Artifacts — registered internal apps (pinned "Apps" section on top, with delete) plus the latest version of every other conversation artifact (markdown, code, HTML/React, SVG, CSV, JSON, diagrams), with search and per-type filter chips. Cards open "/artifact/[id]"; workout/recipe/map/weather types are excluded (they have their own homes).
- Media (images+videos) / Audio (voice notes, music) / Files (PDFs, Office docs, code, other) — populated from two sources: chat/inbox attachments AND files the agent writes into allowlisted workspace output dirs. A file appears in the Library only if it lives in one of: files/, browser-downloads/, gmail-attachments/, artifacts/ (or is an upload). Standard workspace files (USER.md, MEMORY.md, runbooks, config) are deliberately NOT listed here. Workspace files under files/ also have profile-gated direct links at /files/<path-inside-files>; HTML previews render inline there with scripts blocked, and chat auto-opens linked HTML files in a tabbed side-panel mini-browser for newly generated responses. Chat file cards and downloads use the /api/workspace/files endpoint. → This is why create_backup saves into files/: so the archive shows in Library → Files.
- Places — the optional Location Intelligence journal (Home Assistant location webhooks → a local daily journal). Off until the user opts in.
- Cross-tab actions on Media/Audio/Files: search, a selection mode for bulk Download / Share / Delete, a media lightbox, and "View in chat" to jump to the source message. In the Files tab, clicking a file name (or its Eye button) opens the same in-app viewer used in chat — PDFs, Excel/CSV, PowerPoint, Word, and code/text render in-app; the rest fall back to Open-in-new-tab / Download. Deleting removes the upload or the workspace file; standard workspace files can't be deleted here.
</library_surface>

<settings>
Eight tabs (Models, Auth, Files, Logs, Usage, Notifications, Profiles, Updates). The light/dark Theme toggle is in the Settings header, top-right. The active tab is remembered. Settings is admin-only; member profiles are redirected back to the main app.

<settings_profiles>
Admin profile and access management.
- Profiles list: create profiles, edit name/color/role/password, deactivate/restore non-admin profiles, permanently delete a deactivated profile only after typing its exact name, and inspect recent profile audit events (creation, sign-ins, permission changes, deletes). Deactivation blocks sign-in while preserving profile data for restore; permanent delete can also remove that profile's local workspace/private state.
- Access matrix: per profile, choose visible app surfaces, tool classes (web, read/write files, shell, delegation, skills, scheduling, monitoring, microscripts, backups, updates), integration access for external services (none/read/write/setup), and whether the profile may inherit selected admin API keys from the shared process/project environment. Watchlist is a local per-profile surface/subsystem, not an external integration. New member profiles default to the main personal workflow: chat/inbox/library/watchlist/Smart Monitor/maps/workouts plus Scheduling, file read/write, browser agent, delegation, web, memory, skills, monitoring, and microscripts are enabled; admin API-key inheritance is on so model calls use the configured provider keys; shell, backups, updates, models, and raw settings files stay off.
- Google account connections: Gmail, Google Calendar, and Google Workspace each support multiple locally stored OAuth account connections per profile. Settings → Auth shows the available accounts on each Google card and lets the active profile choose its default account for that service; connecting another Google account adds/updates that account instead of overwriting the first one. Legacy single-token installs are migrated into a connection on first status check without deleting the legacy token file.
- Home Assistant sharing: a member can either connect their own Home Assistant in Settings → Auth under their profile context, or admin can grant that member access to another profile's Home Assistant connection from Settings → Profiles. Grants are per connection and can be No access / Read / Read & write / Manage; each profile can choose which accessible connection is its default. Shared access never copies the long-lived token into the member profile — calls run against the owner profile's stored connection, policy, and audit files.
- Remote MCP servers: Settings → Auth → Remote MCP servers is profile-scoped. It stores remote Streamable HTTP MCP endpoint config and OAuth tokens locally in that profile's private state. The app supports browser OAuth for MCP servers and no-auth endpoints for trusted/local testing; it does not run arbitrary local stdio MCP server commands from Settings.
- Sharing model: profiles never share DB/workspace/browser state. Granting integration/API-key access only lets a profile use that capability inside its own workspace and with its own local tokens/config unless explicit key inheritance or an explicit shared connection grant is enabled.
- Logs/user visibility: Logs is admin-only and aggregates model request logs across profiles; rows show the profile that produced the request. The Profiles tab shows profile/session/permission audit events.
</settings_profiles>

<settings_models>
Per-agent model configuration plus the model registry and semantic-memory setup.
- For each agent: pick the Model, the Thinking level, model-specific Features, and up to two ordered Fallback models. Agents are listed in a reorderable sidebar (drag to reorder), with a separate pinned "System" group for agents that run automatically.
- Fallback models are tried automatically on provider availability failures such as rate limits, quota/capacity/overload, expired sessions, or 401/429/503-style errors, as long as the failed attempt has not already emitted assistant prose. If the model fails after tool activity but before a final answer, the next fallback still gets a chance; if visible answer text already streamed, the turn is kept as that provider's error instead of silently restarting.
- Thinking level is a PER-MODEL capability surfaced per-agent: Off / Low / Med / High / XHigh / Max, only shown for models that support adjustable thinking, and it auto-normalizes when you switch to a model that doesn't support the current level. It controls the reasoning effort/budget sent to the model — not a global toggle.
- Override resolution: per-agent override → that agent's default → the global default. The right panel labels which is active.
- Model picker: search across name/provider; Favorites (star, reorderable) at top; Archive/Unarchive per model (archived models hide from the picker but an explicit selection still runs). A Refresh button re-pulls each provider's model list.
- Top bar "Refresh models" auto-discovers new models from each configured provider. New models still need research to be "complete".
- "Model metadata" card: a collapsible section showing how many active models have complete vs incomplete metadata. "Review & research (N)" opens a review panel FIRST (it never auto-starts a run) — the left list shows every active model sorted incomplete-first with its missing fields, the right pane shows the selected model's current metadata; an explicit "Start research (N)" button then runs the researcher agent to fill pricing/context/thinking for the incomplete models from official docs (streamed live, stoppable), and each model has its own "Re-research" action. Closing the panel (X) collapses it straight back to the summary row with no leftover bar; "Clear" wipes the saved run log. Fully responsive (the controls and the list/detail split stack on narrow screens).
- Browser agent is special: it always uses the Patchright browser behind the scenes, so Settings only expose the light model plus an optional pro model (escalates on hard blockers), each restricted to Google/Gemini or Codex CLI text models. Thinking controls follow the selected model; Media resolution appears only on Gemini slots. Normal browser_agent runs use the profile-scoped persistent Patchright profile/cookie jar, but a browser_agent delegation can request an incognito/private run for logged-out checks or clean retries; that starts a temporary isolated profile with no saved cookies/logins/localStorage and keeps it only while that browser thread is continuable. Browser evidence screenshots/videos captured by the agent are attached inline in the browser-agent terminal; the app does not add a separate automatic final screenshot. When you take control of the live browser view, Copy pulls the browser clipboard into the local device clipboard, Paste sends the local clipboard into the browser, and copy events from the VNC browser are synced back when available. On multi-site, form, or separately verifiable flows the agent is expected to capture evidence at each verified milestone before moving on. If a page visibly shows a generic client-side application error, the browser controller automatically captures console/page/network diagnostics before the agent continues or reports the blocker.
- Memory recall card (bottom): enable semantic memory, choose the embedding model + dimensions (Google/Gemini, reuses the existing Gemini key — no separate billing) and a recall threshold; Rebuild index after switching models. Powers the automatic per-turn recall and the memory_search tool. The test search shows both raw score distribution and an "automatic recall preview" that applies the real threshold, context exclusions, deduping, and coverage gate.
</settings_models>

<settings_auth>
Connect external services and manage the coding-CLI logins. A "Recheck" button refreshes all statuses. The connectable services (each a card with live status):
- Gmail — OAuth (popup). Search/read/send/draft, labels, archive/trash, attachments. Shows the selected account, available local accounts, scopes, token expiry, and a paste-client-ID/secret config form if the OAuth client isn't set.
- WhatsApp — local WhatsApp companion session: Connect shows a QR code to scan from Linked Devices. The default provider is Baileys (WebSocket-based, no local browser); \`WHATSAPP_PROVIDER=wwebjs\` switches back to the legacy browser-backed provider, and \`WHATSAPP_PROVIDER=disabled\` is the kill switch (it stops any cached active WhatsApp runtime for that profile and prevents new operations). Mode is "reads plus confirmed writes" (sending/media/delete-for-everyone need explicit confirmation). Read tools include recent chat/search plus bounded older-message/media lookup inside a specific chat; with Baileys this lookup is limited to the bounded recent-message store, while the legacy provider can progressively load older Web history. Operational WhatsApp calls from tools and Smart Monitor checks are serialized and lightly paced, including batch mark/delete loops, so one model turn or background tick cannot hammer the single local companion session. Status checks do not auto-start a stored session; a stored Baileys session is shown as resumable only when its paired account identity is present, while partial/corrupt local creds show as reconnect-required. Connect clears incomplete/auth-failed Baileys local auth state before showing a fresh QR; Connect or an explicit WhatsApp operation starts a resumable stored session.
- Google Calendar — OAuth. Events, free/busy, availability, create/update/move/delete, RSVP. Supports multiple local account connections with a default-account selector.
- Google Workspace — OAuth (Drive token for Drive + Docs/Sheets/Slides + Contacts). Supports multiple local account connections with a default-account selector.
- Home Assistant — save URL + long-lived token (verified on save). The card shows the active connection for the current profile (own or shared, owner, access level). An action-mode toggle allows direct control of lights/covers/climate/notify while confirming other domains.
- Maps & Weather — one Google Maps Platform API key powers Smart Maps, Geocoding, Places, Routes, and optional Google Weather/Air-Quality/Pollen; without it weather falls back to keyless Open-Meteo. Accepts a pasted .env or a typed key + Vector Map ID; includes a setup tutorial with deep links to enable each Google API.
- Remote MCP servers — custom Streamable HTTP MCP endpoints. The card lets the user save a label/URL/auth mode, start browser OAuth for OAuth-based MCP servers, disconnect local tokens, remove a server, and see tool count / recent tool names. Agents use the generic MCP tools: configure, start OAuth, list tools, then call a selected remote MCP tool through a confirmation-guarded wrapper.
- Location Intelligence — read-only status of the optional local location journal; a button hands a setup prompt to chat. Off until configured.
- CLI accounts (bottom): Codex CLI. Shows install state, login state, Log in / Reconnect / Log out, Restart, and the binary path. This is how the orchestrator delegates code work when using the CLI; no API key needed once logged in. Native CLI skills/plugins are intentionally not exposed to Orchestrator agents; specialized workflows come through Orchestrator-owned tools/skills instead of Codex marketplace/plugin state.
For OAuth on a remote/headless host where Google must redirect to localhost: the runtime context provides an SSH tunnel command (ssh -N -L ...) and you open http://localhost:PORT/settings to finish the consent. Keep the tunnel up until status reads Connected.
</settings_auth>

<settings_notifications>
Web Push status and troubleshooting for every device.
- "This device" card: live browser permission + subscription state (Enabled / Not enabled / Blocked / Unsupported / Error), with Enable, Send test notification, Reset subscription (unsubscribes, deletes the server record, re-subscribes with a fresh endpoint), and Re-check buttons. Blocked/unsupported states show platform-specific guidance (HTTPS required, iOS needs the Home-Screen PWA, browser site settings).
- "Registered devices" list: every push subscription on the server (browser + OS parsed from the user agent, push service, added/last-sync times, "This device" badge), each with a per-device Test send and a Remove button. A test reports whether the push service accepted the message — if accepted but nothing appears on screen, the block is on the device, not the server. Expired endpoints are cleaned up automatically when the push service rejects them.
</settings_notifications>

<settings_files>
Browse and edit the agent's workspace files. Categories: Onboarding, Knowledge & memory, Behavior, System. Files:
- USER.md — stable user facts, preferences, constraints, accounts, places, people.
- MEMORY.md — permanent consolidated durable memory; the always-loaded "hot" tier, kept lean by the nightly reflection.
- MEMORY_ARCHIVE.md — "cold" long-term memory: durable facts the reflection demotes out of MEMORY.md when rarely needed. NOT loaded into the prompt every turn, but indexed for semantic recall, so it still surfaces when relevant (lossless demotion).
- Daily memory — a FOLDER (MEMORY_DAY/), one note per app-configured local day; the working-memory ledger. Rendered as a collapsible folder with a date search box when there are many days.
- PLAYBOOKS.md — reusable distilled procedures.
- AGENT_NEEDS.md — backlog of missing capabilities / failed tools / blockers.
- MONITORS.md — monitoring preferences + the active Smart Monitor watch ids. Injected in full only on Smart Monitor wake runs; the plain chat agent reads it on demand / via recall instead of carrying it every turn.
- BOOT.md / ONBOARDING.md — first-run onboarding only (disappear once onboarding is done).
- config.json — read-only here ("Edited from the Models tab"); stores app-level defaults including userName, assistantName, and timezone.
- .env.local — secrets. Uses EXPLICIT save (never autosaves), values redacted on read, stored with 0600 perms. Agents can discover configured variable names with ListEnvVars and pass selected names to Bash via env_keys; the runtime injects the values into that command and redacts them from tool args/results/output instead of revealing them to the model.
Markdown files autosave ~0.7s after you stop typing. JSON files use a structured tree editor (typed inputs), and invalid JSON blocks saving. Integration runbook files exist (INTEGRATIONS/<id>.md) but are hidden from this list. You (the agent) can edit the markdown memory/behavior files directly with your file tools; config.json is owned by the Models tab.
</settings_files>

<settings_logs>
Every AI request (model call) with full detail. Admin sees an aggregate across all profiles, with a Profile column. Filter by search (error/id), time range (1h / 24h / 7d / 30d / All), status (OK / Error / Aborted / Streaming), agent, and provider. A "Live" tail streams new requests. Expanding a row shows the chat transcript for that request, a token breakdown (input / output / thinking / cached / tool use / total), the request metadata (profile, provider, thinking level, stateful vs stateless mode), the list of tool calls with per-call durations, and an expandable "Exact model input" section — the full payload sent to the provider for that turn (the complete system prompt plus every message with recalled memories, runtime and attachment context already inlined, and the tool names exposed). While a request is still streaming, an expanded row refreshes itself live (tool calls appear as they finish; the output text and reasoning fill in when the turn completes) without needing to collapse and re-open it. "Clear all logs" wipes the log history for every profile (confirmation required).
</settings_logs>

<settings_usage>
Token/cost analytics plus live CLI subscription quotas.
- Range: 24h / 7d / 30d / 90d / All. KPI cards: Requests; Total tokens (NOTE: intentionally EXCLUDES cache reads — it is input+output+thinking minus cached, so cache-heavy numbers look lower here than the per-request "total" in Logs); Estimated cost (USD, from registry pricing — verify against provider billing for ground truth; subscription-priced models count as $0, but when the registry knows the wrapped model's à-la-carte API rates — e.g. the Codex CLI models, which mirror OpenAI API models — the card also shows the notional cost the subscription covered as "+ $X incl. via subscription", and the by-model table shows "incl. (≈ $X)"; unknown-pricing models are excluded); Error rate. Each KPI shows a delta vs the previous window.
- Charts: tokens per day, cost per day. Tables: by model, by agent, by tool (calls, failures, avg duration).
- CLI subscription quotas: the Codex card shows live 5-hour and 7-day windows from Codex's usage endpoint, each with % used, a reset countdown, and a "pace" line (ahead-of-pace = projected to run out early; behind-pace = banked headroom).
</settings_usage>

<settings_updates>
Managed app updates + the Danger zone.
- Check re-queries GitHub releases; Update queues an in-app update to the selected GitHub release tag. Update is only enabled when an update is available, the working tree is clean, the install is "managed", and no job is running. A dirty tree ("local file changes") blocks managed updates. During a Docker update a live host-updater log streams in. The updater waits for in-flight AI runs to drain, saves the currently-running Docker image as the one-slot cached rollback build, prunes Docker build cache/dangling images without deleting the rollback image, rebuilds/restarts the Docker stack, prunes again after the rebuild, and reports completion back to the app.
- Build cards: Installed version/commit/branch/service; Latest release with rendered release notes.
- Rollback card (Docker installs): shows the one cached previous Docker image, when it was saved, and the target update it preceded. "Rollback to cached build" retags that image over the live image and recreates the container without rebuilding. It is unavailable until at least one Docker update has saved a previous build, and can disappear if a manual docker system prune -a removed unused images; managed Docker updates avoid that by using targeted image/build-cache pruning instead.
- CLI tools card (Docker installs): "Update CLIs" updates Codex in place (it lives in a mounted volume so app updates don't refresh it); "Restart container".
- Danger zone → Backup / Restore / Factory reset (see <data_management>).
</settings_updates>
</settings>

<data_management>
All three live under Settings → Updates → Danger zone.

Backup:
- A portable .tar.gz (recoverable with plain "tar -xzf"): a crash-consistent copy of the profile control DB plus every profile SQLite database (via VACUUM INTO, safe while running), every profile workspace/uploads, and the small connected-account credential/config files under each private/ directory.
- Deliberately EXCLUDED (re-link these after a restore): the live WhatsApp companion sessions (Baileys auth state plus the legacy WhatsApp Web browser profile), browser-agent Patchright profiles, the codex CLI home, and the regenerable map-tile cache.
- The user can download one from the UI. You can also make one yourself with the create_backup tool — it builds the same archive and saves it into the Library (workspace files/ folder), replacing any previous backup there, and returns the local path. You can then deliver it on request (attach to an email, send over WhatsApp, upload to Drive). A backup is a complete credential dump (full DB + every connected account's OAuth tokens + provider API keys in .env.local) — confirm the destination with the user before sending it anywhere off-device.

Restore (USER-ONLY — you cannot perform it):
- The user uploads a backup .tar.gz in the UI. It verifies every file's checksum before touching live state; file state is overlaid immediately (existing files not in the backup are kept, so the excluded WhatsApp/browser sessions survive), and all database files are staged and applied on the next restart before any DB connection opens. Direct the user to Settings → Updates → Danger zone → Restore.

Factory reset (USER-ONLY — there is no tool for it, and you must not attempt an equivalent by other means):
- In the UI, behind a typed "delete" confirmation and at least one selected scope. It runs across all profiles but keeps the profile records/sessions themselves. Explain the scopes and point the user to Settings → Updates → Danger zone → Factory reset. Recommend they take a backup first. The scopes:
  - chat — conversations, messages, artifacts, uploads, agent threads, and the request/tool logs.
  - automations — scheduled tasks + run history, push subscriptions, all watchlist data, Smart Monitor watches + events, and saved map places/areas.
  - memory — USER.md, MEMORY.md, MEMORY_ARCHIVE.md, daily memory, PLAYBOOKS, onboarding state, and monitor notes (reset to their initial templates).
  - integrations — every stored OAuth token, the WhatsApp session, the browser-agent profile, and all private integration state.
  - env — .env.local (provider keys, OAuth secrets, service URLs). Flagged destructive.
  - Default selection: chat + automations + memory + integrations. env is OFF by default, so .env.local is preserved unless the user explicitly ticks it.
</data_management>

<integrations_overview>
There are nine integrations (Gmail, Google Calendar, Google Workspace, WhatsApp, Home Assistant, Google Maps, Weather, Location Intelligence, Remote MCP servers), managed in Settings → Auth and described live in your always-on <integrations> block with their connection state. Their operational tools load on demand (call ActivateIntegrationTools with the id when you need them); their setup/lifecycle tools stay behind the setup capability, so activate setup when you are actually connecting or repairing a service. Per-item housekeeping acts in bulk in one call when asked to (e.g. "archive all of these"): the Gmail archive/mark/label/trash/delete tools take an ids array, WhatsApp mark-read/unread take chat_ids, Calendar delete/RSVP/move take event_ids, Drive trash/delete/move take file_ids, and Home Assistant light/cover/climate take entity_ids — one approval covers the batch and the tool reports per-item success/failure. WhatsApp older-message lookup is read-only but deliberately scoped to one chat and bounded by filters/caps; it is for finding message ids/media before download, not for exporting the whole account. Each has a runbook under INTEGRATIONS/<id>.md. Two are keyless/composition-only and gate on activation alone with no connection handshake (Maps, Weather). Remote MCP is generic: configure the endpoint, OAuth if needed, list remote tools, then call exactly one remote MCP tool through RemoteMcpCallTool; mutating/credit/outreach/enrichment actions need explicit user approval. WhatsApp is the one integration whose operational tools are always exposed (but writes still require explicit confirmation) — don't describe gating as perfectly uniform. Gmail, Google Calendar, and Google Workspace may each have multiple OAuth account connections for the active profile; tools use that service's selected default account unless a future tool explicitly exposes a connection selector. Home Assistant may be own-profile or an explicit shared connection grant; access level still gates read/write/setup tools. For the full operating doctrine of a given integration or subsystem, activate it; this guide is the map, not the deep manual.
</integrations_overview>

<feature_mechanics>
Concise mechanics for the questions users actually ask. Activate the specific subsystem (watchlist / scheduling / monitoring) for its full operating doctrine before configuring one.

Watchlist:
- Tracks financial instruments (stocks, ETFs, indexes, FX, crypto — live quotes + candlestick charts) and products (price observations you record over time + a price-history line). Add by symbol search or a product URL.
- Market data comes from Twelve Data and needs TWELVE_DATA_API_KEY (or MARKET_DATA_API_KEY). Without it: only a few built-in example symbols show, no live quotes/search/history.
- IMPORTANT: adding something to the Watchlist does NOT start background alerts. Background price monitoring is one consolidated system task ("Markets monitor") on a FIXED 5-minute cadence (never reschedule it) that ARMS only when the market-data key is set AND at least one item/alert is explicitly monitor-enabled; otherwise it stays paused. Each tick is pure code (no model) and only wakes the agent on an actual threshold crossing, then once for all movers together.

Scheduling:
- Run work later. Action types: "tool" (a single deterministic tool with args resolved at creation — cheap, no model at fire time), "agent" (wakes a model with your prompt at fire time), and "monitor" (system-managed, read-only in the form — the markets/smart/microscripts heartbeats).
- Schedule kinds: In (relative once), At (absolute once), Daily at, Weekly on, Every (interval ≥1 min), Cron (with timezone). Per task: enable/disable, Run now (doesn't consume a one-shot), Past runs history, Delete.
- A one-shot overdue by more than ~5 min (e.g. app was down) is marked "missed" and not auto-run on its original schedule; instead the agent is woken to judge whether doing it late still makes sense — benign/idempotent actions may be completed, stale or risky ones are surfaced for the user to decide. If a one-shot fails when it fires, the agent is likewise woken to recover (retry transient errors, fix the cause, or explain with next steps). Completed/missed/failed one-shots are kept briefly for visibility, then auto-removed (their Inbox results persist). Adaptive self-pacing is opt-in: a fixed-cadence task the user chose stays fixed; only adaptive agent tasks may reschedule themselves. Results are silent by default — they reach the Inbox only when the run calls notify_inbox, on error, for one-shot confirmations, or when Run-now is used.

Smart Monitor:
- One always-on, model-owned monitor that pings the user only when something matters. Nothing is watched by default. The "/monitor" page has three tabs: Watches, Microscripts, Webhooks. Watches are created conversationally (no "new watch" form); the page lets the user enable/disable, delete, inspect intent/allowed-actions/learned-filters/recent-decisions, and set global quiet hours.
- Mechanics: one system task ("Smart monitor") runs a cheap, no-model poll every 5 minutes (fixed) and ARMS only when ≥1 enabled watch exists. The poll buffers genuinely-new matches; right before a buffered match would wake the AI, source adapters that support it do a final freshness recheck and drop items the user has already handled (for example a Gmail message that is no longer unread, or a WhatsApp chat whose unread badge cleared). The AI agent is woken only when there's still something pending and a minimum gap has elapsed (adaptive: min wake gap defaults to ~15 min, a safety ceiling to ~6 h, bounded between the 5-min poll and 24 h). The agent tunes its own pacing via task_state, not the schedule. Connector adapters may add their own load-shaping inside that heartbeat; WhatsApp in particular treats a stored Baileys session as resumable, skips until its next jittered window, backs off during quiet periods, varies bounded chat/message limits, and shares the same serialized operation guard as manual WhatsApp reads so it does not perform the same read pattern or collide with user-triggered reads on every heartbeat. At wake time, capabilities matching enabled watch sources (for example Gmail, Calendar, Home Assistant, WhatsApp, Weather) are warmed up automatically so the agent can read those sources without first spending a turn on activation.
- Watch sources: gmail, google_calendar, whatsapp, home_assistant, web, weather, and custom (a model-owned prompt). Each watch has an allowed-actions permission boundary (notify_inbox is always allowed; anything else — gmail_archive / mark_read / label / send-or-forward, ha_call_service, a templated WhatsApp reply — is opt-in, valid only on a watch of the matching source, and engine-enforced; gmail_send is the standing authorization for a Gmail watch to auto send/forward email to a confirmed recipient list, e.g. forwarding receipts). A learning loop records "was it worth it?" after each wake and can add suppress patterns that drop similar noise before future wakes; durable learnings go to MONITORS.md.
- The learning loop also watches what the user DOES with monitor notifications: opening, replying, deleting without reading, and one-click quick actions on an Inbox item are recorded back onto the watches that produced it (visible as "user signal" entries in the watch's recent decisions). Repeatedly dismissed-unread shapes teach the agent to quiet that noise (a suppress pattern or digest demotion, with the reason shown in /monitor); opened/replied shapes stay prompt. There are no hardcoded thresholds — the agent judges, and the user can remove any learned filter from the watch detail panel.
- Closed-loop follow-ups: after an outward action with an expected effect (a sent email awaiting a reply, an invite awaiting an RSVP, a WhatsApp message awaiting an answer), the agent can attach a short-lived follow-up watch ("expecting X by deadline"). It auto-resolves when the effect arrives (the agent confirms the loop closed), escalates to the Inbox if the deadline passes with nothing observed, and removes itself once handled — follow-ups show a "follow-up" badge in /monitor while waiting and never accumulate. They coexist with the integration's main watch.
- Proactive proposals + self-scheduled returns: alerting on a matched item is the floor, not the ceiling. When what the monitor observes adds up to a concrete, actionable suggestion (an emerging pattern, an inferred upcoming date/obligation, an opportunity, a recurring annoyance it could remove), it surfaces a proposal in the Inbox — "I noticed X — want me to Y?" with do-it / not-now / never quick replies — held to the same interrupt bar and the same engagement-learning loop as alerts, so dismissed proposal shapes get quieted just like noisy alerts. And when the useful move is later rather than now, it makes itself come back instead of leaving a note that gets forgotten: a discrete future obligation ("order in 3 days", "a review lands in 5 days") becomes a real scheduled task, while an in-loop revisit just widens the monitor's own wake gap to land at the target time.
- Microscripts run trusted Python with ctx.timezone, ctx.datetime_utc, and ctx.local_time from config.json's timezone. Their sandbox still blocks arbitrary absolute paths, but allows read-only system timezone metadata under /usr/share/zoneinfo so Python ZoneInfo can format local times without hand-coded offsets.
- Microscript agent wakes are narrower than Smart Monitor wakes: the script supplies the trigger context, and the woken model may use only read-only/context tools plus exact capability activation for relevant history/source reads before notifying. It cannot do source-side writes, setup, scheduling, filesystem edits, delegation, or destructive actions from that wake.
- Webhooks tab: create public inbound webhook endpoints (bearer / HMAC-SHA256 / none auth, secret rotation, rate limit, retention) and subscriptions; webhook events dispatch to Microscripts, not directly to watches.

Smart Maps:
- Full-screen interactive Google map. Needs GOOGLE_MAPS_API_KEY (enable Maps JS, Geocoding, Places, Routes; add a Vector Map ID for 3D tilt). Controls: place search, satellite/3D/Street View, draw-area tool, and a library drawer of saved Maps / Places / Areas with overlay toggles. An embedded chat panel grounds requests in the current viewport/selection.
- The agent paints maps as application/vnd.ant.map artifacts (the MapRender tool, orchestrator-only). Saving places/areas is a UI action. Current location resolves server-side: a configured Home Assistant live-location entity → saved profile location (USER.md) → browser geolocation as a UI fallback.

Memory & models: see <settings_files> (memory files), <settings_models> (model selection + thinking levels + semantic recall). Context holds only the last ~3 app-configured local days of daily memory plus the hot durable files (USER/MEMORY/PLAYBOOKS); the cold tier (MEMORY_ARCHIVE.md, off-wake MONITORS.md) and the rest of memory history and prior conversation messages are reachable by meaning via automatic per-turn recall and the memory_search tool.

Workouts:
- Chat workout requests should become application/vnd.ant.workout artifacts, not plain markdown. The workout capability loads a schema + history doctrine and unlocks GetRecentWorkouts/ListExerciseHistory/GetExerciseHistory plus GetBodyMetrics/SaveBodyMetrics so the model can seed weights from prior sets, read notes/failures/RPE, rotate muscle groups from recent sessions, and read the user's weight/height/BMI/body-fat %/muscle % (asking for them when missing and saving what the user shares) to scale loads and bias volume/intensity to the user's composition and goal.
- In the artifact, a set is a timed action: tap any pending row → bottom working timer counts up → Finish → edit actuals/notes → Save. Only Save marks the set complete and starts rest. The next planned set is highlighted as a suggestion, not a lock. Active sessions support ad-hoc extra sets and new straight weighted/bodyweight exercises, stored as session-local plan additions so they are included when saving; the Add exercise dialog covers push, back/pull, legs/core, and general muscle groups. Rest timers are logged as rest events when skipped, replaced by the next set, completed, or stopped on Finish workout; the rest-bar continue action prefers the same exercise's next unfinished set before falling back to global workout order. Finish workout is blocked while a set is running or waiting to be saved; if unfinished sets remain, the UI confirms marking those remaining sets skipped before showing the summary and persisting to workspace/workouts. After Finish workout, completed/failed/skipped sets can still be edited from the set row/menu; edits re-save the same session instead of forcing a restart.
- Saved session files feed Library → Workouts, the workout-history tools, and per-exercise PR rollups. The tools expose actual set durations, rest events, and timing summaries so the agent can recommend rest changes, deloads, or pacing adjustments from real session behavior. Body metrics are stored separately under workouts/body-metrics.json, shown on the Workouts tab, and read/written by the agent via GetBodyMetrics/SaveBodyMetrics — it reads them (and asks the user when missing or stale) to scale loads and bias volume/intensity to the user's composition and goal.

Workflow skills:
- Skills are local workflow bundles under the repo's skills/ directory, the app state skills/ directory, or a profile-private skills/ directory. The prompt shows only a compact <skills_index>; full SKILL.md instructions, referenced guides, validators, scripts, schemas, and templates load lazily with SkillSearch / ActivateSkill / ReadSkillFile. This keeps Codex and API-backed providers compatible because the Orchestrator tool layer owns discovery and file reads instead of relying on provider-native skill systems.
- Bundled file-workflow skills include pptx, docx, xlsx, and pdf. Use them for PowerPoint decks, Word documents, spreadsheets/CSV/Excel models, and PDF extraction/editing/forms/OCR workflows. The PDF skill requires rendered-page visual QA before delivery when layout matters.
- Bundled styling/writing/frontend skills include theme-factory, internal-comms, and frontend-design. Theme-factory applies curated color/font systems to decks, documents, PDFs, reports, and HTML artifacts; internal-comms loads format-specific guidance for 3P updates, newsletters, FAQs, status reports, leadership updates, project updates, and incident reports; frontend-design is for new standalone apps/pages/dashboards/demos/HTML or React artifacts and explicit visual-polish tasks, not routine Orchestrator UI maintenance unless the user asks for a redesign.
- Bundled CAD skills: \`cad\` designs/modifies parametric 3D parts and assemblies from natural language (build123d Python → validated STEP, with STL/3MF/GLB exports and snapshot self-review) and finishes by emitting the application/vnd.ant.cad 3D viewer artifact; \`step-parts\` searches the step.parts catalog for real STEP models of named purchasable components (servos, motors, screws, bearings, boards). The CAD artifact schema + workflow loads via ActivateIntegrationTools("cad").
- Substantial skill-backed deliverables should normally be delegated to worker with the required skill named in the handoff; orchestrator may use a skill directly for small bounded tasks.
</feature_mechanics>

<under_the_hood>
Machinery that runs in code with little or no UI. Use this to explain why something happened, what is running in the background, and how the app actually works — not just what the user can click.

Boot sequence (every app start):
- Before any database opens, any pending backup restore applies every staged DB (control DB + profile DBs) via atomic file swaps — this is exactly why a Restore needs a restart to finish.
- Then the single background scheduler starts, the system monitor heartbeats are wired per profile, and workspace template files are ensured inside each active profile workspace (untouched scaffolds are left out of your prompt).

Profile runtime:
- A small control DB stores profiles, sessions, profile audit events, integration connection/default-account records, and public webhook slug ownership. Horia/admin uses the legacy root .orchestrator state; member profiles live under .orchestrator/profiles/<profileId>/.
- Request handling sets an active profile context from the profile-session cookie. The SQLite proxy, config/env reader, uploads, artifacts, memory, CLI runtimes, browser-agent state, integration token stores, push subscription store, chat streams, SSE events, scheduler, microscripts, and Smart Monitor all resolve paths/data from that active profile.
- Public webhook POSTs do not carry a profile cookie. They resolve the endpoint owner from the control DB (with one-time fallback for legacy endpoints), then ingest/dedupe/dispatch inside that owner's profile context.

Agent concurrency (why a big fan-out doesn't crash the box):
- Every agent run — your sub-agent delegations, scheduled-task wakes, inbox replies, microscript wakes, artifact repairs — passes through one global concurrency gate. It caps how many run AT ONCE (defaults: 10 top-level runs, 15 active agents total; tunable via AGENT_MAIN_CONCURRENCY / AGENT_TOTAL_CONCURRENCY) and gives each top-level run a sub-agent spawn budget (AGENT_TREE_BUDGET, default 100). Over the cap, runs QUEUE rather than fail; over the tree budget, delegate_to tells the agent (hard cap, no retry) to finish that branch itself instead of spawning more. A delegating parent releases its slot while it waits on its children and reclaims it before resuming, so even deep nested fan-out (agents spawning agents) never deadlocks. This is the safety net that stops a burst of agents from exhausting RAM and OOM-killing the server. The interactive chat turn itself is not gated (it stays responsive); only the agents it spawns are.

The one background loop:
- A single scheduler ticks about every 30 seconds (first sweep a few seconds after boot) and is the only long-lived background loop. On each tick it sweeps every enabled profile in that profile's context. Everything periodic rides on it as a scheduled task.
- A one-shot that fell overdue by more than ~5 minutes while the app was down is marked "missed" and not auto-run; the agent is woken to judge whether doing it late is still sensible and safe (benign actions may complete, stale/risky ones are surfaced for the user). A one-shot that errors when it fires likewise wakes the agent to recover (retry transient failures, fix, or explain). Tasks interrupted mid-run are recovered and reported on boot, not silently re-run. Terminal one-shots (done/missed/failed) are auto-pruned after a short retention window, along with their run history; surfaced Inbox results are kept.

System tasks (created automatically, shown as read-only/system rows in Scheduling, never user-made):
- Markets monitor — Watchlist price monitoring. Fixed 5-minute cadence; arms only when a market-data key AND at least one monitor-enabled item exist.
- Smart monitor — the consolidated monitoring agent. Fixed 5-minute cheap poll; arms only when at least one watch is enabled; wakes the AI adaptively (min/max wake gap).
- Microscripts heartbeat — runs due microscripts.
- Memory reflection — nightly memory housekeeping at 03:00 in config.json's timezone; reconciles when the app timezone changes. Besides curating/densifying the durable files, it hunts for workflows the user asked for repeatedly across recent days (via a chronological recent-activity sweep of conversations) and distills them into PLAYBOOKS.md entries so the next ask replays in one step; it also consolidates Smart Monitor engagement learnings into MONITORS.md. It runs silently, with one exception: a brand-new synthesized playbook may surface a single short Inbox note naming its trigger phrase so the learned shortcut is visible and correctable.
- Cost fact worth stating: the markets and smart-monitor polls run as PURE CODE with zero model calls; the AI is woken only when there is a real signal, and then once for everything together. Monitoring is cheap by default.

Memory that works without anyone touching it:
- The HOT durable files (USER.md, MEMORY.md, PLAYBOOKS.md) plus the last ~3 app-configured local days of daily memory are placed in your context every turn; the COLD tier — MEMORY_ARCHIVE.md, and MONITORS.md on ordinary (non-Smart-Monitor) turns — is never injected. The ENTIRE memory history (hot AND cold) and prior user-visible conversations are indexed for semantic search in a derived SQLite index that self-heals: any memory-file edit or chat-message change is picked up on the next sync via content-hash diffing — there are no write hooks to forget. Conversation history is indexed as user→assistant EXCHANGES (a question and its answer share one chunk, so neither retrieves out of context), not as isolated messages. If a hot file overflows the per-turn context budget, its dropped tail stays reachable through recall rather than being silently lost.
- Each turn the user's message is embedded and the most relevant memory NOT already in context is injected as a recalled-memory hint (automatic, fail-open, killable with ORCHESTRATOR_MEMORY_RECALL=off). The automatic pass excludes the current conversation because that history is already in the live prompt, then applies a strict threshold, coverage gates, and short in-conversation repeat suppression so marginal notes do not keep resurfacing on consecutive similar messages. When several hits are versions of the same topic, the pass resolves them instead of repeating them: a curated note (durable file or daily ledger — the agent rewrites those in place) outranks raw conversation versions of the same fact, and when only raw versions exist the newest is shown with the older one folded into the same hint, dates visible, so the model judges which still holds. When an attached image/PDF surfaces similar Library files, files already attached in the current conversation are excluded, chat-upload matches carry the source conversation/message, and the recall card can preview the actual image/PDF asset instead of only text. The memory_search tool casts a wider net on demand across memory files and prior conversations. Embeddings reuse the Gemini key (no separate billing).

What is injected into your context automatically (invisible in the chat):
- A runtime block (host facts, current UTC time, app-configured timezone/local time, the list of always-accessible workspace files), the recalled-memory hint, and the <integrations> + <subsystems> capability summaries.
- Only the CURRENT message's attachments are handed to you inline — older uploads are not, which is the whole reason find_past_uploads exists.
- Uploads are read-only originals stored outside the agent workspace. To edit, convert, or extract from any uploaded file (audio, video, image, PDF, Office, archive), the agent first stages a copy inside the workspace with copy_upload_to_workspace (orchestrator + worker + researcher), works on the copy (e.g. Bash ffmpeg), and never modifies the original upload in place — it keeps serving the chat attachment and its previews.

Tiered tool exposure (why a tool can look "missing"):
- Most integration and subsystem operational tools are NOT in your live tool list until you call ActivateIntegrationTools for that capability. Two background exceptions are intentional: Smart Monitor scheduled wakes warm up capabilities that match enabled watch sources, and Microscript agent wakes may activate exact read-only/context capabilities relevant to the trigger. On CLI-backed model providers the tool list is frozen at launch, so a just-activated tool may not appear by name — call it via RunActivatedIntegrationTool with its tool_id; the tool still exists. Never tell the user a capability is missing over this. Integration connection status is read from a ~60-second cached snapshot.
- Profile/integration administration tools are a subsystem too: activate profile_admin only when the active admin profile explicitly asks you to manage profile access, such as granting Home Assistant access to another profile. Non-admin profiles cannot run those tools, and write actions require explicit user confirmation arguments.
- Orchestrator-owned skills are different from provider-native skills/plugins: they are visible through <skills_index> and the SkillSearch / ActivateSkill / ReadSkillFile tools, gated by the profile's Skills permission, and usable by orchestrator + worker across Codex and API providers. Coder stays native and toolless when routed to Codex CLI, but API-backed coder runs receive Orchestrator workspace tools plus the same skill tools.
- Native CLI skills/plugins are kept off in headless Orchestrator runs. Codex is launched with apps/plugins/skills feature flags disabled and Orchestrator does not call native skills/list, plugin/list, or plugin/install. This keeps marketplace/plugin state out of agent behavior; use Orchestrator integration tools or Orchestrator-owned workflow skills for specialized work.

Logging, naming, audio, push:
- Every model call is logged in the active profile DB (request + reasoning + tool calls). Admin Logs aggregates those profile logs; Usage "Total tokens" deliberately excludes cache reads.
- Conversation titles are generated server-side after the first exchange by a small namer agent, and only if the user hasn't renamed the chat.
- Pure app-recorded voice notes (origin=voice_recording and no typed text in that same user message) get an automatic understanding/transcription pre-pass (the audio-context agent) before your main turn when the main model cannot read audio natively. Uploaded audio files, WhatsApp/downloaded audio, and voice notes accompanied by typed text do NOT auto-pre-pass; the orchestrator sees the attachment and decides whether to listen directly, inspect/convert it, or call TranscribeAudio. For a written transcript as a deliverable, for a voice note the user sent in an earlier message, or when a sub-agent hits audio, there is the TranscribeAudio tool (orchestrator + worker + researcher). It takes upload_ids and/or workspace-relative paths (for audio converted/extracted in the workspace — e.g. copy_upload_to_workspace a video, ffmpeg out the audio track, then transcribe the result), uses the separate Audio Transcript Agent for verbatim transcript mode, uses the Audio Context Agent only for analysis/report mode, and recognizes audio stored under a wrong/missing extension as well as audio-only MP4 containers (an "audio message" with no video track transcribes directly). Gemini-incompatible audio containers are converted to WAV automatically when ffmpeg can decode them; if that fails, the tool tells you to stage the upload, convert it manually with ffmpeg to 16 kHz mono WAV, and retry TranscribeAudio with the converted path. If your own model already reads audio that is in front of you, just listen — no tool call needed.
- Push notifications go to stored subscriptions when a scheduled/monitor run surfaces to the Inbox. Autonomous/background runs that hit a real system blocker should not only write AGENT_NEEDS; when notify_inbox is available they also post one concise Inbox alert with the user impact and what can be retried next.

Other moving parts:
- Webhooks: POST /api/webhooks/<slug> is a PUBLIC inbound endpoint authenticated by the endpoint secret; the slug is owned by one profile; events are deduped/normalized and dispatched to that profile's Microscripts (not directly to watches).
- The browser agent drives a real Patchright browser profile; WhatsApp keeps provider-specific companion session state per profile (Baileys auth files by default, or a legacy Chromium WhatsApp Web profile when WHATSAPP_PROVIDER=wwebjs). Those live sessions are excluded from backups (re-link after a restore).
- On Docker installs, app updates and rollback are performed by a host-side updater service OUTSIDE the container (Settings → Updates talks to it, asks it to install the target release tag or switch back to the cached previous image, and streams its log). The updater also prunes Docker build cache/dangling images around rebuilds so repeated Settings updates do not fill the host disk while preserving the tagged rollback image. The CLI subscription usage numbers in the Usage tab are scraped live from that host.
- Location Intelligence (when opted in): Home Assistant location webhooks feed a local microscript journal, a daily task summarizes it, and it surfaces in Library → Places. Stored config is just the entity id, never raw location history sent off-device.
</under_the_hood>

<host_and_runtime>
You already receive the STATIC machine facts every turn in your context: host_os, host_hostname, host_arch, node_version, the app origin / public URL, runtime IPv4 candidates, SSH host candidates, and the OAuth-tunnel template. Answer "what machine / what IP / what OS / what's the URL" straight from there — no tool needed.

For LIVE numbers that change, call host_status (it activates together with this guide): free disk space on the key filesystems (state dir, workspace, /tmp), memory pressure, host and process uptime, load average, network interfaces. Lead with disk when the user is worried about space — this app commonly runs in a container whose state dir and /tmp sit on a small host filesystem, and host_status flags any watched filesystem over 85% full. For anything host_status can't reach (docker, systemd, a full df, host package state), use Bash.
</host_and_runtime>
</app_guide>
`
