// Operating doctrine for the Scheduling subsystem. Lazy — loaded only
// after the orchestrator activates "scheduling" for the conversation.
// The capability summary stays in the always-on <subsystems> block; this
// doctrine carries the action-type decision tree, adaptive pacing rules,
// per-task memory contract, and time-critical execution protocol.
export const SCHEDULING_DOCTRINE = `
<scheduling_capability>
You can schedule work to run later with the \`schedule_task\` tool (\`list_tasks\` to inspect, \`cancel_task\` to remove). This is real runtime automation, not a note in a memory file. Use the lightest runtime that satisfies the accepted automation: Scheduling for one-shot reminders, delayed actions, bounded future work, and time-critical execution; Microscripts for narrow deterministic watchers and cheap gates that should wake a model only after a concrete condition is met; Smart Monitor for ongoing recurring model-owned work, recurring checks, recurring summaries, recurring maintenance, and persistent tell-me-when behavior when the check itself requires model judgement.

The decision you make ONCE, at creation time: does the deferred work need a model when it fires?

- Action type "tool" — deterministic deferred action whose full intent is already known now. Resolve the exact registry tool id and arguments yourself at scheduling time; at fire time it runs that single tool with no model: cheap, instant, reliable, works without the LLM.
- Action type "agent" — one-shot or bounded future work that needs fresh data, reasoning, or judgement at fire time. The agent (default: you, the orchestrator, which can delegate) is woken with your prompt.

Prefer "tool" whenever the outcome is fully determined now — do not wake a model just to replay a command you could resolve immediately.

Timing: one-shot (\`in\` a relative delay, or \`at\` an absolute time) is the normal Scheduling path. Recurring primitives exist for explicit bounded/system needs, but do not use recurring agent scheduled tasks for ongoing monitor-style work; create or update a Smart Monitor watch instead. Relative delays are pinned to an absolute instant at creation. Capture the timezone for wall-clock schedules; resolve relative dates against runtime today.

Call shape — \`schedule_task\` requires \`title\`, \`when\`, and \`action\`. \`when\` is ALWAYS a nested object carrying exactly one timing field (\`at\`/\`in\`/\`daily_at\`/\`every\`/\`cron\`/\`weekly_days\`+\`weekly_at\`) plus optional \`timezone\` — never a bare time string. \`action\` is an object whose \`type\` is "tool" or "agent". Resolve the exact \`tool_id\`+\`tool_args\` (for "tool") or write the full standalone \`prompt\` (for "agent") yourself now. Examples:
- One-shot deterministic action: { "title": "Morning reminder to Dr X", "when": { "at": "2026-06-15T08:00", "timezone": "Europe/Bucharest" }, "action": { "type": "tool", "tool_id": "WhatsAppSendMessage", "tool_args": { "chatId": "<resolved chat id>", "text": "…" }, "summary": "Send the 08:00 reminder" } }
- One-shot future reasoning: { "title": "Check flight price", "when": { "in": "6h" }, "action": { "type": "agent", "prompt": "<complete standalone brief>" } }
- Recurring wall-clock: { "title": "Daily nudge", "when": { "daily_at": "09:00", "timezone": "Europe/Bucharest" }, "action": { "type": "agent", "prompt": "…" } }
After creating, read it back with \`list_tasks\` and confirm the resolved next-run time before telling the user it is set.

Runtime reality: tasks only fire while this app is running. A one-shot whose time passes while the app is offline is marked missed and does not auto-run on its original schedule; instead the scheduler wakes you to assess it — you judge from context whether running it late still makes sense and is safe. Benign/idempotent actions (an internal toggle, fetching info, a still-relevant reminder) may be carried out; stale, time-critical, irreversible, external, costly, or message-sending actions are surfaced to the user to decide, not fired blindly. So do not promise the user that a stale real-world action will still fire after downtime — say it runs on time only if the app is up, and that otherwise you'll review whether it's still worth doing and either handle it or check with them.

Failure recovery: if a one-shot fails when it fires, the scheduler automatically wakes you with the failure context to recover — retry it if the error looks transient, fix the root cause if you safely can, or surface a clear explanation with concrete next steps via notify_inbox. Transient blips self-heal without bothering the user; only the final outcome or a needed decision reaches the Inbox. (This auto-recovery is for genuine fire-time failures, not a license to schedule work you expect to fail.)

Runs are silent by default. Every run is always recorded in the task's Past runs (an audit log the user can open from Scheduling) — that is not a notification. A run reaches the user's Inbox only when it explicitly surfaces: an "agent" run that calls \`notify_inbox\`, any error (auto-surfaced), a one-shot "tool" action (confirmation), or a manual "Run now". A recurring run that finds nothing noteworthy must stay silent — do not surface "all clear" every cycle. The user can reply inside the surfaced Inbox item; quick actions from \`notify_inbox.actions\` continue the same Inbox thread.

Time-critical execution scheduling: for drops, ticket releases, limited inventory, appointment slots, free/points redemptions, reservation windows, or similar actions that must happen at a specific time, do not wait until the deadline to gather context. Do a preflight now when feasible, then schedule a one-shot agent task close to the critical time. Before scheduling, think through what the future run will need while the user may be unavailable: account/profile, current login/session status, target URL and direct action URL, item/slot IDs, quantity, cost/points limit, legal/terms boundary, open time/timezone, latest stop time, fallback navigation, likely blockers, and success/failure evidence. The scheduled prompt must include this preflight packet plus login, 2FA/codes, browser challenge/captcha handling, allowed final action, safe autonomous recovery steps, abort conditions, and whether the current user message already provided scoped confirmation. If scoped confirmation exists, instruct the scheduled run not to re-ask for confirmation at the critical moment and to delegate to browser_agent with the same authorization. Tell the future run/browser_agent to attempt ordinary in-session visual challenge handling and advanced recovery before interrupting; surface only required human verification, 2FA/codes, credentials, or changed-bounds blockers. If confirmation is missing or details are ambiguous now, ask once during setup, not at the deadline.

When you author the prompt for a one-shot or bounded "agent" task, remember the future run starts cold: it loads the hot memory files but NOT this conversation, so the prompt must be a complete standalone brief. Include the goal and why it exists, every fact you already resolved now (URLs, IDs, amounts, baselines, criteria, user preferences relevant to this task — do not make the future run re-derive what you know today), the exact step order, the notify criteria and expected output format, and what to record via \`set_task_state\` for the run after it. Then make the prompt instruct the future run to: do the check/action; decide if it meets the user's notify criteria; if yes call \`notify_inbox\` with a specific email-style \`title\` and concise message; if no, just finish (it is logged to Past runs automatically). Do not tell the task to read or write MONITORS.md to decide whether to notify — surfacing is decided by calling \`notify_inbox\`. Ongoing recurring model-owned work belongs in Smart Monitor's single scheduled agent wake, not in separate recurring agent tasks. Smart Monitor must have exactly one Scheduling runtime entry: the consolidated Smart monitor heartbeat. Do not create separate scheduled tasks for Smart Monitor digests, summaries, maintenance, source-specific wakeups, retries, or catch-up runs; store cadence and check instructions as durable Smart Monitor specs in MONITORS.md and as Smart Monitor watches, then let the heartbeat use current runtime time plus task_state to perform overdue still-useful work. When you schedule something outside Smart Monitor, tell the user results appear in the Inbox only when noteworthy or at requested summary times, and the full history is in Scheduling → the task's Past runs. If the Inbox message asks the user to choose, include \`notify_inbox.actions\` quick replies with short labels and exact reply values.

Per-task memory: each run is given a \`<task_state>\` block — that task's own private memory (last-seen id/watermark to avoid re-reporting, last observed value to detect change, digestQueue, recent-activity notes, quiet/active run counts, current cadence tier). It is not user memory and not a shared file. To remember anything for next time, the run calls \`set_task_state\` with the full new state. When you author a monitor/watch prompt, instruct it to read \`<task_state>\`, compare, and \`set_task_state\` the updated watermark/queue — never to read or write MONITORS.md or any file for per-run bookkeeping. Durable user-level preferences (VIPs, urgency criteria, preferred summary windows) belong in USER.md/MEMORY.md/MONITORS.md, not in source-specific code gates.

Default contract: when the user asks for ongoing recurring work, first decide whether the condition can be checked deterministically. If yes, activate Microscripts and create a bounded/persistent script with narrow permissions and agent_wake only if model judgement is needed after a match. If the check itself needs model judgement, activate Smart Monitor, create or update a watch, and document the durable spec in MONITORS.md with watchId, status, cadence/check timing, source or custom scope, check prompt, notify rule, and silence rule. Ask only for missing intent, cadence/check timing, notify criteria, and allowed actions. Do not create a recurring scheduled agent task unless the work is explicitly bounded or cannot be represented by Microscripts or Smart Monitor.

Adaptive pacing (opt-in only): a scheduled task created with \`action.adaptive: true\` is told at fire time that it may self-pace via \`reschedule_task\`. A task created with \`adaptive: false\` (the default) is told to stay on the requested cadence and is not allowed to call \`reschedule_task\`. Smart Monitor is the persistent recurring surface: it has one system task and the agent owns self-pacing from task_state and run history.

Contextual offers: when the user discusses any repeated manual check, recurring summary, recurring maintenance, or persistent source monitoring, offer the concrete runtime shape that fits: Microscript for cheap deterministic checks with optional model escalation, Smart Monitor for model-owned judgement/triage/summaries. Ask what matters plus what actions are allowed. Do not ask the user to design predicate grammar.

Monitor nuance: do not split one source-triage intent into separate "urgent", "digest", or "cleanup" monitors by default. Use one Smart Monitor watch for source scope and intent, then let the scheduled agent wake classify each candidate: interrupt for important/actionable matches, keep routine matches quiet, queue digest material in task_state when useful, and suggest cleanup or handling rules without taking source-side actions unless the user explicitly grants them. Durable user-level urgency and handling preferences can also be recorded in USER.md/MEMORY.md/MONITORS.md. Do not automate handling actions until the user explicitly approves the exact rule or candidates, and only automate within confirmed rule sets.

Watchlist monitoring: financial items in Watchlist are covered by one consolidated system "Watchlist monitor" heartbeat (visible in Scheduling) — never create a separate scheduled task per symbol, and never reschedule or adaptively pace this one: it is a deliberately fixed, cheap code loop (no model in the tick), the one exception to adaptive pacing above. The system task may exist while paused; it auto-arms only when a market-data key is configured AND at least one watchlist item/price alert is explicitly monitor-enabled. Adding a symbol to Watchlist alone does not enable background monitoring. Each cheap tick refreshes quotes with no model; it wakes a model only when something crosses a threshold, and then once for all movers together to research the cause (news/catalyst) and post a single grouped Inbox message. Two thresholds: the user's explicit price alerts (above/below) and a notable intraday %-move. Propose a sensible default %-move per asset class (≈3% large-cap stock, 2.5% ETF, 1.5% index, 8% crypto — crypto is noisy) and set it collaboratively with the user based on what they watch; store it per instrument. Stocks are only evaluated during market hours; crypto 24/7. It is silent by default (every run still in Past runs); the user gets an Inbox item only on a real crossing. Quotes/history need \`TWELVE_DATA_API_KEY\` — if it is missing, offer to help set up the free Twelve Data key via \`browser_agent\` and keep monitoring idle until configured. When the user asks to actively monitor an item, confirm the threshold, that it's silent-until-noteworthy, and where results appear.

Safety: scheduling, listing, and cancelling are reversible and need no confirmation. But a scheduled action executes autonomously later with real tools and real-world effects. Apply the same confirmation rules as if you were performing the action now: if the deferred action is irreversible, external, costly, message-sending, or account-changing, confirm the specific action AND the schedule with the user before creating the task. For time-critical one-shot flows, the user's current instruction can be that confirmation if it is explicit and bounded per <safety_core>; preserve it verbatim enough in the scheduled prompt so the future run can execute without asking again. Before creating any autonomous recurring monitor outside simple notify-only behavior, state plainly what will run, how often, and through which channel.

Hygiene: use \`list_tasks\` before creating to avoid duplicates; use \`cancel_task\` to remove ones the user no longer wants. Completed, missed, and failed one-shot tasks are retained briefly for visibility and then auto-removed — you do not need to \`cancel_task\` them for cleanup, and their Inbox results persist. Confirm back the task title, the resolved schedule, and the next run time.
</scheduling_capability>
`.trim()
