export interface IntegrationRunbook {
    id: string
    label: string
    relativePath: string
    description: string
    defaultContent: string
}

export const INTEGRATION_INDEX_PATH = 'INTEGRATIONS.md'

export const INTEGRATION_INDEX_DEFAULT_CONTENT = [
    '# INTEGRATIONS',
    '',
    'Integration runbooks are operational guides for agents. Use them when the user asks to configure, repair, verify, or operate an external service integration.',
    '',
    'Rules:',
    '- Do not send the user to Settings when a runbook plus available tools can advance the setup.',
    '- Ask only for missing credentials, consent, account choices, or risk-bearing decisions.',
    '- Store secrets only in .env.local or another configured secret surface. Never echo secret values back.',
    '- Prefer reversible setup and verification steps before asking for user action.',
    '- Stop before external sends, account changes, payments, bookings, uploads of sensitive documents, or broad permission grants unless the user confirms the exact action.',
    '',
    'Available runbooks:',
    '- gmail: INTEGRATIONS/gmail.md',
    '- google-calendar: INTEGRATIONS/google-calendar.md',
    '- google-workspace: INTEGRATIONS/google-workspace.md',
    '- whatsapp: INTEGRATIONS/whatsapp.md',
    '- home-assistant: INTEGRATIONS/home-assistant.md',
    '',
].join('\n')

export const INTEGRATION_RUNBOOKS: IntegrationRunbook[] = [
    {
        id: 'gmail',
        label: 'Gmail runbook',
        relativePath: 'INTEGRATIONS/gmail.md',
        description: 'Agent setup and operating guide for Gmail OAuth, mailbox reads, and unsent draft creation.',
        defaultContent: [
            '# Gmail Integration Runbook',
            '',
            'Use this runbook when the user asks to connect, configure, repair, or verify Gmail.',
            '',
            '## Capability',
            '',
            '- Search Gmail messages.',
            '- Read relevant Gmail threads.',
            '- Create unsent Gmail drafts for user review.',
            '- Never send email from this integration.',
            '',
            '## Implementation Surface',
            '',
            'Workspace env vars:',
            '- `GOOGLE_OAUTH_CLIENT_ID`',
            '- `GOOGLE_OAUTH_CLIENT_SECRET`',
            '- `GMAIL_OAUTH_REDIRECT_URI` optional; defaults to a Google-compatible callback: `<app_origin>/api/integrations/gmail/oauth/callback` only when app_origin is localhost or public HTTPS, otherwise `http://localhost:3000/api/integrations/gmail/oauth/callback` for SSH-tunnel setup.',
            '',
            'Local API endpoints:',
            '- `GET <app_origin>/api/integrations/status`',
            '- `PUT <app_origin>/api/integrations/gmail/config` with JSON body `{ "rawEnv": "...", "clientId": "...", "clientSecret": "...", "redirectUri": "..." }`',
            '- `POST <app_origin>/api/integrations/gmail/oauth/start`',
            '- `GET <app_origin>/api/integrations/gmail/oauth/callback` is handled by the app after Google redirects back.',
            '',
            'Runtime tools:',
            '- Prefer `SetEnv` for individual env values when the user gives them directly.',
            '- Prefer the config API when the user gives Google OAuth JSON or pasted env lines, because it validates and normalizes the Gmail-specific keys.',
            '- Use `Bash` with `curl` for local API calls when no direct HTTP POST tool is available, but use `<app_origin>` exactly; never use `0.0.0.0` in OAuth/status URLs.',
            '',
            '## Setup Flow',
            '',
            '1. Check status first.',
            '   - Call `GET <app_origin>/api/integrations/status` when `app_origin` is present in runtime context.',
            '   - If the local API is unreachable, inspect the runtime/server URL if available; otherwise explain that the app origin is missing and ask only for the reachable Orchestrator URL.',
            '',
            '2. If OAuth config is missing, ask for exactly one of:',
            '   - Google OAuth client JSON downloaded from Google Cloud for a Web application.',
            '   - Env lines containing `GOOGLE_OAUTH_CLIENT_ID` and `GOOGLE_OAUTH_CLIENT_SECRET`.',
            '   - Separate client ID and client secret values.',
            '',
            '3. If the user has not created a Google OAuth client yet, give step-by-step Google Cloud instructions with links:',
            '   - Open the Google Cloud project selector and choose or create the project that should own this integration: https://console.cloud.google.com/projectselector2/home/dashboard.',
            '   - Enable Gmail API before trying OAuth: https://console.cloud.google.com/flows/enableapi?apiid=gmail.googleapis.com. CLI alternative: `gcloud services enable gmail.googleapis.com`.',
            '   - Configure the Google Auth platform consent screen: https://console.cloud.google.com/auth/branding. If the app is External/testing, open Audience and add the user email as a test user: https://console.cloud.google.com/auth/audience.',
            '   - Create a Web application OAuth client in Google Auth platform > Clients: https://console.cloud.google.com/auth/clients.',
            '   - Under Authorized redirect URIs, add exactly the redirect URI reported by the status/config endpoint. Do not invent this from `<app_origin>` when it is `.lan`, `.local`, or a private IP; Google rejects those. Explain that scheme, host, path, and trailing slash must match or Google returns `redirect_uri_mismatch`.',
            '   - Download the OAuth client JSON or copy the client ID and client secret. Tell the user to paste the JSON or env lines here, not screenshots.',
            '   - Use official references if Google changes labels: https://developers.google.com/workspace/guides/enable-apis, https://developers.google.com/workspace/guides/configure-oauth-consent, https://developers.google.com/workspace/guides/create-credentials.',
            '',
            '4. Save config.',
            '   - Never repeat the secret value in chat.',
            '   - For pasted env lines or Google OAuth JSON, call `PUT <app_origin>/api/integrations/gmail/config` with `rawEnv` set to the raw text.',
            '   - For separate values, call the same endpoint with `clientId`, `clientSecret`, and optional `redirectUri`, or use `SetEnv` for each key.',
            '',
            '5. Start OAuth.',
            '   - Call `POST <app_origin>/api/integrations/gmail/oauth/start`.',
            '   - Give the returned `authUrl` to the user and ask them to approve the Google consent screen.',
            '   - If the returned redirect URI is localhost and the app process is on the same machine as the user browser, no tunnel is needed. If the app is on a different headless server and the user is browsing through `.lan`, `.local`, or an IP, do not continue from that page; use `runtime.sshHostCandidates` from status or runtime_context rather than a hardcoded IP, start a tunnel such as `ssh -N -L <local_port>:127.0.0.1:<remote_port> <user>@<ssh_host>` when shell access on the browser machine is available, otherwise give that exact command and ask the user to open `http://localhost:<local_port>/settings` before clicking Connect.',
            '   - Tell the user to keep the SSH tunnel terminal open until Google redirects back and status says Connected. After status is Connected, tell them to stop the tunnel with Ctrl+C.',
            '   - Start only this one OAuth flow and verify it before starting another Google integration.',
            '   - Make clear this is a human-required consent step. Do not claim it is connected until status confirms it.',
            '',
            '6. Verify after consent.',
            '   - Recheck `GET <app_origin>/api/integrations/status`.',
            '   - Success means `gmail.connected` is true and `gmail.needsReconnect` is false.',
            '   - Report the connected account email and scopes in plain language.',
            '',
            '## Operating Flow After Setup',
            '',
            '- For inbox triage, search first, then read only relevant threads.',
            '- Minimize private content exposure in summaries.',
            '- Create drafts only when the user asks for a draft or explicitly approves draft creation.',
            '- Always say drafts are unsent.',
            '- Do not send, archive, delete, label, or mark messages handled unless a future tool explicitly supports that and the user confirms the exact action.',
            '',
            '## Failure Handling',
            '',
            '- Missing config: ask for the smallest missing credential package.',
            '- Missing scope or refresh token: start OAuth again and ask the user to approve consent.',
            '- Redirect URI mismatch: tell the user the exact redirect URI to add in Google Cloud and restart OAuth after they update it.',
            '- Local API unreachable: report the attempted URL and ask for the reachable Orchestrator app URL or start the local app if appropriate.',
            '',
        ].join('\n'),
    },
    {
        id: 'google-calendar',
        label: 'Google Calendar runbook',
        relativePath: 'INTEGRATIONS/google-calendar.md',
        description: 'Agent setup and operating guide for Google Calendar OAuth, availability reads, event writes, and RSVP handling.',
        defaultContent: [
            '# Google Calendar Integration Runbook',
            '',
            'Use this runbook when the user asks to connect, configure, repair, verify, inspect, schedule, reschedule, cancel, move, or RSVP through Google Calendar.',
            '',
            '## Capability',
            '',
            '- Reuse Google OAuth client config for Calendar and future Google Workspace integrations.',
            '- Read calendar list, events, event details, free/busy blocks, and available time slots.',
            '- Create, update, delete, move, and RSVP to events only after explicit user approval.',
            '- Support attendees, optional attendees, Google Meet links, recurrence rules, reminders, visibility, busy/free transparency, and notification behavior.',
            '',
            '## Implementation Surface',
            '',
            'Workspace env vars:',
            '- `GOOGLE_OAUTH_CLIENT_ID`',
            '- `GOOGLE_OAUTH_CLIENT_SECRET`',
            '- `GOOGLE_WORKSPACE_OAUTH_REDIRECT_URI` optional; defaults to a Google-compatible callback: `<app_origin>/api/integrations/google/oauth/callback` only when app_origin is localhost or public HTTPS, otherwise `http://localhost:3000/api/integrations/google/oauth/callback` for SSH-tunnel setup.',
            '',
            'Local API endpoints:',
            '- `GET <app_origin>/api/integrations/status`',
            '- `PUT <app_origin>/api/integrations/google-calendar/config` with JSON body `{ "rawEnv": "...", "clientId": "...", "clientSecret": "...", "redirectUri": "..." }`',
            '- `POST <app_origin>/api/integrations/google-calendar/oauth/start`',
            '- `GET <app_origin>/api/integrations/google/oauth/callback` is handled by the app after Google redirects back.',
            '- `POST <app_origin>/api/integrations/google-calendar/disconnect` revokes and removes local Calendar tokens.',
            '',
            'Runtime setup tools:',
            '- `GoogleCalendarStatus` checks config, connection, scopes, primary calendar, and writable calendar count.',
            '- `GoogleCalendarConfigure` saves reusable Google OAuth config. Never echo client secrets.',
            '- `GoogleCalendarStartOAuth` returns the Google consent URL. The user must approve consent.',
            '',
            'Runtime read tools:',
            '- `GoogleCalendarListCalendars`',
            '- `GoogleCalendarListEvents`',
            '- `GoogleCalendarGetEvent`',
            '- `GoogleCalendarSearchEvents`',
            '- `GoogleCalendarFreeBusy`',
            '- `GoogleCalendarFindAvailability`',
            '',
            'Runtime write tools requiring explicit confirmation:',
            '- `GoogleCalendarCreateEvent`',
            '- `GoogleCalendarUpdateEvent`',
            '- `GoogleCalendarDeleteEvent`',
            '- `GoogleCalendarRespondToEvent`',
            '- `GoogleCalendarMoveEvent`',
            '',
            '## Setup Flow',
            '',
            '1. Check status first with `GoogleCalendarStatus` or `GET <app_origin>/api/integrations/status`.',
            '',
            '2. If OAuth config is missing, ask for exactly one of:',
            '   - Google OAuth client JSON downloaded from Google Cloud for a Web application.',
            '   - Env lines containing `GOOGLE_OAUTH_CLIENT_ID` and `GOOGLE_OAUTH_CLIENT_SECRET`.',
            '   - Separate client ID and client secret values.',
            '',
            '3. If the user needs Google Cloud instructions, give the full setup path with links:',
            '   - Open the Google Cloud project selector and choose or create the project that should own this integration: https://console.cloud.google.com/projectselector2/home/dashboard.',
            '   - Enable Google Calendar API before trying OAuth: https://console.cloud.google.com/flows/enableapi?apiid=calendar-json.googleapis.com. CLI alternative: `gcloud services enable calendar-json.googleapis.com`.',
            '   - Configure the Google Auth platform consent screen: https://console.cloud.google.com/auth/branding. If the app is External/testing, open Audience and add the user email as a test user: https://console.cloud.google.com/auth/audience.',
            '   - Create or reuse a Web application OAuth client in Google Auth platform > Clients: https://console.cloud.google.com/auth/clients.',
            '   - Under Authorized redirect URIs, add exactly the redirect URI reported by status/config. Do not invent this from `<app_origin>` when it is `.lan`, `.local`, or a private IP; Google rejects those. Explain that scheme, host, path, and trailing slash must match or Google returns `redirect_uri_mismatch`.',
            '   - Download the OAuth client JSON or copy the client ID and client secret. Tell the user to paste the JSON or env lines here, not screenshots.',
            '   - Use official references if Google changes labels: https://developers.google.com/workspace/guides/enable-apis, https://developers.google.com/workspace/guides/configure-oauth-consent, https://developers.google.com/workspace/guides/create-credentials.',
            '',
            '4. Save config.',
            '   - Never repeat the secret value in chat.',
            '   - Prefer `GoogleCalendarConfigure` for pasted env lines or Google OAuth JSON.',
            '   - For separate values, use `GoogleCalendarConfigure` with `client_id`, `client_secret`, and optional `redirect_uri`.',
            '',
            '5. Start OAuth.',
            '   - Call `GoogleCalendarStartOAuth`.',
            '   - Give the returned `authUrl` to the user and ask them to approve the Google consent screen.',
            '   - If the returned redirect URI is localhost and the app process is on the same machine as the user browser, no tunnel is needed. If the app is on a different headless server and the user is browsing through `.lan`, `.local`, or an IP, do not continue from that page; use `runtime.sshHostCandidates` from status or runtime_context rather than a hardcoded IP, start a tunnel such as `ssh -N -L <local_port>:127.0.0.1:<remote_port> <user>@<ssh_host>` when shell access on the browser machine is available, otherwise give that exact command and ask the user to open `http://localhost:<local_port>/settings` before clicking Connect.',
            '   - Tell the user to keep the SSH tunnel terminal open until Google redirects back and status says Connected. After status is Connected, tell them to stop the tunnel with Ctrl+C.',
            '   - Start only this one OAuth flow and verify it before starting another Google integration.',
            '   - Do not claim Calendar is connected until status confirms it.',
            '',
            '6. Verify after consent.',
            '   - Recheck `GoogleCalendarStatus` or `GET <app_origin>/api/integrations/status`.',
            '   - Success means `googleCalendar.connected` is true and `googleCalendar.needsReconnect` is false.',
            '   - Report connected account, primary calendar, timezone, calendar count, and writable calendar count.',
            '',
            '## Operating Flow After Setup',
            '',
            '- For schedule questions, resolve relative dates against runtime today and include timezone in tool arguments.',
            '- For availability, use `GoogleCalendarFreeBusy` or `GoogleCalendarFindAvailability`; prefer bounded windows.',
            '- For event search, use `GoogleCalendarSearchEvents` with a bounded time range when the user gives one.',
            '- For schedule summaries, list events from the relevant calendar and time window; minimize private details unrelated to the request.',
            '- For event creation, update, deletion, move, or RSVP, first show the exact calendar, title, start/end, timezone, attendees, recurrence/instance scope, Meet link behavior, and `send_updates` behavior.',
            '- Call write tools only after the user explicitly approves that exact action.',
            '- For recurring events, distinguish one occurrence from the whole series before writing.',
            '- Treat `send_updates` as external communication when attendees are present.',
            '- If iOS Calendar is involved, remind the user that events sync only when they are saved to the Google calendar, not iCloud or On My iPhone.',
            '',
            '## Failure Handling',
            '',
            '- Missing config: ask for the smallest missing credential package.',
            '- Missing scope or refresh token: start OAuth again and ask the user to approve consent.',
            '- Redirect URI mismatch: tell the user the exact redirect URI to add in Google Cloud and restart OAuth after they update it.',
            '- Calendar write failure: report the Google API error and do not retry a write with broader changes unless the user approves the corrected action.',
            '- Local API unreachable: report the attempted URL and ask for the reachable Orchestrator app URL or start the local app if appropriate.',
            '',
        ].join('\n'),
    },
    {
        id: 'google-workspace',
        label: 'Google Workspace runbook',
        relativePath: 'INTEGRATIONS/google-workspace.md',
        description: 'Agent setup and operating guide for Google Workspace OAuth, Drive files, Docs, Sheets, Slides, Contacts, exports, uploads, organization, and sharing.',
        defaultContent: [
            '# Google Workspace Integration Runbook',
            '',
            'Use this runbook when the user asks to connect, configure, repair, verify, search, read, export, download, upload, organize, delete, share, create, or edit Google Workspace data: Drive, Docs, Sheets, Slides, and Google Contacts.',
            '',
            '## Capability',
            '',
            '- Reuse Google Workspace OAuth client config for Drive, Calendar, Docs, Sheets, and Slides integrations.',
            '- Read Drive profile, storage quota, shared drives, file metadata, permissions, text-like files, and exported Google Docs/Sheets/Slides.',
            '- Create and edit native Google Docs with Docs API batch updates.',
            '- Create, read, update, append, clear, format, chart, and structurally modify native Google Sheets.',
            '- Create and edit native Google Slides decks with batch updates and thumbnail-based visual verification.',
            '- Read, search, create, update, delete, import, and group personal Google Contacts through People API after explicit approval for writes.',
            '- Read/search “Other contacts” and copy selected Other Contacts into My Contacts after explicit approval.',
            '- Download binary files and exported Workspace files to the agent workspace.',
            '- Upload local workspace files, replace Drive file content, create folders, create blank Google Docs/Sheets/Slides/Drawings/Forms, copy, move, rename/update metadata, trash, untrash, permanently delete, and change sharing permissions only after explicit user approval.',
            '',
            '## Implementation Surface',
            '',
            'Workspace env vars:',
            '- `GOOGLE_OAUTH_CLIENT_ID`',
            '- `GOOGLE_OAUTH_CLIENT_SECRET`',
            '- `GOOGLE_WORKSPACE_OAUTH_REDIRECT_URI` optional; defaults to a Google-compatible callback: `<app_origin>/api/integrations/google/oauth/callback` only when app_origin is localhost or public HTTPS, otherwise `http://localhost:3000/api/integrations/google/oauth/callback` for SSH-tunnel setup.',
            '',
            'Local API endpoints:',
            '- `GET <app_origin>/api/integrations/status`',
            '- `PUT <app_origin>/api/integrations/google-drive/config` with JSON body `{ "rawEnv": "...", "clientId": "...", "clientSecret": "...", "redirectUri": "..." }`',
            '- `POST <app_origin>/api/integrations/google-drive/oauth/start`',
            '- `GET <app_origin>/api/integrations/google/oauth/callback` is handled by the app after Google redirects back.',
            '- `POST <app_origin>/api/integrations/google-drive/disconnect` revokes and removes local Workspace tokens used by Drive, Docs, Sheets, Slides, and Contacts.',
            '',
            'Runtime setup tools:',
            '- `GoogleDriveStatus` checks config, connection, scopes, storage quota, and capabilities.',
            '- `GoogleDriveConfigure` saves reusable Google Workspace OAuth config. Never echo client secrets.',
            '- `GoogleDriveStartOAuth` returns the Google consent URL. The user must approve consent.',
            '',
            'Runtime read tools:',
            '- `GoogleDriveAbout`',
            '- `GoogleDriveListSharedDrives`',
            '- `GoogleDriveListFiles`',
            '- `GoogleDriveGetFile`',
            '- `GoogleDriveReadFile`',
            '- `GoogleDriveDownloadFile`',
            '- `GoogleDriveExportFile`',
            '- `GoogleDriveListPermissions`',
            '- `GoogleDocsGetDocument`',
            '- `GoogleSheetsGetSpreadsheet`, `GoogleSheetsGetValues`, `GoogleSheetsBatchGetValues`',
            '- `GoogleSlidesGetPresentation`, `GoogleSlidesGetPage`, `GoogleSlidesGetThumbnail`',
            '- `GoogleContactsListConnections`, `GoogleContactsSearchContacts`, `GoogleContactsGetPerson`, `GoogleContactsBatchGetPeople`',
            '- `GoogleContactsListContactGroups`, `GoogleContactsGetContactGroup`',
            '- `GoogleContactsListOtherContacts`, `GoogleContactsSearchOtherContacts`',
            '',
            'Runtime write/share tools requiring explicit confirmation:',
            '- `GoogleDriveUploadFile`',
            '- `GoogleDriveUpdateFileContent`',
            '- `GoogleDriveCreateFolder`',
            '- `GoogleDriveCreateGoogleFile`',
            '- `GoogleDriveUpdateMetadata`',
            '- `GoogleDriveMoveFile`',
            '- `GoogleDriveCopyFile`',
            '- `GoogleDriveTrashFile`',
            '- `GoogleDriveUntrashFile`',
            '- `GoogleDriveDeleteFile`',
            '- `GoogleDriveShareFile`',
            '- `GoogleDriveUpdatePermission`',
            '- `GoogleDriveDeletePermission`',
            '- `GoogleDocsCreateDocument`, `GoogleDocsInsertText`, `GoogleDocsReplaceAllText`, `GoogleDocsApplyTextStyle`, `GoogleDocsApplyParagraphStyle`, `GoogleDocsInsertTable`, `GoogleDocsBatchUpdate`',
            '- `GoogleSheetsCreateSpreadsheet`, `GoogleSheetsUpdateValues`, `GoogleSheetsAppendValues`, `GoogleSheetsClearValues`, `GoogleSheetsBatchUpdate`',
            '- `GoogleSlidesCreatePresentation`, `GoogleSlidesCreateSlide`, `GoogleSlidesInsertTextBox`, `GoogleSlidesReplaceAllText`, `GoogleSlidesBatchUpdate`',
            '- `GoogleContactsCreateContact`, `GoogleContactsBatchCreateContacts`, `GoogleContactsUpdateContact`, `GoogleContactsBatchUpdateContacts`, `GoogleContactsDeleteContact`, `GoogleContactsBatchDeleteContacts`',
            '- `GoogleContactsCreateContactGroup`, `GoogleContactsUpdateContactGroup`, `GoogleContactsDeleteContactGroup`, `GoogleContactsModifyContactGroupMembers`, `GoogleContactsCopyOtherContactToMyContacts`',
            '',
            '## Setup Flow',
            '',
            '1. Check status first with `GoogleDriveStatus` or `GET <app_origin>/api/integrations/status`.',
            '',
            '2. If OAuth config is missing, ask for exactly one of:',
            '   - Google OAuth client JSON downloaded from Google Cloud for a Web application.',
            '   - Env lines containing `GOOGLE_OAUTH_CLIENT_ID` and `GOOGLE_OAUTH_CLIENT_SECRET`.',
            '   - Separate client ID and client secret values.',
            '',
            '3. If the user needs Google Cloud instructions, give the full setup path with links:',
            '   - Open the Google Cloud project selector and choose or create the project that should own this integration: https://console.cloud.google.com/projectselector2/home/dashboard.',
            '   - Enable every Workspace API this integration uses before trying OAuth: Drive API https://console.cloud.google.com/flows/enableapi?apiid=drive.googleapis.com, Docs API https://console.cloud.google.com/flows/enableapi?apiid=docs.googleapis.com, Sheets API https://console.cloud.google.com/flows/enableapi?apiid=sheets.googleapis.com, Slides API https://console.cloud.google.com/flows/enableapi?apiid=slides.googleapis.com, and People API https://console.cloud.google.com/flows/enableapi?apiid=people.googleapis.com. CLI alternative: `gcloud services enable drive.googleapis.com docs.googleapis.com sheets.googleapis.com slides.googleapis.com people.googleapis.com`.',
            '   - Configure the Google Auth platform consent screen: https://console.cloud.google.com/auth/branding. If the app is External/testing, open Audience and add the user email as a test user: https://console.cloud.google.com/auth/audience.',
            '   - Create or reuse a Web application OAuth client in Google Auth platform > Clients: https://console.cloud.google.com/auth/clients.',
            '   - Under Authorized redirect URIs, add exactly the redirect URI reported by status/config. Do not invent this from `<app_origin>` when it is `.lan`, `.local`, or a private IP; Google rejects those. Explain that scheme, host, path, and trailing slash must match or Google returns `redirect_uri_mismatch`.',
            '   - Download the OAuth client JSON or copy the client ID and client secret. Tell the user to paste the JSON or env lines here, not screenshots.',
            '   - Use official references if Google changes labels: https://developers.google.com/workspace/guides/enable-apis, https://developers.google.com/workspace/guides/configure-oauth-consent, https://developers.google.com/workspace/guides/create-credentials, https://developers.google.com/workspace/drive/api/guides/api-specific-auth.',
            '',
            '4. Save config.',
            '   - Never repeat the secret value in chat.',
            '   - Prefer `GoogleDriveConfigure` for pasted env lines or Google OAuth JSON.',
            '   - For separate values, use `GoogleDriveConfigure` with `client_id`, `client_secret`, and optional `redirect_uri`.',
            '',
            '5. Start OAuth.',
            '   - Call `GoogleDriveStartOAuth`.',
            '   - Give the returned `authUrl` to the user and ask them to approve the Google consent screen.',
            '   - If the returned redirect URI is localhost and the app process is on the same machine as the user browser, no tunnel is needed. If the app is on a different headless server and the user is browsing through `.lan`, `.local`, or an IP, do not continue from that page; use `runtime.sshHostCandidates` from status or runtime_context rather than a hardcoded IP, start a tunnel such as `ssh -N -L <local_port>:127.0.0.1:<remote_port> <user>@<ssh_host>` when shell access on the browser machine is available, otherwise give that exact command and ask the user to open `http://localhost:<local_port>/settings` before clicking Connect.',
            '   - Tell the user to keep the SSH tunnel terminal open until Google redirects back and status says Connected. After status is Connected, tell them to stop the tunnel with Ctrl+C.',
            '   - Start only this one OAuth flow and verify it before starting another Google integration.',
            '   - Do not claim Google Workspace is connected until status confirms it.',
            '',
            '6. Verify after consent.',
            '   - Recheck `GoogleDriveStatus` or `GET <app_origin>/api/integrations/status`.',
            '   - Success means `googleDrive.connected` is true and `googleDrive.needsReconnect` is false.',
            '   - Report connected account, granted scopes, Workspace capabilities, and storage quota if available.',
            '',
            '## Operating Flow After Setup',
            '',
            '- For file lookup, search narrowly first: name, parent folder, MIME type, owner, shared state, modified window, or shared drive.',
            '- Read only files relevant to the user request. Use `GoogleDriveGetFile` for metadata before broad content reads.',
            '- Use `GoogleDriveReadFile` for text-like content and Google Workspace text exports.',
            '- Use `GoogleDriveExportFile` when the user needs a specific output format such as PDF, DOCX, XLSX, PPTX, CSV, or plain text.',
            '- Use `GoogleDriveDownloadFile` for binary non-Workspace files.',
            '- Summarize private document content minimally and avoid dumping full content unless the user explicitly asks for it.',
            '- Before uploading local files to Drive, replacing content, creating folders/files, moving/copying/renaming/trashing/untrashing/deleting files, or changing permissions, summarize the exact source, target, destination, file name, MIME/export format, permission principal, role, notification behavior, and reversibility.',
            '- Call write/share/delete tools only after the user explicitly approves that exact action.',
            '- Prefer Trash over permanent deletion unless the user explicitly confirms permanent deletion.',
            '- Prefer user/group sharing over domain or anyone links; treat owner transfer, public/domain links, and notification emails as high-risk access changes.',
            '- For Docs, read the document before edits, build a section skeleton, use headings/tables/styles intentionally, and re-read after writes.',
            '- For Sheets, read metadata and exact ranges first, preserve formulas/validation/protection unless approved, and verify edited ranges after writes.',
            '- For Slides, build the narrative first, use editable native elements, avoid clipped text/overlap, and verify every touched slide with `GoogleSlidesGetPage` plus `GoogleSlidesGetThumbnail`.',
            '- For Contacts, search/list first, read exact `people/*` resources before updates, preserve current etag/source metadata, and verify writes with readback.',
            '- Treat contact creates, edits, deletes, group membership changes, batch imports, and copying Other Contacts into My Contacts as synced personal-data changes that need exact confirmation.',
            '- For iOS Contacts questions, explain that Orchestrator sees contacts saved in/synced to Google Contacts, not contacts stored only in iCloud or On My iPhone.',
            '',
            '## Failure Handling',
            '',
            '- Missing config: ask for the smallest missing credential package.',
            '- Missing scope or refresh token: start OAuth again and ask the user to approve consent.',
            '- Redirect URI mismatch: tell the user the exact redirect URI to add in Google Cloud and restart OAuth after they update it.',
            '- Export failure: try a format supported by `GoogleDriveAbout.exportFormats` or ask which format the user wants.',
            '- Upload/download too large: report byte size and ask for a narrower file, lower limit, or approved large transfer path.',
            '- Permission failure: report the Google API error and do not retry with broader sharing unless the user approves the corrected action.',
            '- Local API unreachable: report the attempted URL and ask for the reachable Orchestrator app URL or start the local app if appropriate.',
            '',
        ].join('\n'),
    },
    {
        id: 'whatsapp',
        label: 'WhatsApp runbook',
        relativePath: 'INTEGRATIONS/whatsapp.md',
        description: 'Agent setup and operating guide for local WhatsApp Web QR login, reads, confirmed sends, media attachments, and delete-for-everyone.',
        defaultContent: [
            '# WhatsApp Integration Runbook',
            '',
            'Use this runbook when the user asks to connect, configure, repair, verify, read, send, attach files, attach photos, or delete WhatsApp messages.',
            '',
            '## Capability',
            '',
            '- Start a local WhatsApp Web session with the user scanning a QR code from their phone.',
            '- List recent WhatsApp chats.',
            '- Read recent messages from a selected chat.',
            '- Search recent message bodies across recent chats.',
            '- Send text messages only after the user explicitly approves the exact chat and exact message body.',
            '- Send workspace files/photos as WhatsApp media/documents only after the user explicitly approves the exact chat, files, and caption.',
            '- Delete messages only with `WhatsAppDeleteMessageForEveryone`; no delete-for-me mode is exposed.',
            '- Never archive, mute, pin, label, mark read, mark unread, or otherwise mutate WhatsApp state unless a dedicated confirmed tool is added.',
            '',
            '## Implementation Surface',
            '',
            'Local runtime:',
            '- Uses `whatsapp-web.js` and a local browser controlled by Puppeteer.',
            '- Uses `qrcode` to render QR codes.',
            '- Stores session data under private app state, not in markdown memory.',
            '- Optional env var: `WHATSAPP_CHROME_EXECUTABLE_PATH` when Chrome/Chromium cannot be auto-detected.',
            '',
            'Local API endpoints:',
            '- `GET <app_origin>/api/integrations/status`',
            '- `POST <app_origin>/api/integrations/whatsapp/start`',
            '- `GET <app_origin>/api/integrations/whatsapp/qr` returns the current QR PNG when available.',
            '- `POST <app_origin>/api/integrations/whatsapp/disconnect` removes the local session.',
            '',
            'Runtime tools:',
            '- `WhatsAppStatus` checks connection, QR, browser, and local-session state.',
            '- `WhatsAppConnect` starts the local WhatsApp Web session and returns `qrMarkdown` when the user must scan a QR.',
            '- `WhatsAppListChats` lists recent chats after connection.',
            '- `WhatsAppReadChat` reads recent messages from one chat.',
            '- `WhatsAppSearchMessages` scans recent messages; this is not full-history server-side search.',
            '- `WhatsAppSendMessage` sends a confirmed text message.',
            '- `WhatsAppSendMedia` sends confirmed workspace files/photos as media/documents.',
            '- `WhatsAppDeleteMessageForEveryone` deletes a confirmed exact message for everyone.',
            '',
            '## Setup Flow',
            '',
            '1. Check status first.',
            '   - Use `WhatsAppStatus` or `GET <app_origin>/api/integrations/status`.',
            '   - If `configured` is false, ask the user to install Chrome/Chromium or set `WHATSAPP_CHROME_EXECUTABLE_PATH` to the local executable path.',
            '',
            '2. Start QR login.',
            '   - Call `WhatsAppConnect`.',
            '   - If `qrMarkdown` is returned, show it directly to the user in the chat.',
            '   - Tell the user to open WhatsApp on their phone, go to Linked devices, choose Link a device, and scan the QR.',
            '   - Do not claim connection succeeded until status reports `whatsapp.connected` true.',
            '',
            '3. Verify after scanning.',
            '   - Recheck `WhatsAppStatus`.',
            '   - If status is `authenticated` or `starting`, wait and check again; do not restart the QR handshake while WhatsApp Web is still finishing login.',
            '   - Success means `connected` is true and phase is `ready`.',
            '   - Report the connected display name or phone number when available.',
            '',
            '## Operating Flow After Setup',
            '',
            '- For triage, list chats first, then read only chats relevant to the user request.',
            '- Minimize private content exposure in summaries.',
            '- Mention that search scans recent messages, not guaranteed full history.',
            '- Before sending a text message, show the exact destination and exact body; call `WhatsAppSendMessage` only after explicit user approval and set `confirmed_by_user` true.',
            '- Before sending photos/files, show the exact destination, workspace paths/filenames, whether they send as media or documents, and the caption; call `WhatsAppSendMedia` only after explicit user approval and set `confirmed_by_user` true.',
            '- Before deleting, show the exact message id and explain it will be deleted for everyone; call `WhatsAppDeleteMessageForEveryone` only after explicit user approval and set `confirmed_by_user` true.',
            '- Stop if the user asks to delete only for themselves; this implementation intentionally exposes delete-for-everyone only.',
            '- Stop if the user asks to archive, mark read, mute, pin, or otherwise change WhatsApp state; no such tool is exposed.',
            '',
            '## Failure Handling',
            '',
            '- No browser found: ask for a Chrome/Chromium path and store it in `WHATSAPP_CHROME_EXECUTABLE_PATH` with `SetEnv`.',
            '- QR expired while still unscanned: call `WhatsAppConnect` again or recheck status until a refreshed QR appears.',
            '- Auth failure: disconnect and start again.',
            '- Local API unreachable: report the attempted URL and ask for the reachable Orchestrator app URL or start the local app if appropriate.',
            '',
            '## Safety Notes',
            '',
            '- This is a local WhatsApp Web session for the user who scans the QR code.',
            '- Treat the QR as sensitive while it is valid.',
            '- Do not store QR contents in memory files.',
            '- Writes affect the user\'s real WhatsApp account. Never send or delete unless the user explicitly confirms the exact action in the current conversation.',
            '- Delete operations are delete-for-everyone only; do not offer delete-for-me.',
            '',
        ].join('\n'),
    },
    {
        id: 'home-assistant',
        label: 'Home Assistant runbook',
        relativePath: 'INTEGRATIONS/home-assistant.md',
        description: 'Agent setup and operating guide for read-only Home Assistant REST/WebSocket API access.',
        defaultContent: [
            '# Home Assistant Integration Runbook',
            '',
            'Use this runbook when the user asks to connect, configure, verify, inspect, summarize, or troubleshoot Home Assistant.',
            '',
            '## Capability',
            '',
            '- Save a Home Assistant base URL and long-lived access token locally.',
            '- Read API status, core config, events, services, states, entity state, history, logbook, error log, calendars, camera snapshots, templates, config checks, registries, automations, scripts, and scenes.',
            '- Use REST and whitelisted read-only WebSocket commands.',
            '- In action mode, directly control lights, covers, climate, and notify services when the user clearly asks.',
            '- In action mode, any other Home Assistant service may be called only after explicit user confirmation of the exact service, target, and data.',
            '- Never edit YAML/config files, access Samba/SSH/add-on filesystems, or bypass the Home Assistant API.',
            '',
            '## Implementation Surface',
            '',
            'Workspace env vars:',
            '- `HOME_ASSISTANT_URL` such as `http://homeassistant.local:8123` or `http://<ip>:8123`',
            '- `HOME_ASSISTANT_TOKEN` long-lived access token',
            '',
            'Local API endpoints:',
            '- `GET <app_origin>/api/integrations/status`',
            '- `PUT <app_origin>/api/integrations/home-assistant/config` with JSON body `{ "baseUrl": "...", "token": "...", "rawEnv": "..." }`',
            '- `POST <app_origin>/api/integrations/home-assistant/disconnect` removes local URL/token config.',
            '- `GET/PUT <app_origin>/api/integrations/home-assistant/action-policy` reads or updates local action mode policy.',
            '',
            'Runtime setup tool:',
            '- `HomeAssistantConfigure` saves URL/token or pasted env lines and verifies the API. Never echo token values.',
            '- `HomeAssistantStatus` checks configured, connected, version, entity count, service-domain count, and errors.',
            '',
            'Runtime read tools:',
            '- `HomeAssistantApiInfo`, `HomeAssistantGetConfig`',
            '- `HomeAssistantListStates`, `HomeAssistantGetState`, `HomeAssistantSearchEntities`',
            '- `HomeAssistantListServices`, `HomeAssistantListEvents`',
            '- `HomeAssistantHistory`, `HomeAssistantLogbook`, `HomeAssistantErrorLog`',
            '- `HomeAssistantListCalendars`, `HomeAssistantReadCalendar`',
            '- `HomeAssistantCameraSnapshot`',
            '- `HomeAssistantRenderTemplate`, `HomeAssistantCheckConfig`',
            '- `HomeAssistantWebSocketRead` for `get_config`, `get_states`, `get_services`, `get_panels`, `ping` only',
            '- `HomeAssistantListRegistries` best-effort areas/devices/entities/floors/labels read',
            '- `HomeAssistantListAutomations`, `HomeAssistantListScripts`, `HomeAssistantListScenes`, `HomeAssistantAutomationActivity`',
            '- `HomeAssistantReadAutomationConfig`, `HomeAssistantListAutomationConfigs` read exposed automation trigger/condition/action components.',
            '',
            'Runtime action tools:',
            '- `HomeAssistantPreviewAction` validates a service call without executing it.',
            '- `HomeAssistantSetLight` controls `light.*` with brightness, color, color temperature, effect, transition, turn on/off, and toggle.',
            '- `HomeAssistantSetCover` controls `cover.*` open, close, stop, toggle, position, and tilt position.',
            '- `HomeAssistantSetClimate` controls `climate.*` HVAC mode, temperature, preset, fan, humidity, and swing mode.',
            '- `HomeAssistantNotify` sends through `notify.*` services.',
            '- `HomeAssistantCallService` is the generic service caller. For domains outside light/cover/climate/notify, use it only after explicit user confirmation and set `confirmed: true`.',
            '- `HomeAssistantReadActionAudit` reads recent local action audit entries.',
            '',
            '## Setup Flow',
            '',
            '1. Check status first with `HomeAssistantStatus` or `GET <app_origin>/api/integrations/status`.',
            '',
            '2. If config is missing, ask for exactly:',
            '   - Home Assistant URL.',
            '   - Long-lived access token from the user profile page.',
            '   - Or pasted env lines containing `HOME_ASSISTANT_URL` and `HOME_ASSISTANT_TOKEN`.',
            '',
            '3. If the user needs token instructions:',
            '   - Open Home Assistant.',
            '   - Click the user profile.',
            '   - Scroll to Long-lived access tokens.',
            '   - Create a token named Orchestrator.',
            '   - Paste it once. Do not ask for Samba, SSH, YAML, or add-on filesystem access.',
            '',
            '4. Save config with `HomeAssistantConfigure` or the local config API.',
            '   - Never repeat the token in chat.',
            '   - Verification success means `homeAssistant.connected` is true and `needsReconnect` is false.',
            '   - If verification fails, report the exact network/auth error and ask only for the corrected URL/token or network route.',
            '',
            '## Operating Flow After Setup',
            '',
            '- For smart-home summaries, start with `HomeAssistantListStates` using domain/query filters, then inspect exact entities with `HomeAssistantGetState`.',
            '- For automations, use `HomeAssistantListAutomations` and `HomeAssistantAutomationActivity` before drawing conclusions.',
            '- For automation structure, use `HomeAssistantReadAutomationConfig` or `HomeAssistantListAutomationConfigs`. Some YAML/unexposed automations may return 404 even though their entities exist.',
            '- For scenes/scripts, use their dedicated list tools and service schemas first; call scripts/scenes only after explicit user confirmation via `HomeAssistantCallService`.',
            '- For direct light/cover/climate/notify requests, use the dedicated action tool, then report before/after state and audit id.',
            '- For all other service calls, first say exactly: service domain/name, target entity/device/area, data payload, and expected effect; ask for confirmation; call with `confirmed: true` only after the user confirms.',
            '- For trends, use `HomeAssistantHistory` with explicit entity IDs and bounded time ranges.',
            '- For recent events, use `HomeAssistantLogbook` with entity and time filters.',
            '- For visual checks, use `HomeAssistantCameraSnapshot` only when the user request makes camera access relevant.',
            '- Minimize sensitive home data in summaries; include only what is useful for the request.',
            '',
            '## Failure Handling',
            '',
            '- Missing config: ask for URL and token only.',
            '- 401/403: token is missing, expired, copied incorrectly, or lacks permissions; ask for a fresh long-lived token.',
            '- Network failure: verify scheme, port 8123, hostname/IP, local network/VPN, firewall, and whether Orchestrator runs where Home Assistant is reachable.',
            '- WebSocket registry read failures can be permission/version/support differences. Fall back to REST states/config/services when possible.',
            '- Large history/logbook output: narrow entity IDs and time ranges instead of fetching everything.',
            '',
            '## Safety Notes',
            '',
            '- Read tools are available for all Home Assistant state and metadata exposed by the API.',
            '- Action mode is enabled/disabled by local policy.',
            '- `HomeAssistantConfigure` and disconnect only mutate local Orchestrator config.',
            '- Direct action domains are light, cover, climate, and notify.',
            '- All other domains require explicit confirmation in the current conversation before calling `HomeAssistantCallService` with `confirmed: true`.',
            '- Do not edit YAML/config files, use Samba/SSH, or bypass Home Assistant permissions.',
            '',
        ].join('\n'),
    },
]

export function buildIntegrationRunbooksContext(): string {
    const lines = INTEGRATION_RUNBOOKS.map(runbook =>
        `- ${runbook.id}: ${runbook.relativePath} - ${runbook.description}`
    )

    return [
        '<integration_runbooks>',
        'Service-specific setup guides are available in the workspace. When the user asks to configure, connect, repair, or verify an integration, follow the relevant runbook end-to-end instead of defaulting to UI instructions.',
        'Keep context bounded: do not read every runbook. Read only the specific runbook for the service you are about to configure or operate.',
        `Index: ${INTEGRATION_INDEX_PATH}`,
        'Available runbooks:',
        ...lines,
        '</integration_runbooks>',
    ].join('\n')
}
