export interface IntegrationRunbook {
  id: string
  label: string
  relativePath: string
  description: string
  defaultContent: string
}

export const INTEGRATION_INDEX_PATH = "INTEGRATIONS.md"

export const INTEGRATION_INDEX_DEFAULT_CONTENT = [
  "# INTEGRATIONS",
  "",
  "Integration runbooks are operational guides for agents. Use them when the user asks to configure, repair, verify, or operate an external service integration.",
  "",
  "Rules:",
  "- Do not send the user to Settings when a runbook plus available tools can advance the setup.",
  "- Ask only for missing credentials, consent, account choices, or risk-bearing decisions.",
  "- Store secrets only in .env.local or another configured secret surface. Never echo secret values back.",
  "- Prefer reversible setup and verification steps before asking for user action.",
  "- Stop before external sends, account changes, payments, bookings, uploads of sensitive documents, or broad permission grants unless the user confirms the exact action.",
  "",
  "Available runbooks:",
  "- gmail: INTEGRATIONS/gmail.md",
  "- google-calendar: INTEGRATIONS/google-calendar.md",
  "- google-workspace: INTEGRATIONS/google-workspace.md",
  "- whatsapp: INTEGRATIONS/whatsapp.md",
  "- home-assistant: INTEGRATIONS/home-assistant.md",
  "- maps: INTEGRATIONS/maps.md",
  "- weather: INTEGRATIONS/weather.md",
  "- location-intelligence: INTEGRATIONS/location-intelligence.md",
  "",
].join("\n")

export const INTEGRATION_RUNBOOKS: IntegrationRunbook[] = [
  {
    id: "gmail",
    label: "Gmail runbook",
    relativePath: "INTEGRATIONS/gmail.md",
    description:
      "Agent setup and operating guide for Gmail OAuth, mailbox reads, and unsent draft creation.",
    defaultContent: [
      "# Gmail Integration Runbook",
      "",
      "Use this runbook when the user asks to connect, configure, repair, or verify Gmail.",
      "",
      "## Capability",
      "",
      "Read-only context:",
      "- Search Gmail messages (`GmailSearch`) and read relevant threads (`GmailReadThread`).",
      "- Download an attachment from a message into the workspace (`GmailDownloadAttachment`).",
      "- Inspect a sender's List-Unsubscribe options without acting (`GmailUnsubscribeInfo`).",
      "",
      "Drafts and sending (sends need explicit user approval; `confirmed_by_user` only after that):",
      "- Create unsent drafts for review (`GmailCreateDraft`), optionally with workspace-file attachments.",
      "- Send a confirmed draft (`GmailSendDraft`) or compose-and-send a confirmed email (`GmailSendEmail`).",
      "",
      "Mailbox state changes (only when the user requested/approved that exact action):",
      "- Archive (`GmailArchive`), mark read/unread (`GmailMarkRead`/`GmailMarkUnread`), add/remove labels (`GmailModifyLabels`), move to/from Trash (`GmailTrash`/`GmailUntrash`).",
      "- List and create labels (`GmailListLabels`/`GmailCreateLabel`).",
      "- Permanently delete (`GmailDeletePermanently`) — irreversible, needs `confirm_permanent_delete`.",
      "- Unsubscribe a user from a sender (`GmailUnsubscribe`) — needs `confirmed_by_user`; check `GmailUnsubscribeInfo` first.",
      "- The archive/mark/label/trash/delete tools accept an `ids` array to act on many messages/threads in one batch call.",
      "",
      "## Implementation Surface",
      "",
      "Workspace env vars:",
      "- `GOOGLE_OAUTH_CLIENT_ID`",
      "- `GOOGLE_OAUTH_CLIENT_SECRET`",
      "- `GMAIL_OAUTH_REDIRECT_URI` optional; defaults to a Google-compatible callback: `<app_origin>/api/integrations/gmail/oauth/callback` only when app_origin is localhost or public HTTPS, otherwise `http://localhost:3000/api/integrations/gmail/oauth/callback` for SSH-tunnel setup.",
      "",
      "Local API endpoints:",
      "- `GET <app_origin>/api/integrations/status`",
      '- `PUT <app_origin>/api/integrations/gmail/config` with JSON body `{ "rawEnv": "...", "clientId": "...", "clientSecret": "...", "redirectUri": "..." }`',
      "- `POST <app_origin>/api/integrations/gmail/oauth/start`",
      "- `GET <app_origin>/api/integrations/gmail/oauth/callback` is handled by the app after Google redirects back.",
      "",
      "Runtime tools:",
      "- Prefer `SetEnv` for individual env values when the user gives them directly.",
      "- Prefer the config API when the user gives Google OAuth JSON or pasted env lines, because it validates and normalizes the Gmail-specific keys.",
      "- Use `Bash` with `curl` for local API calls when no direct HTTP POST tool is available, but use `<app_origin>` exactly; never use `0.0.0.0` in OAuth/status URLs.",
      "",
      "## Setup Flow",
      "",
      "1. Check status first.",
      "   - Call `GET <app_origin>/api/integrations/status` when `app_origin` is present in runtime context.",
      "   - If the local API is unreachable, inspect the runtime/server URL if available; otherwise explain that the app origin is missing and ask only for the reachable Orchestrator URL.",
      "",
      "2. If OAuth config is missing, ask for exactly one of:",
      "   - Google OAuth client JSON downloaded from Google Cloud for a Web application.",
      "   - Env lines containing `GOOGLE_OAUTH_CLIENT_ID` and `GOOGLE_OAUTH_CLIENT_SECRET`.",
      "   - Separate client ID and client secret values.",
      "",
      "3. If the user has not created a Google OAuth client yet, give step-by-step Google Cloud instructions with links:",
      "   - Open the Google Cloud project selector and choose or create the project that should own this integration: https://console.cloud.google.com/projectselector2/home/dashboard.",
      "   - Enable Gmail API before trying OAuth: https://console.cloud.google.com/flows/enableapi?apiid=gmail.googleapis.com. CLI alternative: `gcloud services enable gmail.googleapis.com`.",
      "   - Configure the Google Auth platform consent screen: https://console.cloud.google.com/auth/branding. If the app is External/testing, open Audience and add the user email as a test user: https://console.cloud.google.com/auth/audience.",
      "   - Create a Web application OAuth client in Google Auth platform > Clients: https://console.cloud.google.com/auth/clients.",
      "   - Under Authorized redirect URIs, add exactly the redirect URI reported by the status/config endpoint. Do not invent this from `<app_origin>` when it is `.lan`, `.local`, or a private IP; Google rejects those. Explain that scheme, host, path, and trailing slash must match or Google returns `redirect_uri_mismatch`.",
      "   - Download the OAuth client JSON or copy the client ID and client secret. Tell the user to paste the JSON or env lines here, not screenshots.",
      "   - Use official references if Google changes labels: https://developers.google.com/workspace/guides/enable-apis, https://developers.google.com/workspace/guides/configure-oauth-consent, https://developers.google.com/workspace/guides/create-credentials.",
      "",
      "4. Save config.",
      "   - Never repeat the secret value in chat.",
      "   - For pasted env lines or Google OAuth JSON, call `PUT <app_origin>/api/integrations/gmail/config` with `rawEnv` set to the raw text.",
      "   - For separate values, call the same endpoint with `clientId`, `clientSecret`, and optional `redirectUri`, or use `SetEnv` for each key.",
      "",
      "5. Start OAuth.",
      "   - Call `POST <app_origin>/api/integrations/gmail/oauth/start`.",
      "   - Give the returned `authUrl` to the user and ask them to approve the Google consent screen.",
      "   - If the returned redirect URI is localhost and the app process is on the same machine as the user browser, no tunnel is needed. If the app is on a different headless server and the user is browsing through `.lan`, `.local`, or an IP, do not continue from that page; use `runtime.sshHostCandidates` from status or runtime_context rather than a hardcoded IP, start a tunnel such as `ssh -N -L <local_port>:127.0.0.1:<remote_port> <user>@<ssh_host>` when shell access on the browser machine is available, otherwise give that exact command and ask the user to open `http://localhost:<local_port>/settings` before clicking Connect.",
      "   - Tell the user to keep the SSH tunnel terminal open until Google redirects back and status says Connected. After status is Connected, tell them to stop the tunnel with Ctrl+C.",
      "   - Start only this one OAuth flow and verify it before starting another Google integration.",
      "   - Make clear this is a human-required consent step. Do not claim it is connected until status confirms it.",
      "",
      "6. Verify after consent.",
      "   - Recheck `GET <app_origin>/api/integrations/status`.",
      "   - Success means `gmail.connected` is true and `gmail.needsReconnect` is false.",
      "   - Report the connected account email and scopes in plain language.",
      "",
      "## Operating Flow After Setup",
      "",
      "- For inbox triage, search first, then read only relevant threads.",
      "- Minimize private content exposure in summaries.",
      "- Create drafts only when the user asks for a draft or explicitly approves draft creation.",
      "- Always say drafts are unsent.",
      "- Send/archive/mark/label/trash/delete tools exist; call them only after the user confirms the exact action.",
      "- Acting on MANY messages/threads at once: pass `ids` (array) to GmailArchive/GmailMarkRead/GmailMarkUnread/GmailModifyLabels/GmailTrash/GmailUntrash/GmailDeletePermanently for ONE batch call instead of one call per id (all ids must share `target_type`; messages use Gmail's native batchModify endpoint, threads loop). One confirmation covers the batch; the tool returns a per-item succeeded/failed summary, so report failures rather than assuming all-or-nothing.",
      "",
      "## Failure Handling",
      "",
      "- Missing config: ask for the smallest missing credential package.",
      "- Missing scope or refresh token: start OAuth again and ask the user to approve consent.",
      "- Redirect URI mismatch: tell the user the exact redirect URI to add in Google Cloud and restart OAuth after they update it.",
      "- Local API unreachable: report the attempted URL and ask for the reachable Orchestrator app URL or start the local app if appropriate.",
      "",
    ].join("\n"),
  },
  {
    id: "google-calendar",
    label: "Google Calendar runbook",
    relativePath: "INTEGRATIONS/google-calendar.md",
    description:
      "Agent setup and operating guide for Google Calendar OAuth, availability reads, event writes, and RSVP handling.",
    defaultContent: [
      "# Google Calendar Integration Runbook",
      "",
      "Use this runbook when the user asks to connect, configure, repair, verify, inspect, schedule, reschedule, cancel, move, or RSVP through Google Calendar.",
      "",
      "## Capability",
      "",
      "- Reuse Google OAuth client config for Calendar and future Google Workspace integrations.",
      "- Read calendar list, events, event details, free/busy blocks, and available time slots.",
      "- Create, update, delete, move, and RSVP to events only after explicit user approval.",
      "- Support attendees, optional attendees, Google Meet links, recurrence rules, reminders, visibility, busy/free transparency, and notification behavior.",
      "",
      "## Implementation Surface",
      "",
      "Workspace env vars:",
      "- `GOOGLE_OAUTH_CLIENT_ID`",
      "- `GOOGLE_OAUTH_CLIENT_SECRET`",
      "- `GOOGLE_WORKSPACE_OAUTH_REDIRECT_URI` optional; defaults to a Google-compatible callback: `<app_origin>/api/integrations/google/oauth/callback` only when app_origin is localhost or public HTTPS, otherwise `http://localhost:3000/api/integrations/google/oauth/callback` for SSH-tunnel setup.",
      "",
      "Local API endpoints:",
      "- `GET <app_origin>/api/integrations/status`",
      '- `PUT <app_origin>/api/integrations/google-calendar/config` with JSON body `{ "rawEnv": "...", "clientId": "...", "clientSecret": "...", "redirectUri": "..." }`',
      "- `POST <app_origin>/api/integrations/google-calendar/oauth/start`",
      "- `GET <app_origin>/api/integrations/google/oauth/callback` is handled by the app after Google redirects back.",
      "- `POST <app_origin>/api/integrations/google-calendar/disconnect` revokes and removes local Calendar tokens.",
      "",
      "Runtime setup tools:",
      "- `GoogleCalendarStatus` checks config, connection, scopes, primary calendar, and writable calendar count.",
      "- `GoogleCalendarConfigure` saves reusable Google OAuth config. Never echo client secrets.",
      "- `GoogleCalendarStartOAuth` returns the Google consent URL. The user must approve consent.",
      "",
      "Runtime read tools:",
      "- `GoogleCalendarListCalendars`",
      "- `GoogleCalendarListEvents`",
      "- `GoogleCalendarGetEvent`",
      "- `GoogleCalendarSearchEvents`",
      "- `GoogleCalendarFreeBusy`",
      "- `GoogleCalendarFindAvailability`",
      "",
      "Runtime write tools requiring explicit confirmation:",
      "- `GoogleCalendarCreateEvent`",
      "- `GoogleCalendarUpdateEvent`",
      "- `GoogleCalendarDeleteEvent`",
      "- `GoogleCalendarRespondToEvent`",
      "- `GoogleCalendarMoveEvent`",
      "",
      "## Setup Flow",
      "",
      "1. Check status first with `GoogleCalendarStatus` or `GET <app_origin>/api/integrations/status`.",
      "",
      "2. If OAuth config is missing, ask for exactly one of:",
      "   - Google OAuth client JSON downloaded from Google Cloud for a Web application.",
      "   - Env lines containing `GOOGLE_OAUTH_CLIENT_ID` and `GOOGLE_OAUTH_CLIENT_SECRET`.",
      "   - Separate client ID and client secret values.",
      "",
      "3. If the user needs Google Cloud instructions, give the full setup path with links:",
      "   - Open the Google Cloud project selector and choose or create the project that should own this integration: https://console.cloud.google.com/projectselector2/home/dashboard.",
      "   - Enable Google Calendar API before trying OAuth: https://console.cloud.google.com/flows/enableapi?apiid=calendar-json.googleapis.com. CLI alternative: `gcloud services enable calendar-json.googleapis.com`.",
      "   - Configure the Google Auth platform consent screen: https://console.cloud.google.com/auth/branding. If the app is External/testing, open Audience and add the user email as a test user: https://console.cloud.google.com/auth/audience.",
      "   - Create or reuse a Web application OAuth client in Google Auth platform > Clients: https://console.cloud.google.com/auth/clients.",
      "   - Under Authorized redirect URIs, add exactly the redirect URI reported by status/config. Do not invent this from `<app_origin>` when it is `.lan`, `.local`, or a private IP; Google rejects those. Explain that scheme, host, path, and trailing slash must match or Google returns `redirect_uri_mismatch`.",
      "   - Download the OAuth client JSON or copy the client ID and client secret. Tell the user to paste the JSON or env lines here, not screenshots.",
      "   - Use official references if Google changes labels: https://developers.google.com/workspace/guides/enable-apis, https://developers.google.com/workspace/guides/configure-oauth-consent, https://developers.google.com/workspace/guides/create-credentials.",
      "",
      "4. Save config.",
      "   - Never repeat the secret value in chat.",
      "   - Prefer `GoogleCalendarConfigure` for pasted env lines or Google OAuth JSON.",
      "   - For separate values, use `GoogleCalendarConfigure` with `client_id`, `client_secret`, and optional `redirect_uri`.",
      "",
      "5. Start OAuth.",
      "   - Call `GoogleCalendarStartOAuth`.",
      "   - Give the returned `authUrl` to the user and ask them to approve the Google consent screen.",
      "   - If the returned redirect URI is localhost and the app process is on the same machine as the user browser, no tunnel is needed. If the app is on a different headless server and the user is browsing through `.lan`, `.local`, or an IP, do not continue from that page; use `runtime.sshHostCandidates` from status or runtime_context rather than a hardcoded IP, start a tunnel such as `ssh -N -L <local_port>:127.0.0.1:<remote_port> <user>@<ssh_host>` when shell access on the browser machine is available, otherwise give that exact command and ask the user to open `http://localhost:<local_port>/settings` before clicking Connect.",
      "   - Tell the user to keep the SSH tunnel terminal open until Google redirects back and status says Connected. After status is Connected, tell them to stop the tunnel with Ctrl+C.",
      "   - Start only this one OAuth flow and verify it before starting another Google integration.",
      "   - Do not claim Calendar is connected until status confirms it.",
      "",
      "6. Verify after consent.",
      "   - Recheck `GoogleCalendarStatus` or `GET <app_origin>/api/integrations/status`.",
      "   - Success means `googleCalendar.connected` is true and `googleCalendar.needsReconnect` is false.",
      "   - Report connected account, primary calendar, timezone, calendar count, and writable calendar count.",
      "",
      "## Operating Flow After Setup",
      "",
      "- For schedule questions, resolve relative dates against runtime today and include timezone in tool arguments.",
      "- For availability, use `GoogleCalendarFreeBusy` or `GoogleCalendarFindAvailability`; prefer bounded windows.",
      "- For event search, use `GoogleCalendarSearchEvents` with a bounded time range when the user gives one.",
      "- For schedule summaries, list events from the relevant calendar and time window; minimize private details unrelated to the request.",
      "- For silent-until-noteworthy calendar monitoring, use Smart Monitor source `google_calendar` after the user confirms what should count as important. Common rules include onboarding/deadline keywords, RSVP-needed invites, specific attendees/locations, and starts-soon windows.",
      "- For event creation, update, deletion, move, or RSVP, first show the exact calendar, title, start/end, timezone, attendees, recurrence/instance scope, Meet link behavior, and `send_updates` behavior.",
      "- Call write tools only after the user explicitly approves that exact action.",
      "- To delete, RSVP, or move several events on the same calendar at once (e.g. clearing an afternoon, declining a batch of invites), pass `event_ids` (array) to `GoogleCalendarDeleteEvent`/`GoogleCalendarRespondToEvent`/`GoogleCalendarMoveEvent` in ONE call. One approval covers the batch; the tool returns a per-item succeeded/failed summary. There is no native Calendar batch endpoint, so this loops server-side — still one model tool call.",
      "- For recurring events, distinguish one occurrence from the whole series before writing.",
      "- Treat `send_updates` as external communication when attendees are present.",
      "- If iOS Calendar is involved, remind the user that events sync only when they are saved to the Google calendar, not iCloud or On My iPhone.",
      "",
      "## Failure Handling",
      "",
      "- Missing config: ask for the smallest missing credential package.",
      "- Missing scope or refresh token: start OAuth again and ask the user to approve consent.",
      "- Redirect URI mismatch: tell the user the exact redirect URI to add in Google Cloud and restart OAuth after they update it.",
      "- Calendar write failure: report the Google API error and do not retry a write with broader changes unless the user approves the corrected action.",
      "- Local API unreachable: report the attempted URL and ask for the reachable Orchestrator app URL or start the local app if appropriate.",
      "",
    ].join("\n"),
  },
  {
    id: "google-workspace",
    label: "Google Workspace runbook",
    relativePath: "INTEGRATIONS/google-workspace.md",
    description:
      "Agent setup and operating guide for Google Workspace OAuth, Drive files, Docs, Sheets, Slides, Contacts, exports, uploads, organization, and sharing.",
    defaultContent: [
      "# Google Workspace Integration Runbook",
      "",
      "Use this runbook when the user asks to connect, configure, repair, verify, search, read, export, download, upload, organize, delete, share, create, or edit Google Workspace data: Drive, Docs, Sheets, Slides, and Google Contacts.",
      "",
      "## Capability",
      "",
      "- Reuse Google Workspace OAuth client config for Drive, Calendar, Docs, Sheets, and Slides integrations.",
      "- Read Drive profile, storage quota, shared drives, file metadata, permissions, text-like files, and exported Google Docs/Sheets/Slides.",
      "- Create and edit native Google Docs with Docs API batch updates.",
      "- Create, read, update, append, clear, format, chart, and structurally modify native Google Sheets.",
      "- Create and edit native Google Slides decks with batch updates and thumbnail-based visual verification.",
      "- Read, search, create, update, delete, import, and group personal Google Contacts through People API after explicit approval for writes.",
      "- Read/search “Other contacts” and copy selected Other Contacts into My Contacts after explicit approval.",
      "- Download binary files and exported Workspace files to the agent workspace.",
      "- Upload local workspace files, replace Drive file content, create folders, create blank Google Docs/Sheets/Slides/Drawings/Forms, copy, move, rename/update metadata, trash, untrash, permanently delete, and change sharing permissions only after explicit user approval.",
      "",
      "## Implementation Surface",
      "",
      "Workspace env vars:",
      "- `GOOGLE_OAUTH_CLIENT_ID`",
      "- `GOOGLE_OAUTH_CLIENT_SECRET`",
      "- `GOOGLE_WORKSPACE_OAUTH_REDIRECT_URI` optional; defaults to a Google-compatible callback: `<app_origin>/api/integrations/google/oauth/callback` only when app_origin is localhost or public HTTPS, otherwise `http://localhost:3000/api/integrations/google/oauth/callback` for SSH-tunnel setup.",
      "",
      "Local API endpoints:",
      "- `GET <app_origin>/api/integrations/status`",
      '- `PUT <app_origin>/api/integrations/google-drive/config` with JSON body `{ "rawEnv": "...", "clientId": "...", "clientSecret": "...", "redirectUri": "..." }`',
      "- `POST <app_origin>/api/integrations/google-drive/oauth/start`",
      "- `GET <app_origin>/api/integrations/google/oauth/callback` is handled by the app after Google redirects back.",
      "- `POST <app_origin>/api/integrations/google-drive/disconnect` revokes and removes local Workspace tokens used by Drive, Docs, Sheets, Slides, and Contacts.",
      "",
      "Runtime setup tools:",
      "- `GoogleDriveStatus` checks config, connection, scopes, storage quota, and capabilities.",
      "- `GoogleDriveConfigure` saves reusable Google Workspace OAuth config. Never echo client secrets.",
      "- `GoogleDriveStartOAuth` returns the Google consent URL. The user must approve consent.",
      "",
      "Runtime read tools:",
      "- `GoogleDriveAbout`",
      "- `GoogleDriveListSharedDrives`",
      "- `GoogleDriveListFiles`",
      "- `GoogleDriveGetFile`",
      "- `GoogleDriveReadFile`",
      "- `GoogleDriveDownloadFile`",
      "- `GoogleDriveExportFile`",
      "- `GoogleDriveListPermissions`",
      "- `GoogleDocsGetDocument`",
      "- `GoogleSheetsGetSpreadsheet`, `GoogleSheetsGetValues`, `GoogleSheetsBatchGetValues`",
      "- `GoogleSlidesGetPresentation`, `GoogleSlidesGetPage`, `GoogleSlidesGetThumbnail`",
      "- `GoogleContactsListConnections`, `GoogleContactsSearchContacts`, `GoogleContactsGetPerson`, `GoogleContactsBatchGetPeople`",
      "- `GoogleContactsListContactGroups`, `GoogleContactsGetContactGroup`",
      "- `GoogleContactsListOtherContacts`, `GoogleContactsSearchOtherContacts`",
      "",
      "Runtime write/share tools requiring explicit confirmation:",
      "- `GoogleDriveUploadFile`",
      "- `GoogleDriveUpdateFileContent`",
      "- `GoogleDriveCreateFolder`",
      "- `GoogleDriveCreateGoogleFile`",
      "- `GoogleDriveUpdateMetadata`",
      "- `GoogleDriveMoveFile`",
      "- `GoogleDriveCopyFile`",
      "- `GoogleDriveTrashFile`",
      "- `GoogleDriveUntrashFile`",
      "- `GoogleDriveDeleteFile`",
      "- `GoogleDriveShareFile`",
      "- `GoogleDriveUpdatePermission`",
      "- `GoogleDriveDeletePermission`",
      "- `GoogleDocsCreateDocument`, `GoogleDocsInsertText`, `GoogleDocsReplaceAllText`, `GoogleDocsApplyTextStyle`, `GoogleDocsApplyParagraphStyle`, `GoogleDocsInsertTable`, `GoogleDocsBatchUpdate`",
      "- `GoogleSheetsCreateSpreadsheet`, `GoogleSheetsUpdateValues`, `GoogleSheetsAppendValues`, `GoogleSheetsClearValues`, `GoogleSheetsBatchUpdate`",
      "- `GoogleSlidesCreatePresentation`, `GoogleSlidesCreateSlide`, `GoogleSlidesInsertTextBox`, `GoogleSlidesReplaceAllText`, `GoogleSlidesBatchUpdate`",
      "- `GoogleContactsCreateContact`, `GoogleContactsBatchCreateContacts`, `GoogleContactsUpdateContact`, `GoogleContactsBatchUpdateContacts`, `GoogleContactsDeleteContact`, `GoogleContactsBatchDeleteContacts`",
      "- `GoogleContactsCreateContactGroup`, `GoogleContactsUpdateContactGroup`, `GoogleContactsDeleteContactGroup`, `GoogleContactsModifyContactGroupMembers`, `GoogleContactsCopyOtherContactToMyContacts`",
      "",
      "## Setup Flow",
      "",
      "1. Check status first with `GoogleDriveStatus` or `GET <app_origin>/api/integrations/status`.",
      "",
      "2. If OAuth config is missing, ask for exactly one of:",
      "   - Google OAuth client JSON downloaded from Google Cloud for a Web application.",
      "   - Env lines containing `GOOGLE_OAUTH_CLIENT_ID` and `GOOGLE_OAUTH_CLIENT_SECRET`.",
      "   - Separate client ID and client secret values.",
      "",
      "3. If the user needs Google Cloud instructions, give the full setup path with links:",
      "   - Open the Google Cloud project selector and choose or create the project that should own this integration: https://console.cloud.google.com/projectselector2/home/dashboard.",
      "   - Enable every Workspace API this integration uses before trying OAuth: Drive API https://console.cloud.google.com/flows/enableapi?apiid=drive.googleapis.com, Docs API https://console.cloud.google.com/flows/enableapi?apiid=docs.googleapis.com, Sheets API https://console.cloud.google.com/flows/enableapi?apiid=sheets.googleapis.com, Slides API https://console.cloud.google.com/flows/enableapi?apiid=slides.googleapis.com, and People API https://console.cloud.google.com/flows/enableapi?apiid=people.googleapis.com. CLI alternative: `gcloud services enable drive.googleapis.com docs.googleapis.com sheets.googleapis.com slides.googleapis.com people.googleapis.com`.",
      "   - Configure the Google Auth platform consent screen: https://console.cloud.google.com/auth/branding. If the app is External/testing, open Audience and add the user email as a test user: https://console.cloud.google.com/auth/audience.",
      "   - Create or reuse a Web application OAuth client in Google Auth platform > Clients: https://console.cloud.google.com/auth/clients.",
      "   - Under Authorized redirect URIs, add exactly the redirect URI reported by status/config. Do not invent this from `<app_origin>` when it is `.lan`, `.local`, or a private IP; Google rejects those. Explain that scheme, host, path, and trailing slash must match or Google returns `redirect_uri_mismatch`.",
      "   - Download the OAuth client JSON or copy the client ID and client secret. Tell the user to paste the JSON or env lines here, not screenshots.",
      "   - Use official references if Google changes labels: https://developers.google.com/workspace/guides/enable-apis, https://developers.google.com/workspace/guides/configure-oauth-consent, https://developers.google.com/workspace/guides/create-credentials, https://developers.google.com/workspace/drive/api/guides/api-specific-auth.",
      "",
      "4. Save config.",
      "   - Never repeat the secret value in chat.",
      "   - Prefer `GoogleDriveConfigure` for pasted env lines or Google OAuth JSON.",
      "   - For separate values, use `GoogleDriveConfigure` with `client_id`, `client_secret`, and optional `redirect_uri`.",
      "",
      "5. Start OAuth.",
      "   - Call `GoogleDriveStartOAuth`.",
      "   - Give the returned `authUrl` to the user and ask them to approve the Google consent screen.",
      "   - If the returned redirect URI is localhost and the app process is on the same machine as the user browser, no tunnel is needed. If the app is on a different headless server and the user is browsing through `.lan`, `.local`, or an IP, do not continue from that page; use `runtime.sshHostCandidates` from status or runtime_context rather than a hardcoded IP, start a tunnel such as `ssh -N -L <local_port>:127.0.0.1:<remote_port> <user>@<ssh_host>` when shell access on the browser machine is available, otherwise give that exact command and ask the user to open `http://localhost:<local_port>/settings` before clicking Connect.",
      "   - Tell the user to keep the SSH tunnel terminal open until Google redirects back and status says Connected. After status is Connected, tell them to stop the tunnel with Ctrl+C.",
      "   - Start only this one OAuth flow and verify it before starting another Google integration.",
      "   - Do not claim Google Workspace is connected until status confirms it.",
      "",
      "6. Verify after consent.",
      "   - Recheck `GoogleDriveStatus` or `GET <app_origin>/api/integrations/status`.",
      "   - Success means `googleDrive.connected` is true and `googleDrive.needsReconnect` is false.",
      "   - Report connected account, granted scopes, Workspace capabilities, and storage quota if available.",
      "",
      "## Operating Flow After Setup",
      "",
      "- For file lookup, search narrowly first: name, parent folder, MIME type, owner, shared state, modified window, or shared drive.",
      "- Read only files relevant to the user request. Use `GoogleDriveGetFile` for metadata before broad content reads.",
      "- Use `GoogleDriveReadFile` for text-like content and Google Workspace text exports.",
      "- Use `GoogleDriveExportFile` when the user needs a specific output format such as PDF, DOCX, XLSX, PPTX, CSV, or plain text.",
      "- Use `GoogleDriveDownloadFile` for binary non-Workspace files.",
      "- Summarize private document content minimally and avoid dumping full content unless the user explicitly asks for it.",
      "- Before uploading local files to Drive, replacing content, creating folders/files, moving/copying/renaming/trashing/untrashing/deleting files, or changing permissions, summarize the exact source, target, destination, file name, MIME/export format, permission principal, role, notification behavior, and reversibility.",
      "- Call write/share/delete tools only after the user explicitly approves that exact action.",
      "- To act on several Drive files at once, pass `file_ids` (array) to `GoogleDriveTrashFile`/`GoogleDriveUntrashFile`/`GoogleDriveDeleteFile`/`GoogleDriveMoveFile` in ONE call (one approval covers the batch; returns a per-item succeeded/failed summary; loops server-side since Drive has no native batch endpoint). Contacts already exposes `GoogleContactsBatch*` tools and Docs/Sheets/Slides expose native `*BatchUpdate` — prefer those over repeated single-item calls.",
      "- Prefer Trash over permanent deletion unless the user explicitly confirms permanent deletion.",
      "- Prefer user/group sharing over domain or anyone links; treat owner transfer, public/domain links, and notification emails as high-risk access changes.",
      "- For Docs, read the document before edits, build a section skeleton, use headings/tables/styles intentionally, and re-read after writes.",
      "- For Sheets, read metadata and exact ranges first, preserve formulas/validation/protection unless approved, and verify edited ranges after writes.",
      "- For Slides, build the narrative first, use editable native elements, avoid clipped text/overlap, and verify every touched slide with `GoogleSlidesGetPage` plus `GoogleSlidesGetThumbnail`.",
      "- For Contacts, search/list first, read exact `people/*` resources before updates, preserve current etag/source metadata, and verify writes with readback.",
      "- Treat contact creates, edits, deletes, group membership changes, batch imports, and copying Other Contacts into My Contacts as synced personal-data changes that need exact confirmation.",
      "- For iOS Contacts questions, explain that Orchestrator sees contacts saved in/synced to Google Contacts, not contacts stored only in iCloud or On My iPhone.",
      "",
      "## Failure Handling",
      "",
      "- Missing config: ask for the smallest missing credential package.",
      "- Missing scope or refresh token: start OAuth again and ask the user to approve consent.",
      "- Redirect URI mismatch: tell the user the exact redirect URI to add in Google Cloud and restart OAuth after they update it.",
      "- Export failure: try a format supported by `GoogleDriveAbout.exportFormats` or ask which format the user wants.",
      "- Upload/download too large: report byte size and ask for a narrower file, lower limit, or approved large transfer path.",
      "- Permission failure: report the Google API error and do not retry with broader sharing unless the user approves the corrected action.",
      "- Local API unreachable: report the attempted URL and ask for the reachable Orchestrator app URL or start the local app if appropriate.",
      "",
    ].join("\n"),
  },
  {
    id: "whatsapp",
    label: "WhatsApp runbook",
    relativePath: "INTEGRATIONS/whatsapp.md",
    description:
      "Agent setup and operating guide for local WhatsApp Web QR login, reads, confirmed sends, media attachments, and delete-for-everyone.",
    defaultContent: [
      "# WhatsApp Integration Runbook",
      "",
      "Use this runbook when the user asks to connect, configure, repair, verify, read, send, attach files, attach photos, delete, or mark read/unread WhatsApp messages.",
      "",
      "## Capability",
      "",
      "- Start a local WhatsApp Web session with the user scanning a QR code from their phone.",
      "- List recent WhatsApp chats.",
      "- Read recent messages from a selected chat.",
      "- Search recent message bodies across recent chats.",
      "- Download the media (photo, video, voice note, audio, document, sticker) from a received message and show it to the user inline.",
      "- Send text messages only after the user explicitly approves the exact chat and exact message body.",
      "- Send workspace files/photos as WhatsApp media/documents only after the user explicitly approves the exact chat, files, and caption.",
      "- Delete messages only with `WhatsAppDeleteMessageForEveryone`; no delete-for-me mode is exposed.",
      "- Mark a chat read or unread on the user's phone with `WhatsAppMarkChatRead`/`WhatsAppMarkChatUnread` (the only WhatsApp state-change tools beyond send/delete); both accept a `chat_ids` array, and delete accepts `message_ids`, to act on several at once in one call.",
      "- Never archive, mute, pin, or label, nor otherwise mutate WhatsApp state unless a dedicated confirmed tool is added.",
      "",
      "## Implementation Surface",
      "",
      "Local runtime:",
      "- Uses `whatsapp-web.js` and a local browser controlled by Puppeteer.",
      "- Uses `qrcode` to render QR codes.",
      "- Stores session data under private app state, not in markdown memory.",
      "- Optional env var: `WHATSAPP_CHROME_EXECUTABLE_PATH` when Chrome/Chromium cannot be auto-detected.",
      "",
      "Local API endpoints:",
      "- `GET <app_origin>/api/integrations/status`",
      "- `POST <app_origin>/api/integrations/whatsapp/start`",
      "- `GET <app_origin>/api/integrations/whatsapp/qr` returns the current QR PNG when available.",
      "- `POST <app_origin>/api/integrations/whatsapp/disconnect` removes the local session.",
      "",
      "Runtime tools:",
      "- `WhatsAppStatus` checks connection, QR, browser, and local-session state.",
      "- `WhatsAppConnect` starts the local WhatsApp Web session and returns `qrMarkdown` when the user must scan a QR.",
      "- `WhatsAppListChats` lists recent chats after connection.",
      "- `WhatsAppReadChat` reads recent messages from one chat.",
      "- `WhatsAppSearchMessages` scans recent messages; this is not full-history server-side search.",
      "- `WhatsAppDownloadMedia` downloads the media on one message (by message id) and saves it as an upload; returns `mediaMarkdown` to embed so the photo/file shows inline for the user. Read-only; no confirmation required.",
      "- `WhatsAppSendMessage` sends a confirmed text message.",
      "- `WhatsAppSendMedia` sends confirmed workspace files/photos as media/documents.",
      "- `WhatsAppDeleteMessageForEveryone` deletes a confirmed exact message for everyone (pass `message_ids` to delete several at once).",
      "- `WhatsAppMarkChatRead` / `WhatsAppMarkChatUnread` clear or restore the unread badge on the user's phone (pass `chat_ids` to mark several chats at once).",
      "",
      "## Setup Flow",
      "",
      "1. Check status first.",
      "   - Use `WhatsAppStatus` or `GET <app_origin>/api/integrations/status`.",
      "   - If `configured` is false, ask the user to install Chrome/Chromium or set `WHATSAPP_CHROME_EXECUTABLE_PATH` to the local executable path.",
      "",
      "2. Start QR login.",
      "   - Call `WhatsAppConnect`.",
      "   - If `qrMarkdown` is returned, show it directly to the user in the chat.",
      "   - Tell the user to open WhatsApp on their phone, go to Linked devices, choose Link a device, and scan the QR.",
      "   - Do not claim connection succeeded until status reports `whatsapp.connected` true.",
      "",
      "3. Verify after scanning.",
      "   - Recheck `WhatsAppStatus`.",
      "   - If status is `authenticated` or `starting`, wait and check again; do not restart the QR handshake while WhatsApp Web is still finishing login.",
      "   - Success means `connected` is true and phase is `ready`.",
      "   - Report the connected display name or phone number when available.",
      "",
      "## Operating Flow After Setup",
      "",
      "- For triage, list chats first, then read only chats relevant to the user request.",
      "- Minimize private content exposure in summaries.",
      "- Mention that search scans recent messages, not guaranteed full history.",
      "- When the user wants a photo/file from a message (its summary shows `hasMedia` true), call `WhatsAppDownloadMedia` with that message id, then embed the returned `mediaMarkdown` in your reply so it appears inline. This only downloads, so no confirmation is needed.",
      "- Before sending a text message, show the exact destination and exact body; call `WhatsAppSendMessage` only after explicit user approval and set `confirmed_by_user` true.",
      "- Before sending photos/files, show the exact destination, workspace paths/filenames, whether they send as media or documents, and the caption; call `WhatsAppSendMedia` only after explicit user approval and set `confirmed_by_user` true.",
      "- Before deleting, show the exact message id and explain it will be deleted for everyone; call `WhatsAppDeleteMessageForEveryone` only after explicit user approval and set `confirmed_by_user` true.",
      "- To clear/restore unread on several chats at once, pass `chat_ids` (array) to `WhatsAppMarkChatRead`/`WhatsAppMarkChatUnread` in ONE call; for batch delete-for-everyone after approval, pass `message_ids`. These loop server-side over the single WhatsApp Web session (kept at low concurrency) and return a per-item succeeded/failed summary.",
      "- Stop if the user asks to delete only for themselves; this implementation intentionally exposes delete-for-everyone only.",
      "- Stop if the user asks to archive, mute, or pin; those WhatsApp state changes have no exposed tool (mark read/unread do).",
      "",
      "## Failure Handling",
      "",
      "- No browser found: ask for a Chrome/Chromium path and store it in `WHATSAPP_CHROME_EXECUTABLE_PATH` with `SetEnv`.",
      "- QR expired while still unscanned: call `WhatsAppConnect` again or recheck status until a refreshed QR appears.",
      "- Auth failure: disconnect and start again.",
      "- Media download returns no data / media unavailable: WhatsApp drops media from its servers over time, so older attachments may no longer be downloadable once they leave the local WhatsApp Web cache. Tell the user it can no longer be retrieved and, if they still need it, ask them to reopen or resend it in WhatsApp. If the message id is simply not found, open the chat with `WhatsAppReadChat` first so the message loads, then retry `WhatsAppDownloadMedia`.",
      "- Local API unreachable: report the attempted URL and ask for the reachable Orchestrator app URL or start the local app if appropriate.",
      "",
      "## Safety Notes",
      "",
      "- This is a local WhatsApp Web session for the user who scans the QR code.",
      "- Treat the QR as sensitive while it is valid.",
      "- Do not store QR contents in memory files.",
      "- Writes affect the user's real WhatsApp account. Never send or delete unless the user explicitly confirms the exact action in the current conversation.",
      "- Delete operations are delete-for-everyone only; do not offer delete-for-me.",
      "",
    ].join("\n"),
  },
  {
    id: "home-assistant",
    label: "Home Assistant runbook",
    relativePath: "INTEGRATIONS/home-assistant.md",
    description:
      "Agent setup and operating guide for read-only Home Assistant REST/WebSocket API access.",
    defaultContent: [
      "# Home Assistant Integration Runbook",
      "",
      "Use this runbook when the user asks to connect, configure, verify, inspect, summarize, or troubleshoot Home Assistant.",
      "",
      "## Capability",
      "",
      "- Save a Home Assistant base URL and long-lived access token locally.",
      "- Read API status, core config, events, services, states, entity state, history, logbook, error log, calendars, camera snapshots, templates, config checks, registries, automations, scripts, and scenes.",
      "- Read `person.*`, `device_tracker.*`, and `zone.*` entities to identify the user's live location source for maps, commute, and location-aware monitors.",
      "- Use REST and whitelisted read-only WebSocket commands.",
      "- In action mode, directly control lights, covers, climate, and notify services when the user clearly asks.",
      "- In action mode, any other Home Assistant service may be called only after explicit user confirmation of the exact service, target, and data.",
      "- Never edit YAML/config files, access Samba/SSH/add-on filesystems, or bypass the Home Assistant API.",
      "",
      "## Implementation Surface",
      "",
      "Workspace env vars:",
      "- `HOME_ASSISTANT_URL` such as `http://homeassistant.local:8123` or `http://<ip>:8123`",
      "- `HOME_ASSISTANT_TOKEN` long-lived access token",
      "",
      "Local API endpoints:",
      "- `GET <app_origin>/api/integrations/status`",
      '- `PUT <app_origin>/api/integrations/home-assistant/config` with JSON body `{ "baseUrl": "...", "token": "...", "rawEnv": "..." }`',
      "- `POST <app_origin>/api/integrations/home-assistant/disconnect` removes local URL/token config.",
      "- `GET/PUT <app_origin>/api/integrations/home-assistant/action-policy` reads or updates local action mode policy.",
      "",
      "Runtime setup tool:",
      "- `HomeAssistantConfigure` saves URL/token or pasted env lines and verifies the API. Never echo token values.",
      "- `HomeAssistantStatus` checks configured, connected, version, entity count, service-domain count, and errors.",
      "",
      "Runtime read tools:",
      "- `HomeAssistantApiInfo`, `HomeAssistantGetConfig`",
      "- `HomeAssistantListStates`, `HomeAssistantGetState`, `HomeAssistantSearchEntities`",
      "- `HomeAssistantListServices`, `HomeAssistantListEvents`",
      "- `HomeAssistantHistory`, `HomeAssistantLogbook`, `HomeAssistantErrorLog`",
      "- `HomeAssistantListCalendars`, `HomeAssistantReadCalendar`",
      "- `HomeAssistantCameraSnapshot`",
      "- `HomeAssistantRenderTemplate`, `HomeAssistantCheckConfig`",
      "- `HomeAssistantWebSocketRead` for `get_config`, `get_states`, `get_services`, `get_panels`, `ping` only",
      "- `HomeAssistantListRegistries` best-effort areas/devices/entities/floors/labels read",
      "- `HomeAssistantListAutomations`, `HomeAssistantListScripts`, `HomeAssistantListScenes`, `HomeAssistantAutomationActivity`",
      "- `HomeAssistantReadAutomationConfig`, `HomeAssistantListAutomationConfigs` read exposed automation trigger/condition/action components.",
      "",
      "Runtime action tools:",
      "- `HomeAssistantPreviewAction` validates a service call without executing it.",
      "- `HomeAssistantSetLight` controls `light.*` with brightness, color, color temperature, effect, transition, turn on/off, and toggle. `entity_ids` is an array — control several lights (all the downstairs lights) in ONE call rather than one call per entity.",
      "- `HomeAssistantSetCover` controls `cover.*` open, close, stop, toggle, position, and tilt position. `entity_ids` is an array — control several covers at once.",
      "- `HomeAssistantSetClimate` controls `climate.*` HVAC mode, temperature, preset, fan, humidity, and swing mode. `entity_ids` is an array — control several thermostats at once.",
      "- `HomeAssistantNotify` sends through `notify.*` services.",
      "- `HomeAssistantCallService` is the generic service caller. For domains outside light/cover/climate/notify, use it only after explicit user confirmation and set `confirmed: true`.",
      "- `HomeAssistantReadActionAudit` reads recent local action audit entries.",
      "",
      "## Setup Flow",
      "",
      "1. Check status first with `HomeAssistantStatus` or `GET <app_origin>/api/integrations/status`.",
      "",
      "2. If config is missing, ask for exactly:",
      "   - Home Assistant URL.",
      "   - Long-lived access token from the user profile page.",
      "   - Or pasted env lines containing `HOME_ASSISTANT_URL` and `HOME_ASSISTANT_TOKEN`.",
      "",
      "3. If the user needs token instructions:",
      "   - Open Home Assistant.",
      "   - Click the user profile.",
      "   - Scroll to Long-lived access tokens.",
      "   - Create a token named Orchestrator.",
      "   - Paste it once. Do not ask for Samba, SSH, YAML, or add-on filesystem access.",
      "",
      "4. Save config with `HomeAssistantConfigure` or the local config API.",
      "   - Never repeat the token in chat.",
      "   - Verification success means `homeAssistant.connected` is true and `needsReconnect` is false.",
      "   - If verification fails, report the exact network/auth error and ask only for the corrected URL/token or network route.",
      "",
      "5. After a successful connection, identify and save the user-location source for maps.",
      "   - Read `person.*`, `device_tracker.*`, and `zone.*` entities with `HomeAssistantListStates` / `HomeAssistantSearchEntities`.",
      "   - Infer the entity that represents the current Orchestrator user from user profile/name, friendly names, entity ids, current zone/state, and whether latitude/longitude attributes exist.",
      '   - If one `person.*` or `device_tracker.*` candidate is high-confidence, persist it immediately as the default "my location" source with `PUT <app_origin>/api/maps/location-source` using JSON `{ "provider": "home-assistant", "entityId": "person.horia", "label": "Horia" }`.',
      "   - If several candidates are plausible, show a short list (friendly name, entity id, current zone/state, whether latitude/longitude attributes exist) and ask the user to pick one.",
      "   - Store only the non-secret entity id and optional label. Do not store tokens or full GPS history in memory files.",
      "   - Smart Maps defaults to the saved Home Assistant entity. If it does not exist or cannot resolve, the Smart Maps page falls back to browser geolocation; server-side agents/jobs use the saved profile location as their non-browser fallback.",
      "",
      "## Operating Flow After Setup",
      "",
      "- For smart-home summaries, start with `HomeAssistantListStates` using domain/query filters, then inspect exact entities with `HomeAssistantGetState`.",
      '- For "where am I", commute, geofence, or map defaults outside an active browser session, prefer `GET <app_origin>/api/maps/current-location`. If no Home Assistant source is configured, inspect likely `person.*` / `device_tracker.*` entities and save a high-confidence match as the user\'s default; ask only when ambiguous.',
      "- For automations, use `HomeAssistantListAutomations` and `HomeAssistantAutomationActivity` before drawing conclusions.",
      "- For automation structure, use `HomeAssistantReadAutomationConfig` or `HomeAssistantListAutomationConfigs`. Some YAML/unexposed automations may return 404 even though their entities exist.",
      "- For scenes/scripts, use their dedicated list tools and service schemas first; call scripts/scenes only after explicit user confirmation via `HomeAssistantCallService`.",
      "- For direct light/cover/climate/notify requests, use the dedicated action tool, then report before/after state and audit id.",
      "- For all other service calls, first say exactly: service domain/name, target entity/device/area, data payload, and expected effect; ask for confirmation; call with `confirmed: true` only after the user confirms.",
      "- For trends, use `HomeAssistantHistory` with explicit entity IDs and bounded time ranges.",
      "- For recent events, use `HomeAssistantLogbook` with entity and time filters.",
      "- For visual checks, use `HomeAssistantCameraSnapshot` only when the user request makes camera access relevant.",
      "- Minimize sensitive home data in summaries; include only what is useful for the request.",
      "",
      "## Failure Handling",
      "",
      "- Missing config: ask for URL and token only.",
      "- 401/403: token is missing, expired, copied incorrectly, or lacks permissions; ask for a fresh long-lived token.",
      "- Network failure: verify scheme, port 8123, hostname/IP, local network/VPN, firewall, and whether Orchestrator runs where Home Assistant is reachable.",
      "- `HomeAssistantErrorLog` uses the documented `GET /api/error_log`; if that endpoint returns unavailable/404 while other calls work, treat only that log endpoint as unsupported and continue with logbook, states, config, or WebSocket reads.",
      "- WebSocket registry read failures can be permission/version/support differences. Fall back to REST states/config/services when possible.",
      "- Large history/logbook output: narrow entity IDs and time ranges instead of fetching everything.",
      "",
      "## Safety Notes",
      "",
      "- Read tools are available for all Home Assistant state and metadata exposed by the API.",
      "- Action mode is enabled/disabled by local policy.",
      "- `HomeAssistantConfigure` and disconnect only mutate local Orchestrator config.",
      "- Direct action domains are light, cover, climate, and notify.",
      "- All other domains require explicit confirmation in the current conversation before calling `HomeAssistantCallService` with `confirmed: true`.",
      "- Do not edit YAML/config files, use Samba/SSH, or bypass Home Assistant permissions.",
      "",
    ].join("\n"),
  },
  {
    id: "maps",
    label: "Google Maps runbook",
    relativePath: "INTEGRATIONS/maps.md",
    description:
      "Agent setup and operating guide for interactive satellite map artifacts (Google Maps JavaScript API).",
    defaultContent: [
      "# Google Maps Integration Runbook",
      "",
      "Use this runbook when the user asks to enable, configure, repair, or troubleshoot satellite maps in the chat.",
      "",
      "## Capability",
      "",
      "- Render interactive satellite maps inline in chat as `application/vnd.ant.map` artifacts via the `MapRender` tool.",
      "- The renderer uses Google Maps JavaScript API loaded inside a sandboxed iframe — same engine that powers maps.google.com, so imagery quality and behaviour match what users already know.",
      "- Two basemaps: `satellite` (pure imagery, no POI clutter) and `satellite-streets` (Google's hybrid: imagery + road labels). Default is `satellite`.",
      "- Trip-planner mode (multi-day) when the payload includes a `days[]` array — produces day-tab pills above the map + a per-day sidebar with location cards.",
      "- Pins (with optional photo, address, rating, icon, custom colour), polylines, polygons, custom popups, click-to-fly sidebar nav, and local multi-stop order optimization.",
      "",
      "## Implementation Surface",
      "",
      "Workspace env vars:",
      "- `GOOGLE_MAPS_API_KEY` — one Google Cloud API key with **Maps JavaScript API**, **Geocoding API**, **Places API**, and **Routes API** enabled. It also unlocks Weather API, Air Quality API, Pollen API, and Static Maps when those APIs are enabled separately in the same GCP project.",
      "- `GOOGLE_MAPS_MAP_ID` (recommended) — a custom JavaScript Map ID created in Cloud Console with **Vector** rendering and **Tilt and Rotation** enabled. Defaults to Google's `DEMO_MAP_ID` if unset, which is acceptable for basic development but not the production path for reliable tilt/heading.",
      "",
      "Setup tool:",
      "- `MapsStatus` — reports `configured` (key present), `connected` (a Geocoding probe with the key returned OK), `mapIdConfigured`, `vectorMap`, and `earth3d`. When `connected` is false but `configured` is true, the error string carries Google's response verbatim, including the GCP console URL to enable the missing API.",
      "- `MapsCurrentLocation` — returns the server-side current-location default (saved Home Assistant entity first, saved profile location second). The Smart Maps page uses browser geolocation only when that Home Assistant source is missing or cannot resolve.",
      "- `MapsListLocationSources` — lists likely Home Assistant `person.*`, `device_tracker.*`, and `zone.*` location entities for onboarding.",
      "- `MapsSetLocationSource` — persists the non-secret Home Assistant entity id as the default live location source after the model identifies a high-confidence user match, or after the user chooses among ambiguous candidates.",
      "- Note: `MapsStatus` proves the key and Geocoding API path. `MapsPlaces` and `MapsDirections` will still return clear errors if the Places API or Routes API has not been enabled yet.",
      "",
      "Operational tools (all granted directly to the orchestrator, no activation gate):",
      '- `MapRender` — validates a map payload against `MapArtifactSchema` and direct-emits the canonical `<artifact type="application/vnd.ant.map">` into chat. Validation is local; no upstream call.',
      "- `MapsGeocode` — batch address → [lng, lat] via Google Geocoding API. Accepts up to 10 addresses per call. Returns per-input hit/miss entries; misses keep the query string so the orchestrator can acknowledge in chat.",
      "- `MapsReverseGeocode` — [lng, lat] → human-readable address. Single-point.",
      "- `MapsPlaces` — Google Places API (New) text/nearby search for POIs and venues. Returns normalized places plus `pinReady[]` / `mapPins` that can be passed into `MapRender.pins[]` after composition.",
      '- `MapsOptimizeStops` — local straight-line optimizer for already-geocoded stops. Returns `waypointPositions` ready for `MapsDirections`; useful for errands, logistics, and "what order should I visit".',
      "- `MapsDirections` — ordered [lng, lat] waypoints → route geometry, distance, duration, and fitBounds via Google Routes API. Use after geocoding; the output is ready to pass into `MapRender.routes[]`.",
      "",
      "Local route:",
      "- `GET <app_origin>/api/maps/config` — returns `{ configured, key, mapId }` using `GOOGLE_MAPS_API_KEY` (503 when unconfigured). The chat client fetches this once at mount and injects the values into the sandboxed map iframe.",
      "- `GET <app_origin>/api/maps/current-location` — returns the default server-side location. Smart Maps prefers a saved Home Assistant location source and falls back to browser geolocation when that source is missing or unavailable.",
      "- `GET/PUT/DELETE <app_origin>/api/maps/location-source` — reads, saves, or clears the Home Assistant live-location entity inferred or chosen for the user.",
      "",
      "## Setup Flow",
      "",
      "1. Call `MapsStatus`. If `configured` is true and `connected` is true, you are done.",
      "",
      "2. If `configured` is false:",
      "   - Direct the user to https://console.cloud.google.com/google/maps-apis to create or pick a project, then create an API key.",
      "   - In the same project, the user must enable these APIs as separate enable steps:",
      "     - **Maps JavaScript API** — drives the interactive chat map. https://console.cloud.google.com/apis/library/maps-backend.googleapis.com",
      "     - **Geocoding API** — turns user-supplied addresses into pin coordinates. https://console.cloud.google.com/apis/library/geocoding-backend.googleapis.com",
      "     - **Places API** — finds places/POIs/venues for `MapsPlaces`. https://console.cloud.google.com/apis/library/places-backend.googleapis.com",
      "     - **Routes API** — computes route geometry, duration, and distance for `MapsDirections`. https://console.cloud.google.com/apis/library/routes.googleapis.com",
      "     - Optional weather-card upgrades: **Weather API** https://console.cloud.google.com/apis/library/weather.googleapis.com, **Air Quality API** https://console.cloud.google.com/apis/library/airquality.googleapis.com, and **Pollen API** https://console.cloud.google.com/apis/library/pollen.googleapis.com.",
      "   - When the user provides the key, call `SetEnv` with name `GOOGLE_MAPS_API_KEY`. Do not echo key values back. The server must restart to pick up env changes.",
      "   - For production Smart Maps tilt/rotation, ask the user to create a Map ID in Map Management: type **JavaScript**, rendering **Vector**, with **Tilt and Rotation** enabled. Save it as `GOOGLE_MAPS_MAP_ID`.",
      "   - Explain the 3D distinction clearly: normal Maps tilt is vector/heading support; Earth-like photorealistic 3D uses Maps JavaScript **3D Maps beta** (`gmp-map-3d` / `Map3DElement`) and coverage varies by area.",
      "   - Recommend restricting the key in Google Cloud Console once the basic flow works: allow the APIs above and the app origins used by the deployment where applicable. Maps JavaScript keys are designed to reach the browser; restrictions are what stop third-party abuse.",
      "",
      "3. If `configured` is true but `connected` is false:",
      '   - Inspect the `error` field on `MapsStatus`. If it mentions `SERVICE_DISABLED` or names a specific API (e.g. "Geocoding API has not been used"), the user needs to enable that API in their GCP project. The error message includes the activation URL.',
      "   - If the error mentions `API_KEY_INVALID` or HTTP 401, the key is wrong; ask the user to re-paste.",
      "   - If the error mentions `BILLING_DISABLED` or quota, the user needs to enable billing on the GCP project. Both APIs require a billing account; usage stays under the monthly $200 free credit for any reasonable single-user volume.",
      "   - After any change, call `MapsStatus` with `refresh: true` to skip the 5-minute probe cache.",
      "",
      "4. Verify by composing a tiny test artifact (e.g. a single pin over a known landmark) with `MapRender`. If the map renders, you are done.",
      "",
      "## Cost Notes",
      "",
      '- Maps JavaScript API: $7 / 1k map loads (one "load" = an entire pan/zoom session). The $200/month free credit covers any single-user volume.',
      "- Geocoding API: $5 / 1k requests. Same free credit pool.",
      "- Places API: billed by selected field mask/SKU; `MapsPlaces` uses an explicit field mask and only requests ratings/websites when asked.",
      "- Routes API: billed per route compute request; same Maps Platform free credit pool. Single-user route planning volume should stay negligible.",
      "- The Google JS bundle is cached by the browser across chat sessions; repeated map artifacts in the same browser do not re-pay the load cost.",
      "",
      "## Safety Notes",
      "",
      "- The API key reaches the sandboxed iframe for Maps JavaScript (Maps JS keys are designed to be public; security comes from Google Cloud Console restrictions).",
      "- Restrict the key to the APIs and app origins you actually use before shipping to anyone else with access to the deployment.",
      "- Do not store the key in markdown memory or artifact bodies.",
      "- The MapRender tool validates artifact payloads against a strict schema; never write the API key, mapId, or any rendering implementation details into the artifact JSON.",
      "- Do not write the key into the artifact JSON — the renderer wires the provider automatically based on the `basemap` field.",
      "",
    ].join("\n"),
  },
  {
    id: "weather",
    label: "Weather runbook",
    relativePath: "INTEGRATIONS/weather.md",
    description:
      "Agent setup and operating guide for live weather cards (Google Weather API, iOS-style artifact).",
    defaultContent: [
      "# Weather Integration Runbook",
      "",
      "Use this runbook when the user asks to enable, configure, repair, or troubleshoot weather cards in the chat.",
      "",
      "## Capability",
      "",
      "- Render live weather forecasts inline as `application/vnd.ant.weather` artifacts via the `WeatherShow` tool.",
      "- iOS-style layout: hero card with condition-driven gradient and animated rain/snow particles, 24-hour scroll strip, 10-day forecast with temperature range bars, detail grid (UV, wind, sunrise/sunset arc, humidity, visibility, feels-like, pressure), optional air quality tile.",
      "- **Two-tier provider chain**: Google Weather first when `GOOGLE_MAPS_API_KEY` is set and Weather API enabled; Open-Meteo (keyless, ECMWF-backed) as automatic fallback. Weather works for every user out of the box — the Google key just upgrades description quality and environmental detail.",
      "- Optional **Google Air Quality API** for local AQI + PM2.5/PM10/O3 readings on the card. Open-Meteo also supplies AQ via CAMS as fallback.",
      "- Optional **Google Pollen API** for Universal Pollen Index (`TREE`, `GRASS`, `WEED`) and health recommendations on the card. Open-Meteo supplies keyless seasonal pollen fallback (`alder`, `birch`, `grass`, `mugwort`, `olive`, `ragweed`) when Google Pollen is unavailable.",
      "- Geocoding: Google Geocoding (preferred when key present) → Open-Meteo Geocoding API (free, multilingual) as fallback.",
      "- 10-minute in-memory cache keyed on (lat, lng, units) to avoid hammering upstreams on repeated requests.",
      "",
      "## Implementation Surface",
      "",
      "Workspace env vars:",
      "- `GOOGLE_MAPS_API_KEY` (optional) — Google Cloud Maps Platform key. When present and the Weather API is enabled, WeatherShow uses Google Weather as primary provider. When absent or the Weather API is not enabled, WeatherShow falls through to Open-Meteo (keyless, no setup). Weather, Air Quality, and Pollen each need a separate enable step in the GCP project.",
      "",
      "Setup tool:",
      "- `WeatherStatus` — reports BOTH provider states: Google (`configured`, `connected`, `error`) and Open-Meteo (`available`). Returns `anyProviderReady: true` when at least one will answer — almost always true since Open-Meteo is keyless. `providerInUse` tells the orchestrator which one will be picked next.",
      "",
      "Operational tools (granted directly to the orchestrator, no activation gate):",
      '- `WeatherShow` — one tool, end-to-end. Takes a place name or "lat,lng" pair, geocodes (Google → Open-Meteo fallback), picks the best available provider (Google → Open-Meteo fallback), fetches current + hourly + daily forecast (+ optional air quality), transforms to the canonical `WeatherArtifactSchema`, caches the result for 10 minutes, and returns { body, providerUsed, suggestGoogleUpgrade, ... } to the orchestrator.',
      "",
      "## Setup Flow",
      "",
      "1. Call `WeatherStatus`. If `anyProviderReady` is true, weather works. If `providerInUse` is `google`, you are fully set up. If `providerInUse` is `open-meteo`, the fallback works but you can offer the user to enable Google for richer descriptions and local air quality.",
      "",
      "2. If the user wants to enable Google (or you are setting up from scratch and they confirmed):",
      "   - Direct the user to https://console.cloud.google.com/google/maps-apis to create or pick a project and create/reuse the API key from the Maps integration.",
      "   - Recommend enabling the **Weather API** at https://console.cloud.google.com/apis/library/weather.googleapis.com, optionally the **Air Quality API** at https://console.cloud.google.com/apis/library/airquality.googleapis.com, and the **Pollen API** at https://console.cloud.google.com/apis/library/pollen.googleapis.com — each is a separate enable step from creating the key.",
      "   - When the user provides the key, call `SetEnv` with name `GOOGLE_MAPS_API_KEY`. Do not echo the key back.",
      "",
      "3. If `configured` is true but `connected` is false:",
      '   - Inspect the `error` field on `WeatherStatus`. If it mentions "Weather API has not been used in project" or `SERVICE_DISABLED`, the user needs to enable Weather API in their GCP project. Surface the exact activation URL from Google\'s error.',
      "   - If the error mentions `API_KEY_INVALID` or 401, the key is wrong; ask the user to re-paste.",
      "   - If the error mentions `BILLING_DISABLED` or quota, the user needs to enable billing on the GCP project. Maps Platform requires a billing account; usage stays well under the monthly free credit for any reasonable single-user volume.",
      "   - After any change, call `WeatherStatus` with `refresh: true` to skip the 5-minute cache.",
      "",
      '4. Verify by composing a test artifact: call `WeatherShow` with a known location ("Bucharest"). If the card renders, you are done.',
      "",
      "## Cost Notes",
      "",
      "- Google Weather API: ~$0.001 per current call, ~$0.003 per forecast call. The $200/month Maps Platform free credit covers any reasonable single-user volume.",
      "- Google Pollen API: billed separately under Maps Platform environmental APIs; single-user card usage should remain tiny under the same monthly credit.",
      "- Geocoding API (called per place-name lookup): $5 / 1000 requests; same free credit. Negligible at single-user volume.",
      "- WeatherShow uses a 10-minute in-memory cache keyed on location/provider/units/date horizon, so repeated cards in the same process avoid needless upstream calls.",
      "",
      "## Safety Notes",
      "",
      "- The API key is server-only; it never reaches the artifact renderer. The renderer receives validated JSON only.",
      "- Do not store the key in markdown memory or artifact bodies.",
      "- Do not write the key into the artifact JSON — the renderer is theme-driven and does not need provider credentials.",
      "",
    ].join("\n"),
  },
  {
    id: "location-intelligence",
    label: "Location Intelligence runbook",
    relativePath: "INTEGRATIONS/location-intelligence.md",
    description:
      "Agent setup guide for optional Home Assistant location journaling, raw observations, retention, daily summaries, and Library Places.",
    defaultContent: [
      "# Location Intelligence Runbook",
      "",
      "Use this runbook only after the user explicitly asks to set up or inspect Location Intelligence. Do not enable tracking by default.",
      "",
      "## Capability",
      "",
      "- Ingest Home Assistant location updates through a webhook into a local microscript journal.",
      "- Store local files under `microscripts/<scriptId>/files/location/`: `points.jsonl`, `days/*.json`, `routine.json`, and `place_aliases.json`.",
      "- Preserve every raw Home Assistant webhook sample in `points.jsonl`; filtering belongs in summaries and interpretation, not in the raw journal.",
      "- Let a daily scheduled agent summarize the journal into day JSON files without clustering sparse Home Assistant points into synthetic stops.",
      "- Infer raw observation stays from the gap until the next webhook sample. A gap of at least 7 minutes means the previous point is an inferred stay, regardless of an `Automotive`/motion activity label; do not treat the activity label as proof of movement across that silent gap.",
      "- Gym day summaries must derive `gym_detected` and gym session fields from confirmed session state (`current_session.notified`, `confirmed_at`, `ended_at`, weekly session ids) and from a valid `gym_candidate` -> `gym_departure` dwell, not only from a raw `gym_arrival_confirmed` row.",
      "- For manual/non-webhook runs, daily maintenance must run before pending adherence handling so the just-ended local day always writes `days/YYYY-MM-DD.json` and `routine.json`, even when a weekly adherence check is pending or deferred.",
      "- Persist place labels that Library > Places can display in `place_aliases.json`; do not rely on scheduled task `task_state` or run summaries for UI labels.",
      "- Show the result in Library > Places as a Google map, route approximation, day selector, stats, summarized Places, and Raw observations.",
      '- Retention is explicit: finite `retentionDays` or `retention: "forever"` / keep everything.',
      "- Maps mode is explicit: `strict`, `balanced`, or `relaxed`.",
      "",
      "## Safety And Consent",
      "",
      "- Ask for opt-in before creating any webhook, microscript, scheduled task, or config entry.",
      "- Explain that location history is sensitive and local to this Orchestrator workspace unless the user exports or shares it.",
      '- Ask the user to choose retention before enabling tracking. Include the option "keep everything" / `retention: "forever"` alongside finite retention.',
      "- Preserve the label `home` when it appears, but do not reverse-geocode or display exact home addresses in user-facing copy.",
      "- Do not store Home Assistant tokens or webhook secrets in `config.json`; secrets belong in the existing env/secret surfaces.",
      "",
      "## Config Shape",
      "",
      "Store non-secret config in workspace `config.json` under `locationIntelligence`:",
      "",
      "```json",
      "{",
      '  "enabled": true,',
      '  "source": {',
      '    "type": "home-assistant-webhook",',
      '    "entityId": "person.example",',
      '    "label": "Home Assistant person entity"',
      "  },",
      '  "journalScriptId": "ms_...",',
      '  "dailyTaskId": "sch_...",',
      '  "retentionDays": 90,',
      '  "mapsMode": "balanced"',
      "}",
      "```",
      "",
      'For unlimited retention, replace `retentionDays` with `"retention": "forever"`.',
      "",
      "## Status And UI",
      "",
      "- `GET <app_origin>/api/integrations/status` includes `locationIntelligence` with configured/enabled/status/source/retention/script/task fields.",
      "- `GET <app_origin>/api/library/places` lists available days from both daily summaries and raw `points.jsonl`, with summary counts only.",
      "- `GET <app_origin>/api/library/places/<YYYY-MM-DD>` returns one day with summarized stops, raw observations, and display route coordinates.",
      "- Missing config or missing files must be treated as an empty/setup state, not as a fatal error.",
      "- Daily agent review should reverse-geocode the start point of meaningful inferred stays (>=7 min), except `home`; when reverse geocoding produces a useful non-home address/label, persist it to `place_aliases.json` as a coordinate alias so Library > Places can display it. `task_state` is only run bookkeeping and is not a UI label cache.",
      "- If the reverse-geocoded label is only a broad/uncertain address, keep `confidence` low or mark it as `inferred_reverse_geocode`; ask Horia later only when a semantic label more specific than the address is useful.",
      "",
      "## Setup Flow",
      "",
      "1. Confirm the user wants Location Intelligence enabled and understands it stores location history locally.",
      "2. Confirm Home Assistant is connected or ask the user to configure it first using the Home Assistant runbook.",
      "3. Identify the Home Assistant `person.*` or `device_tracker.*` entity the user wants to track. Ask when ambiguous.",
      "4. Ask for retention: a finite number of days or keep everything.",
      "5. Ask for Maps mode: `strict` for conservative route display, `balanced` for normal defaults, or `relaxed` for more approximate route reconstruction.",
      "6. Create or identify the microscript that writes every webhook sample to `points.jsonl` and a scheduled daily agent task that summarizes days.",
      "   - The daily task prompt must include the sparse-webhook stay rule: a `>=7 min` gap means an inferred stay at the previous point even if activity says `Automotive`/motion.",
      "   - The microscript daily summary logic must set `gym_detected`/gym session fields from confirmed session state and from valid `gym_candidate` -> `gym_departure` dwell intervals. Do not require a `gym_arrival_confirmed` raw row; delayed/manual confirmation can update state without adding that row.",
      "   - For non-webhook/manual triggers, run daily maintenance first. Pending adherence checks may be sent, cleared, or deferred only after the just-ended local day file and `routine.json` write requests have been prepared.",
      "   - The daily task prompt must instruct the agent to reverse-geocode meaningful inferred-stay start points except `home`, and to persist every useful non-home reverse-geocoded label/address to `place_aliases.json` as a coordinate alias.",
      "   - The daily task prompt must state that `task_state` is private run bookkeeping and is not a UI label cache; Library > Places reads `place_aliases.json`.",
      "7. Update `config.json` with the non-secret fields above. Do not hardcode one user or assistant name.",
      "8. Verify Settings > Auth > Location Intelligence and Library > Places show the expected status.",
      "",
    ].join("\n"),
  },
]

export function buildIntegrationRunbooksContext(): string {
  const lines = INTEGRATION_RUNBOOKS.map(
    (runbook) =>
      `- ${runbook.id}: ${runbook.relativePath} - ${runbook.description}`
  )

  return [
    "<integration_runbooks>",
    "Service-specific setup guides are available in the workspace. When the user asks to configure, connect, repair, or verify an integration, follow the relevant runbook end-to-end instead of defaulting to UI instructions.",
    "Keep context bounded: do not read every runbook. Read only the specific runbook for the service you are about to configure or operate.",
    `Index: ${INTEGRATION_INDEX_PATH}`,
    "Available runbooks:",
    ...lines,
    "</integration_runbooks>",
  ].join("\n")
}
